<?php
//$this->plugin('basePath')->setBasePath($this->basePath().'/public');
 $path=$this->basePath();
?> 
<?php
 $SightseeingDetails = $_SESSION['SightseeingDetails'];
 $ShowsDetails = $_SESSION['ShowsDetails']; 
 $guideDetails = $_SESSION['guideDetails']; 
 $guide_fare = $_SESSION['guide_fare'];
 $NoOfday=$_SESSION['NoOfday'];

// echo $SightseeingDetails['s_id'];die;
 $_SESSION['vehicleId']
//$qry = "select * from ";
 //echo $ShowsDetails['s_id'];
/* foreach($guide_fare as $SD)
 {
	echo $SD['s_id']; 
   echo $SD['name']; 
   echo $SD['fare'];
 }     */
?>
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>welcome to Hello 42</title>
<!-- Custom Theme files -->

<!-- //Custom Theme files -->
<link href="<?php echo $path; ?>/public/css/bootstrap_out.css" type="text/css" rel="stylesheet" media="all">
<link href="<?php echo $path; ?>/public/css/style_out.css" type="text/css" rel="stylesheet" media="all">
<link href="<?php echo $path; ?>/public/css/newcss_out.css" media="screen" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="<?php echo $path; ?>/public/css/flexslider.css" type="text/css" media="screen" />

<script src="<?php echo $path; ?>/public/js/searchEngin.js" type="text/javascript"></script>
<script type="text/javascript"> 
<!-- 
function showMe (it, box) { 
var vis = (box.checked) ? "block" : "none"; document.getElementById(it).style.display = vis;
} 


//--> 
</script>
<script type="text/javascript"> 
<!-- 
function showMe1 (it, box) { 
var vis = (box.checked) ? "none" : "block"; document.getElementById(it).style.display = vis;
} 

//--> 
</script>

 

<style>

.summary{}
.details h2, .summary h2{padding: 7px 10px; background: #f1f1f1; font-size:22px;}
.details .inner, .summary .inner{padding: 10px; min-height: 250px;}
.summary .inner{font-size: 12px;}
.summary .bookcimg{border:1px solid #ccc; padding:7px; box-shadow: 0px 0px 1px #ccc; margin:5px 0 20px; max-width: 260px;}
.summary .inner .info{padding:3px 0}
.summary .inner .infopay{padding: 10px 0;}
.summary .inner .infopay .title{font-size: 14px; display: inline-block; width:150px;}
.summary .inner .infopay .price{font-size: 14px; padding: 4px 0 4px 20px; font-weight:bold; font-family: arial; display: inline-block}
.summary .inner .info ul{padding:5px 0; list-style: none ; margin-top: 0px}
.summary .inner .info ul li{padding:3px 0}

lable
{
	font-size:12px !important
}


input[type=checkbox] {
		display:;
	}

	input[type=checkbox] + label {
		display:inline-block;
		margin:-2px;
		padding: 4px 32px;
		margin-bottom: 0;
		font-size: 14px;
		line-height: 20px;
		color: #333;
		text-align: center;
		text-shadow: 0 1px 1px rgba(255,255,255,0.75);
		vertical-align: middle;
		cursor: pointer;
		background-color: #f5f5f5;
		background-image: -moz-linear-gradient(top,#fff,#e6e6e6);
		background-image: -webkit-gradient(linear,0 0,0 100%,from(#fff),to(#e6e6e6));
		background-image: -webkit-linear-gradient(top,#fff,#e6e6e6);
		background-image: -o-linear-gradient(top,#fff,#e6e6e6);
		background-image: linear-gradient(to bottom,#fff,#e6e6e6);
		background-repeat: repeat-x;
		border: 1px solid #ccc;
		border-color: #e6e6e6 #e6e6e6 #bfbfbf;
		border-color: rgba(0,0,0,0.1) rgba(0,0,0,0.1) rgba(0,0,0,0.25);
		border-bottom-color: #b3b3b3;
		filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff',endColorstr='#ffe6e6e6',GradientType=0);
		filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
		-webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,0.2),0 1px 2px rgba(0,0,0,0.05);
		-moz-box-shadow: inset 0 1px 0 rgba(255,255,255,0.2),0 1px 2px rgba(0,0,0,0.05);
		box-shadow: inset 0 1px 0 rgba(255,255,255,0.2),0 1px 2px rgba(0,0,0,0.05);
	}

	input[type=checkbox]:checked + label {
		   background-image: none;
		outline: 0;
		
			background-color:#e0e0e0;
	}
	

	label {
    color: #5c5c5c !important;
    font-family: "Open Sans",sans-serif;
    font-size: 12px !important;
    font-weight: normal !important;
    padding: 5px 0 0;
}

</style>


<script language="javascript" type="text/javascript">
        function togglemodify(id, btn_id) {
			//alert(1);
            //debugger;
            var btnId = btn_id.v
//            var e = document.getElementById(id);
//            var b = document.getElementById(btn_id);
            //            e.style.display = e.style.display == "none" ? "block" : "none";
			//$("#1").css("display","block");
            $("#modify_search").slideToggle(500);
            if ($("#btnModify").val() == "Modify Search (+)") {
                $("#btnModify").val("Modify Search (-)");
            }
            else { $("#btnModify").val("Modify Search (+)"); }
//            b.value = e.style.display == "block" ? "Hide Search" : "Change Search";
//           
//            b.value = e.style.display == "none" ? "Change Search" : "Hide Search";
           
//            if (e.style.display = 'none') {
//                e.style.display = 'block';
//                b.value = "Hide search";

//            }
//            else  {
//                e.style.display = 'none';
//                b.value = "Change search";
//            }

        }

        function gotoResult() {


            if (Validate_Me()) {
                if (TransValue())
                    return true;
                else
                    return false;
            }
            else {
                return false;
            }
        }
    </script>


<style>
input[type=radio] {
		display:;
	}

	input[type=radio] + label {
		display:inline-block;
		margin:-2px;
		padding: 4px 32px;
		margin-bottom: 0;
		font-size: 14px;
		line-height: 20px;
		color: #333;
		text-align: center;
		text-shadow: 0 1px 1px rgba(255,255,255,0.75);
		vertical-align: middle;
		cursor: pointer;
		background-color: #f5f5f5;
		background-image: -moz-linear-gradient(top,#fff,#e6e6e6);
		background-image: -webkit-gradient(linear,0 0,0 100%,from(#fff),to(#e6e6e6));
		background-image: -webkit-linear-gradient(top,#fff,#e6e6e6);
		background-image: -o-linear-gradient(top,#fff,#e6e6e6);
		background-image: linear-gradient(to bottom,#fff,#e6e6e6);
		background-repeat: repeat-x;
		border: 1px solid #ccc;
		border-color: #e6e6e6 #e6e6e6 #bfbfbf;
		border-color: rgba(0,0,0,0.1) rgba(0,0,0,0.1) rgba(0,0,0,0.25);
		border-bottom-color: #b3b3b3;
		filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff',endColorstr='#ffe6e6e6',GradientType=0);
		filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
		-webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,0.2),0 1px 2px rgba(0,0,0,0.05);
		-moz-box-shadow: inset 0 1px 0 rgba(255,255,255,0.2),0 1px 2px rgba(0,0,0,0.05);
		box-shadow: inset 0 1px 0 rgba(255,255,255,0.2),0 1px 2px rgba(0,0,0,0.05);
	}

	input[type=radio]:checked + label {
		   background-image: none;
		outline: 0;
		
			background-color:#ccc;
	}
	
</style>



  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
	
	<!-- banner-bottom -->
	<div class="banner-bottom pcenter" >
		<!-- container -->
		<div class="container">
        
		<div class="choose">
      <div class="destinations-grid-info tours">
        <div class="td-grids">
          <div class="col-md-31 sightmargin" align="left">
            <p>
              <label><strong> From:</strong></label>
              <br>
              <label> <?php echo $_SESSION['outRoundtripfrom']; ?></label>
            </p>
          </div>
          <div class="col-md-31 sightmargin" align="left">
            <p>
              <label><strong> To:</strong></label>
              <br>
              <label> <?php echo $_SESSION['outRoundtripto']; ?></label>
            </p>
          </div>
          <div class="col-md-31 sightmargin sightmargin2" align="left">
            <p>
              <label><strong> Departure Date:</strong></label>
              <br>
              <label> <?php echo $_SESSION['outstation_Ddate']; ?></label>
            </p>
          </div>
          <div class="col-md-31 sightmargin" align="left">
            <p>
              <label><strong> Pickup Address:</strong></label>
              <br>
              <label> <?php echo $_SESSION['outPickupAddress']; ?></label>
            </p>
          </div>
          <div class="col-md-31 sightmargin sightmargin2" align="left">
            <p>
              <label><strong> Pickup Time:</strong></label>
              <br>
              <label> <?php echo $_SESSION['outPickupTimeH']; ?>:<?php echo $_SESSION['outPickupTimeM']; ?></label>
            </p>
          </div>
          <div class="col-md-31 sightmargin" align="left">
            <p>
              <label><strong> Adults:</strong> <?php echo $_SESSION['outstationAdults']; ?></label>
              <br>
              <label> <strong> Children:</strong> <?php echo $_SESSION['outstationChilds']; ?></label>
            </p>
          </div>
          <div class="col-md-31 sightmargin3" align="left">
            <p>
              <label> <strong>Car Type:</strong></label>
              <br>
              <label> <?php  $cartype = $_SESSION['cartype'];
								     if($cartype ==1)
									 {
										 echo "Economy";
									 }
									 elseif($cartype == 2)
									 {
										 echo "Sedan";
									 }
									 else
									 {
										echo "Prime"; 
									 }

								  ?></label>
            </p>
          </div>
          <div class="col-md-31 sightmargin" align="left">
            <p>
              <input id="btnModify" class="modify_text" value="Modify Search (+)" onClick="javascript:togglemodify('1','btnBack');" type="button">
            </p>
          </div>
          <div class="col-xs-2 td-right" style="width:100%;">
            <div id="modify_search" style="width: 100%; border-radius: ; border: ; padding: 5px; display:none ;"> 
              
            <!--Outstation Start-->
<form id="outstationForm" name="outstationForm" method="post" action="<?php echo $this->basePath('login/index/carlistoutstation')?>">
<div id="booking_outstation" class="portlet portlet-purple" style="border: 0;border-top: 1px solid #d2d2d2; margin:0; display:;">
  <div id="inputSizing" class="panel-collapse in" style="height: auto;">
    <div class="portlet-body " style="padding:10px 15px 0;">
      <div id="popAlert" style="display:none;">
        <div class="row">
          <div class="col-sm-12" style="text-align:center;" >
            <p style="border-bottom: 1px solid #ff3f3f; color:#ff3f3f">We can not confirm online booking as such short notice.</br>
              Please call (011)42424242 for immediate bookings and confirmations.</p>
          </div>
        </div>
      </div>
      
      <!--================alert for same day============ --> 
      
      <!--================alert for same day============ -->
      
      <div class="row">
    <div class="form-group clearfix" style="margin:0;">
      <div class="col-sm-11" style="margin-left:10px;">
      
      
      
               <?php 
	  if($_SESSION['optionsInlineRadios']==1)
	  {
	  ?>
	   <label class="radio-inline specs mytip" name="optionsInlineRadios" onclick="roundtrip()" value="1" checked="" style="margin-left::10px;">
        <div class="radioWrap">
           <input type="radio" name="optionsInlineRadios" onClick="roundtrip()" class="radiobtnalign" value="1" checked="">
          <span></span></div>
       <span id="outstation_roundtrip"></span>
        </label>
      <?php 		
	  }
	  else if($_SESSION['optionsInlineRadios']==2)
	  {
      ?>

         <label class="radio-inline specs" style="padding-left:47px !important;">
        <div class="radioWrap">
          <input type="radio" name="optionsInlineRadios" onClick="oneway();" class="radiobtnalign" value="2">
          <span></span></div>
        <span id="" style="color:#fff;">Oneway</span>
        </label>
        
          <?php
	  }
	  else
	  {
	  ?>         
         <label class="radio-inline specs" style="padding-left:47px !important;">
        <div class="radioWrap">
           <input type="radio" id="selectMulticity" name="optionsInlineRadios" onClick="multicity();" class="radiobtnalign" value="3">
          <span></span></div>
        <span id="" style="color:#fff;">Multicity</span>
        </label>
        
         <?php } ?>
      </div>
    </div>
    
  </div>
      
      
      
      
      <!--multiple country-->
      <div> 
        
        <!--multiple country End-->
        <hr style="margin:5px auto 10px;"/>
		<?php if($status == 0){
                              echo $status;                       ?>
         <div class="row clearfix" style="padding-bottom:10px; display: block" id="userInfoLocal" >
            <div class="form-group padding_margin0">
              <label for="textInput" class="col-sm-21 control-label" id="">Name <span style="color:#F00">*</span></label>
              <div class="col-sm-2">
              <input id="outstationName" value="<?php echo $_SESSION['outstationName']; ?>" name="outstationName" type="text" class="form-control ui-autocomplete-input inputfild outstation_name" placeholder="Full Name">
              </div>
            </div>
            <div class="form-group padding_margin0">
              <label for="textInput" class="col-sm-21 control-label " style="padding-left:0; padding-right:0;" id="">Mobile No. <span style="color:#F00">*</span></label>
              <div class="col-sm-2">
                 <input id="outstationMobile" value="<?php echo $_SESSION['outstationMobile']; ?>" name="outstationMobile" type="text" class="form-control ui-autocomplete-input inputfild outstation_phno" placeholder="Mobile No." >
            </input>
              </div>
            </div>
            
            <div class="form-group padding_margin0">
             
              <div class="col-sm-2">
                 <input id="outstationMobile2" value="<?php echo $_SESSION['outstationMobile2']; ?>" name="outstationMobile2" type="text" class="form-control ui-autocomplete-input inputfild outstation_phno" placeholder="Mobile No2." >
            </input>
              </div>
            </div>
            
            
            
            <div class="form-group padding_margin0">
              <label for="textInput" class="col-sm-1 control-label" id="">Email <span style="color:#F00">*</span></label>
              <div class="col-sm-41 col-sm-21outdate1">
               <input id="outstationEmail" name="outstationEmail" value="<?php echo $_SESSION['outstationEmail']; ?>" type="email" class="form-control ui-autocomplete-input inputfild" placeholder="Email">
            </input>
              </div>
            </div>
          </div>
          
		<?php } ?> 
          
          
          <div class="row" id="countryMultiple" style="display:block" >
          <div class="col-md-12 col-lg-12 multiplerow">
            <div class="" style="padding:5px 0;">
              <label id="" class="col-sm-21" style="color:#fff;">From<span style="color:#F00">*</span></label>
              <div class="col-sm-2">
               <select id="outRoundtripfrom" name="outRoundtripfrom" onChange="citySelection4(this.value)" class="form-control check_booking" >
             
                  <option value="<?php echo $_SESSION['outRoundtripfrom']; ?>" ><?php echo $_SESSION['outRoundtripfrom']; ?></option>
              </select>
              </div>
              <label id="outstation_to"  class="col-sm-21 col-sm-21inter" style="display:block; color:#fff; width:4% !important;">To<span style="color:#F00">*</span></label>
               <div class="col-sm-2">
                    <select id="outRoundtripto" name="outRoundtripto" class=" form-control" onChange="mapping(this.id);">
			  <option value="<?php echo $_SESSION['outRoundtripto']; ?>" ><?php echo $_SESSION['outRoundtripto']; ?></option>
              </select>
              </div>
              
              <label id="" class="col-sm-21"  style="color:#fff; margin-right:8px;">Departure<span style="color:#F00">*</span></label>
               <div class="col-sm-2">
               
   <input name="outstation_Ddate" id="outstation_Ddate" type="text" class=" form-control inputfild" onChange="StationpickHour(0);" value="<?php echo $_SESSION['outstation_Ddate']; ?>" />
              </div>
              
               
               <div class="col-sm-2 col-sm-21out">
             <select id="outPickupTimeH" name="outPickupTimeH" onchange="StationpickHour();" name="field_8h" class="form-control">
              <option value="<?php echo $_SESSION['outPickupTimeH']; ?>"><?php echo $_SESSION['outPickupTimeH']; ?></option>
             
            </select>
              </div>
              
               <div class="col-sm-21 col-sm-21out">
          
           <select id="outPickupTimeM" name="outPickupTimeM" class=" form-control">
              <option value="<?php echo $_SESSION['outPickupTimeM']; ?>"><?php echo $_SESSION['outPickupTimeM']; ?></option>
              
            </select>
          </div>
            
             <div class="col-sm-21 col-sm-21out">
            
          <input type="textbox" id="no_ofdays" name="NoOfday" onFocus="" class=" form-control inputfild" placeholder="No. of Day" value="<?php echo $_SESSION['NoOfday']; ?>">
           
			<input type="hidden" name="BookingType" value="104">
           
          </div>
              
              
            </div>
            
            
          </div>
          
          <div class="col-md-12 col-lg-12 multiplerow">
            <div class="" style="padding:5px 0;">
              <label id="" class="col-sm-21" style="color:#fff;">From<span style="color:#F00">*</span></label>
              
              <div class="col-sm-2">

						<input id="cityFromr1" class="form-control inputfild" type="text" value="<?php echo $_SESSION['outRoundtripto']; ?>" ><?php echo $_SESSION['outRoundtripto']; ?>">

              <!-- <select id="outRoundtripfrom" name="outRoundtripfrom" class="form-control check_booking" >-->
                <!--                                                  	<option>Please Select</option>
                                                        <option value="Delhi/NCR">Delhi/NCR</option>-->
              <!--</select>-->
              </div>
              <label id="outstation_to"  class="col-sm-21 col-sm-21inter" style="display:block; color:#fff; width:4% !important;">To<span style="color:#F00">*</span></label>
               <div class="col-sm-2">
						<input id="cityFromt1" class="form-control inputfild" type="text" value="<?php echo $_SESSION['outRoundtripfrom']; ?>" ><?php echo $_SESSION['outRoundtripfrom']; ?>">
                 <!--<select id="outRoundtripto2" name="outRoundtripto2" class=" form-control" onchange="mapping(this.id);">
              </select> -->
              </div>
                                  <label id="" class="col-sm-21"  style="color:#fff; margin-right:8px;">Return<span style="color:#F00">*</span></label>
               <div class="col-sm-2">
               
              
 <input  name="outstation_Rdate" id="outstation_Rdate"  type="text" class=" form-control inputfild" value="<?php echo $_SESSION['outstation_Rdate']; ?>" />
              </div>
              
               <div class="col-sm-2 col-sm-21out">
           <select id="outReturnTimeH" name="outReturnTimeH" onchange="StationpickHourRet();" class="form-control">
              <option value="<?php echo $_SESSION['outReturnTimeH']; ?>"><?php echo $_SESSION['outReturnTimeH']; ?></option>
             
            </select>
              </div>
              
               <div class="col-sm-21 col-sm-21out">
          
            <select id="outReturnTimeM" name="outReturnTimeM" class=" form-control">
                <option value="<?php echo $_SESSION['outReturnTimeM']; ?>"><?php echo $_SESSION['outReturnTimeM']; ?></option>
            </select>
          </div>
            </div>
          </div>
        </div>
          <div class="row" id="countryoneway" style="display:none" >
          <div class="col-md-12 col-lg-12 multiplerow">
            <div class="" style="padding:5px 0;">
              <label id="" class="col-sm-21" style="color:#fff;">From<span style="color:#F00">*</span></label>
              <div class="col-sm-2">
               <select id="outRoundtripfrom" name="outRoundtripfrom" class="form-control check_booking" >
                <!--                                                  	<option>Please Select</option>
                                                        <option value="Delhi/NCR">Delhi/NCR</option>-->
              </select>
              </div>
              <label id="outstation_to"  class="col-sm-21 col-sm-21inter" style="display:block; color:#fff; width:4% !important;">To<span style="color:#F00">*</span></label>
               <div class="col-sm-2">
                  <select id="outRoundtripto" name="outRoundtripto" class=" form-control" onChange="mapping(this.id);">
              </select>
              </div>
              <label id="" class="col-sm-21"  style="color:#fff; margin-right:8px;">Departure<span style="color:#F00">*</span></label>
               <div class="col-sm-2">
              
    <input id="outstationone_Ddate" name="outstationone_Ddate" type="text" class=" form-control inputfild" onChange="" value=""
     placeholder="<?php echo date("d-m-Y")?>"/>
              </div>
              
              
               <div class="col-sm-2 col-sm-21out">
             <select id="outPickuponTimeH" onChange="StationpickHour();" name="outPickuponTimeH" class="form-control">
              <option value="hrs">Hrs</option>
             
            </select>
              </div>
              
               <div class="col-sm-21 col-sm-21out">
          
             <select id="outPickuponTimeM" name="outonPickupTimeM" class=" form-control">
              <option value="min">Min</option>
              
            </select>
          </div>
            
             <div class="col-sm-21 col-sm-21out">
            
          <input type="textbox" id="no_ofodays" name="NoOfoday" onFocus="DaysBetween();" class=" form-control inputfild" placeholder="No. of Day" value="">
           
			<input type="hidden" name="BookingType" value="104">
           
          </div>
              
              
            </div>
            
            
          </div>
          
        </div>
          
          
        
      </div>
      
      
      
      <!--multiple address-->
      <div id="addCity" style="display:none">
        <div class="row" >
          <div class="col-md-12 col-lg-12 multiplerow">
            <div class="" style="padding:5px 0;">
              <label id="" class="col-sm-21" style="color:#fff;">From<span style="color:#F00">*</span></label>
              <div class="col-sm-2">
              <select id="cityFrom0" name="field" onChange="citySelection5(this.value)" class="form-control outstationCities">
              </select>
              </div>
              <label id="outstation_to"  class="col-sm-21 col-sm-21inter" style="display:block; color:#fff; width:4% !important;">To<span style="color:#F00">*</span></label>
               <div class="col-sm-2">
                  <select id="multicityapd0" name="" class=" form-control" onChange="citySelection2(this.id); multiMap(this.id);">
                  </select>
              </div>
              <label id="" class="col-sm-21"  style="color:#fff; margin-right:9px">Departure<span style="color:#F00">*</span></label>
               <div class="col-sm-2">
              <input id="outstationM_Ddate" name="outstationM_Ddate" onChange="StationpickHour(0);" type="text"  class=" form-control datepick inputfild" placeholder="<?php echo date("d-m-Y")?>">
              </div>
              
               <div class="col-sm-2 col-sm-21out">
            <select id="outPickupTimeH1" name="outPickupTimeH1" onChange="StationpickHour1();" class="form-control">
              <option value="hrs">Hrs</option>
             
            </select>
              </div>
              
               <div class="col-sm-21 col-sm-21out">
          
            <select id="outPickupTimeM1" name="outPickupTimeM1" class=" form-control">
              <option value="min">Min</option>
             
            </select>
          </div>
            
             <div class="col-sm-21 col-sm-21out">
            
         <input type="textbox" name="Nofday" class=" form-control inputfild" placeholder="No of Day">
           
          </div>
              
              
            </div>
            
            
          </div>
          
        </div>
        <div class="row" >
          <div class="col-md-12 col-lg-12 multiplerow">
            <div class="" style="padding-top:5px;">
            
            <label id="" class="col-sm-21" style="color:#fff;">From<span style="color:#F00">*</span></label>
              <div class="col-sm-2">
               <input id="cityFrom1" type="text" class="form-control inputfild" >
              </div>
            
            <label id="" class="col-sm-21 col-sm-21inter" style="display:block; color:#fff; width:4% !important;">To<span style="color:#F00">*</span></label>
              <div class="col-sm-2">
               <select id="multicityapd1" name="" class=" form-control" onChange="citySelection2(this.id);multiMap(this.id); ">
                  </select>
              </div>
           
            
            <label id="" class="col-sm-21" style="color:#fff; margin-right:9px"">Departure<span style="color:#F00">*</span></label>
              <div class="col-sm-2">
               <input id="outstationM_Rdate" name="outstationM_Rdate" onChange="StationpickHour(0);" type="text"  class=" form-control datepick inputfild" placeholder="<?php echo date("d-m-Y")?>">
              </div>
           
           <div class="col-sm-21 col-sm-21out" style="padding-top:5px;">
            
            <select id="outPickupTimeH2" name="outPickupTimeH2" onChange="StationpickHour();" class="form-control">
              <option value="hrs">Hrs</option>
             
            </select>
          
         </div>
       
           <div class="col-sm-21 col-sm-21out" style="padding-top:5px;">
          
            <select id="outPickupTimeM2" name="outPickupTimeM2" class=" form-control">
              <option value="min">Min</option>
             
            </select>
          </div>
            
             <div class="col-sm-21 col-sm-21out" style="padding-top:5px;">
            
         <input type="textbox" name="Nofday" class=" form-control inputfild" placeholder="No of Day">
           
          </div>
          
            </div>
         
          </div>
        </div>
      </div>
      <!--add div form-->
      <div id="addCityForm" ></div>
      <!--add div form--> 
      
      <!--add button-->
      <div id="addCitybutton" onClick="addCitybutton();" style="display:none;width: 150px; font-family: arial; background: #333; font-weight: bold;padding: 2px 10px;margin-top: 5px;border: 1px solid #000; margin:10px 0 0"> <a href="#" style="color:white" id="outstation_addcity"></a> </div>
      <!--add button end--> 
      
	  
	  <div class="row" style="padding:10px 10px 0;">
      <div class="userInfoLocal" style="padding-left:5px;">
      
   <div class="row clearfix" style="padding-bottom:10px; display: block">
   
            <div class="form-group padding_margin0">
              <label for="textInput" class="col-sm-21 control-label" id="">Nationality </label>
              <div class="col-sm-2">
               <select id="outstationNationalit" name="outstationNationality" class="inputfild form-control valid" aria-invalid="false">
               <option value="<?php echo $_SESSION['outstationNationality']; ?>" id="localCabFor0"><?php echo $_SESSION['outstationNationality']; ?></option>
                <option value="Indian" id="localCabFor0">Indian</option>
                <option value="Non-Indian" id="localCabFor1">Non-Indian</option>
              </select>
              </div>
            </div>
            
            <div class="form-group padding_margin0">
              <label for="textInput" class="col-sm-21 col-sm-21local control-label " style="padding-left:0 !important; padding-right:0 !important;" id="">No. of Adults <span style="color:#F00">*</span></label>
              <div class="col-sm-21 col-sm-21out">
              <select id="outstationAdult" name="outstationAdults" class="inputfild form-control">
              <option value="<?php echo $_SESSION['outstationAdults']; ?>" ><?php echo $_SESSION['outstationAdults']; ?></option>
              </select>
              </div>
            </div>
            
            <div class="form-group padding_margin0">
             <label for="textInput" class="col-sm-2 control-label col-sm-21local " style="padding-left:0 !important; padding-right:0 !important;" id="">No. of Children </label>
              <div class="col-sm-21 col-sm-21out">
              <select id="outstationChild" name="outstationChilds" class="inputfild form-control">
              <option value="<?php echo $_SESSION['outstationChilds']; ?>" ><?php echo $_SESSION['outstationChilds']; ?></option>
              </select>
              </div>
            </div>
            
            <div class="form-group padding_margin0">
              <label for="textInput" class="col-sm-21 col-sm-21local control-label" id="" style="margin-right:-2px; padding-right:0 !important; padding-left:0 !important;">No. of Luggages </label>
              <div class="col-sm-21 col-sm-21out">
                <select id="outstationLuggage" name="outstationLuggages" class="inputfild form-control">
                <option value="<?php echo $_SESSION['outstationLuggages']; ?>" ><?php echo $_SESSION['outstationLuggages']; ?></option>
                
              </select>
              </div>
            </div>
            
          </div>
      
      </div>
      </div>
      
      
      <hr style="margin:6px auto 6px;"/>
      <div class="row" style="padding-left:10px;">
      
      <div class="form-group clearfix">
        <label class="col-sm-21" id="" style="margin-right:; padding-top:10px; color:#fff; padding-right:0 !important; padding-left:0 !important;">No of Cars </label>
        <div class="radioWrap col-sm-2" style="margin-top:5px; padding-left:0 !important;">
        
        <select id="NoOfCar_outstation" name="NoOfCar_outstation" class="inputfild form-control">
        
         <option value="<?php echo $_SESSION['NoOfCar_outstation']; ?>" selected ><?php echo $_SESSION['NoOfCar_outstation']; ?></option>
        
              </select>
        
      
          <span></span></div>
		 
       
        
       
        <div class="radioWrap col-sm-2" style="margin-top:5px;">
          <input type="text" name="coupan_code_outstation" placeholder="Coupon Code" id="coupan_code_outstation" onClick="" class="form-control ui-autocomplete-input inputfild loc_req_fields" >
          <span></span></div>
		  <label id="apply_coupancode_outstation" style="float:left; padding-top:10px; margin-right:10px;"><a href="#" > Apply Coupon </a></label>
          
       
          
		  <div id="outstation_coupan_msg"></div>
		  <div id=""> <input type="hidden" name="outstation_coupan_id" id="outstation_coupan_id" /> 
		  <input type="hidden" name="outstation_DiscountType" id="outstation_DiscountType" />
		  <input type="hidden" name="outstation_coupan_disount" id="outstation_coupan_disount" /> 
		  <input type="hidden" name="outstation_Promo_Name" id="outstation_Promo_Name" /></div>
       
       </div>
      </div>
      <div class="row">
      
      
      
    <div class="form-group clearfix" style="margin:0;">
      <div class="col-sm-11">
        <label id="local_carsTypes" style="margin-bottom:0; margin-right:24px; color:#fff;">Car Types</label>
        <label class="radio-inline specs mytip economy" data-toggle="tooltip" data-placement="bottom" title="Minimum Charge: 989">
        <div class="radioWrap">
          <input type="radio" name="cartype" onClick="carbook(this.id);" class="radiobtnalign" Value="1"  id="economy" checked="">
          <span></span></div>
        <span id="local_economy" style="color:;">Economy</span>&nbsp;&nbsp;<i class="fa fa-taxi fa-1_5x" style="color:;"></i>
        </label>
        <label class="radio-inline specs  mytip sedan" data-toggle="tooltip" data-placement="bottom" title=" Minimum Charge: 1455" style="padding-left:47px !important;">
        <div class="radioWrap">
           <input type="radio" name="cartype" onClick="carbook(this.id);" class="radiobtnalign" value="2"  id="prime">
          <span></span></div>
        <span id="local_prime" style="color:;">Sedan</span>&nbsp;&nbsp;<i class="fa fa-car fa-1_5x" style="color:;"></i>
        </label>
        <label class="radio-inline specs mytip prime" data-toggle="tooltip" data-placement="bottom" title="Minimum Charge: 1670" style="padding-left:47px !important;">
        <div class="radioWrap">
           <input type="radio" name="cartype" onClick="carbook(this.id);" class="radiobtnalign" value="3"  id="higher">
          <span></span></div>
        <span id="local_higher" style="color:;">Prime</span>&nbsp;&nbsp;<i class="fa fa-car fa-1_5x" style="color:;"></i>
        </label>
                        
      </div>
    </div>
    
  </div>
      
      
      <hr style=" margin-bottom:6px !important; margin-top:0 !important;"/>
      
      <div class="row">
      
      <div class="col-sm-11" style="margin-top:; margin-bottom:10px; color:;">
      Coming Mode is Flight 
      <label class="radio-inline specs mytip" data-toggle="" data-placement="bottom" title="" style="padding-left:47px !important;">
        <div class="radioWrap">
           <input type="radio" name="flightmode" onClick="showMe('didfv3', this)" class="radiobtnalign" value="yes"  id="">
          <span></span></div>
        <span id="local_higher" style="color:;">Yes</span
        ></label>
        
         <label class="radio-inline specs mytip" data-toggle="" data-placement="bottom" title="" style="padding-left:47px !important;">
        <div class="radioWrap">
           <input type="radio" name="flightmode" onClick="showMe1('didfv3', this)" class="radiobtnalign" value="no"  id="">
          <span></span></div>
        <span id="local_higher" style="color:;">No</span
        ></label>
      
      </div>
      
      </div>
      
       <div class="row" id="didfv3" style="display:none;">  
        <div class="form-group padding_margin0" style="margin-top:;">
          <label id="flight_nos1" name="flight_no" class="col-sm-2 control-label" >Flight No</label>
          <div class="col-sm-4">
            <input id="airFlightNo" type="text" class=" form-control inputfild" />
          </div>
        </div>
        <div class="form-group clearfix">
          <label id="flight_time" class="col-sm-2 control-label paddingleft30">Flight Time</label>
           <div class="col-sm-2">
             
            <select id="flightTimeH" name="flightTimeH" onChange="StationpickHour();" class="form-control">
              <option value="hrs">Hrs</option>
             
            </select>
          </div>
         
       
           <div class="col-sm-2">
          
            <select id="flightTimeM" name="flightTimeM" class=" form-control">
              <option value="min">Min</option>
             
            </select>
			<input type="hidden" name="BookingType" value="104">
          </div>
        </div>
      </div>
      
      
      <div class="row">
      	<div class="">
        <div class="form-group padding_margin0">
          <label id="" class="col-sm-2 form-contro" style="padding-left:10px;">Pickup Address*</label>
          <div class="col-sm-4">
            <textarea id="outPickupAddress" name="outPickupAddress" class="form-control StationPick "  placeholder="" onBlur="mappingOut();" style="height:40px !important;"><?php echo $_SESSION['outPickupAddress']; ?></textarea>
          </div>
        </div>
        <div class="form-group padding_margin0">
          <label id="outstation_pickup_time" class="col-sm-2 form-contro"></label>
          
        </div>
           </div>
             <div class="col-sm-12">   
        <div class="col-sm-6" style="margin-right: 1px; padding-left:0;" id="bookingGroundTrip"> 
       <a href="#" id="104"  type="button" class=" btn btn-lg bg-primary col-sm-12 makebookingbtn outstationBooking" value="Make Your Booking Now"/>Make Your Booking Now</a> 
        </div>
        <div class="col-sm-6" style="margin-right: 1px; padding-left:0; display:none" id="bookingMultyCity"> 
        <a href="#" onClick="bookingmulitCity();" type="button" class=" btn btn-lg bg-primary col-sm-12 makebookingbtn" value="" id="outstation_book"/></a> 
        </div>
        
        </div>
      </div>
    </div>
  </div>
</div>
</form>
<!--Outstation End-->
              
            </div>
          </div>
          <div class="clearfix"> </div>
        </div>
      </div>
    </div>
		
        
			<div class="banner-bottom-info">
				<h3>Travel Details</h3>
			</div>
			<div class="banner-bottom-grids">
				<div class="col-md-41 banner-bottom-grid">
               <div class="destinations-grid-info tours">
                           <div class="td-grids">
                           
                           <div class="slider">

<!--<h4>Add Sightseeing</h4>-->
<ul id="flexiselDemo3">
<li class="nbs-flexisel-item1">
								
									<img src="<?php echo $path; ?>/public/images/tajmahal.jpg" style="width:100%; height:250px;" alt="">
	</li>						
<li class="nbs-flexisel-item1">
								
									<img src="<?php echo $path; ?>/public/images/tajmahal.jpg"  style="width:100%; height:250px;" alt="">
	</li>
</ul>
</div></div></div>
<script type="text/javascript">
						 $(window).load(function() {			
						  $("#flexiselDemo3").flexisel({
							visibleItems: 1,
							animationSpeed: 1000,
							autoPlay: true,
							autoPlaySpeed: 5000,    		
							pauseOnHover:true,
							enableResponsiveBreakpoints: true,
							responsiveBreakpoints: { 
								portrait: { 
									changePoint:480,
									visibleItems: 1
								}, 
								landscape: { 
									changePoint:640,
									visibleItems: 1
								},
								tablet: { 
									changePoint:768,
									visibleItems: 1
								}
							}
						});
						});
						</script>
                        
         <div class="pcenter" id="pcenter">  
         
         
         <div class="choose">
          <h5>Add Sightseeings</h5>
          
         <div class="sightcont"  style="position:; float:left; background:#fff;  width:100%; min-height:0; z-index:99; left:5px; padding-left:10px; " 
align="center">

<ul class="sightinc">



</ul>
</div>
         </div>               
                        
<div class="choose">

              <h5>Sightseeings (<?php echo $_SESSION['outRoundtripfrom']; ?>)</h5>


<div class="sightcont">
<div class="destinations-grid-info tours">
                           <div class="td-grids">
                           
                           <div class="slider">

<!--<h4>Add Sightseeing</h4>-->
<ul class="sightadd" id="flexiselDemo1">
<?php	
$i=1;
	foreach($SightseeingDetails as $v){ 
	echo $v['guide_charge'];

?>
<li align="">
<div class="sdes" onclick="$(this).parent().find('.sdesc').fadeIn('medium')" align="center">
 <a  href="#" data-toggle="modal" data-target="#myModal<?php echo $i; ?>" style="cursor:pointer;" > 
<img src="<?php echo $path; ?>/public/images/sightseeing/<?php echo $v['image']; ?>" alt="" title="Click to View Detail"></a>
<div class="sname"><?php echo $v['name']; ?><br>
<p> <a href="#" data-toggle="modal" data-target="#myModal">
                                    View Detail</a></p>
</div>
</div>
<div class="sadd"  onclick="addSightSeeing($(this).parent(),7,<?php echo $v['fare'];?>)" style="margin-left:22%;">Add</div>
</li>
<?php $i++; 
}
?>


</ul>
</div></div></div>
</div>



</div>


          <script type="text/javascript">
						 $(window).load(function() {			
						  $("#flexiselDemo1").flexisel({
							visibleItems: 4,
							animationSpeed: 1000,
							autoPlay: true,
							autoPlaySpeed: 3000,    		
							pauseOnHover:true,
							enableResponsiveBreakpoints: true,
							responsiveBreakpoints: { 
								portrait: { 
									changePoint:480,
									visibleItems: 1
								}, 
								landscape: { 
									changePoint:640,
									visibleItems: 2
								},
								tablet: { 
									changePoint:768,
									visibleItems: 3
								}
							}
						});
						});
						</script>      
                
                <div class="choose">
					<div class="banner-bottom-right">
						
							<div class="choose-info">
							<h5>Add Sightseeings (Agra)</h5>
						</div>
                        <div class="sightcont">
							<div class="destinations-grid-info tours">
                           <div class="td-grids">
                           
                           <div class="slider">
				<div class="arrival-grids">			 
					 <ul class="sightadd" id="flexiselDemo4">

<li>
<div class="sdes" onclick="$(this).parent().find('.sdesc').fadeIn('medium')">
 <a  href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;"> 
<img src="<?php echo $path; ?>/public/images/tajmahal.jpg" alt="Bahai Temple" title="Click to View Detail"></a>
<div class="sname">Taj Mahal(Agra)<br>
<p> <a href="#" data-toggle="modal" data-target="#myModal">
                                    View Detail</a></p>
</div>
</div>



<div class="sadd" onclick="addSightSeeing($(this).parent(),7)" style="margin-left:22%;">Add</div>

</li>
<li>
<div class="sdes" onclick="$(this).parent().find('.sdesc').fadeIn('medium')">
 <a  href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;"> 
<img src="<?php echo $path; ?>/public/images/tajmahal.jpg" alt="Bahai Temple" title="Click to View Detail"></a>
<div class="sname">Taj Mahal(Agra)<br>
<p> <a href="#" data-toggle="modal" data-target="#myModal">
                                    View Detail</a></p>
</div>
</div>



<div class="sadd" onclick="addSightSeeing($(this).parent(),7)" style="margin-left:21%;">Add</div>

</li>
<li>
<div class="sdes" onclick="$(this).parent().find('.sdesc').fadeIn('medium')">
 <a  href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;"> 
<img src="<?php echo $path; ?>/public/images/tajmahal.jpg" alt="Bahai Temple" title="Click to View Detail"></a>
<div class="sname">Taj Mahal(Agra)<br>
<p> <a href="#" data-toggle="modal" data-target="#myModal">
                                    View Detail</a></p>
</div>
</div>



<div class="sadd" onclick="addSightSeeing($(this).parent(),7)" style="margin-left:21%;">Add</div>

</li>
<li>
<div class="sdes" onclick="$(this).parent().find('.sdesc').fadeIn('medium')">
 <a  href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;"> 
<img src="<?php echo $path; ?>/public/images/tajmahal.jpg" alt="Bahai Temple" title="Click to View Detail"></a>
<div class="sname">Taj Mahal(Agra)<br>
<p> <a href="#" data-toggle="modal" data-target="#myModal">
                                    View Detail</a></p>
</div>
</div>



<div class="sadd" onclick="addSightSeeing($(this).parent(),7)" style="margin-left:21%;">Add</div>

</li>
<li>
<div class="sdes" onclick="$(this).parent().find('.sdesc').fadeIn('medium')">
 <a  href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;"> 
<img src="<?php echo $path; ?>/public/images/tajmahal.jpg" alt="Bahai Temple" title="Click to View Detail"></a>
<div class="sname">Taj Mahal(Agra)<br>
<p> <a href="#" data-toggle="modal" data-target="#myModal">
                                    View Detail</a></p>
</div>
</div>



<div class="sadd" onclick="addSightSeeing($(this).parent(),7)" style="margin-left:21%;">Add</div>

</li>
<li>
<div class="sdes" onclick="$(this).parent().find('.sdesc').fadeIn('medium')">
 <a  href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;"> 
<img src="<?php echo $path; ?>/public/images/tajmahal.jpg" alt="Bahai Temple" title="Click to View Detail"></a>
<div class="sname">Taj Mahal(Agra)<br>
<p> <a href="#" data-toggle="modal" data-target="#myModal">
                                    View Detail</a></p>
</div>
</div>



<div class="sadd" onclick="addSightSeeing($(this).parent(),7)" style="margin-left:21%;">Add</div>

</li>
<li>
<div class="sdes" onclick="$(this).parent().find('.sdesc').fadeIn('medium')">
 <a  href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;"> 
<img src="<?php echo $path; ?>/public/images/tajmahal.jpg" alt="Bahai Temple" title="Click to View Detail"></a>
<div class="sname">Taj Mahal(Agra)<br>
<p> <a href="#" data-toggle="modal" data-target="#myModal">
                                    View Detail</a></p>
</div>
</div>



<div class="sadd" onclick="addSightSeeing($(this).parent(),7)" style="margin-left:21%;">Add</div>

</li>
<li>
<div class="sdes" onclick="$(this).parent().find('.sdesc').fadeIn('medium')">
 <a  href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;"> 
<img src="<?php echo $path; ?>/public/images/tajmahal.jpg" alt="Bahai Temple" title="Click to View Detail"></a>
<div class="sname">Taj Mahal(Agra)<br>
<p> <a href="#" data-toggle="modal" data-target="#myModal">
                                    View Detail</a></p>
</div>
</div>



<div class="sadd" onclick="addSightSeeing($(this).parent(),7)" style="margin-left:21%;">Add</div>

</li>
<li>
<div class="sdes" onclick="$(this).parent().find('.sdesc').fadeIn('medium')">
 <a  href="#" data-toggle="modal" data-target="#myModal" style="cursor:pointer;"> 
<img src="<?php echo $path; ?>/public/images/tajmahal.jpg" alt="Bahai Temple" title="Click to View Detail"></a>
<div class="sname">Taj Mahal(Agra)<br>
<p> <a href="#" data-toggle="modal" data-target="#myModal">
                                    View Detail</a></p>
</div>
</div>



<div class="sadd" onclick="addSightSeeing($(this).parent(),7)" style="margin-left:22%;">Add</div>

</li>
</ul>
                        
                        
                        
						<script type="text/javascript">
						 $(window).load(function() {			
						  $("#flexiselDemo4").flexisel({
							visibleItems: 4,
							animationSpeed: 1000,
							autoPlay: true,
							autoPlaySpeed: 3000,    		
							pauseOnHover:true,
							enableResponsiveBreakpoints: true,
							responsiveBreakpoints: { 
								portrait: { 
									changePoint:480,
									visibleItems: 1
								}, 
								landscape: { 
									changePoint:640,
									visibleItems: 2
								},
								tablet: { 
									changePoint:768,
									visibleItems: 3
								}
							}
						});
						});
						</script>
                        
                        <style>
.pkgcost {font-size: 25px; padding: 10px 0; background:#1C587B; color: #fff; border-radius:5px; margin-top:10px;}
</style>


<script>
document.getElementById('fromcity').selectedIndex=0;
document.getElementById('packform').reset();

var sightarray=new Array();
sightarray.push(1);
function removeSightSeeing(el,id){
  var btn="<div onclick='addSightSeeing($(this).parent(),"+id+")' class='sadd'>Add</div>";
  el.find('.sremove').remove();
  el.append(btn);
  $('.sightadd').append(el);
  sightarray.splice(sightarray.indexOf(id),1);
  document.getElementById('selsight').value=sightarray.toString();
  console.log(sightarray);
  console.log(document.getElementById('selsight').value);
}

function addSightSeeing(el,id,fare){
	alert(fare);
	$('.payaddon').html(fare);
	//alert(el);
	//alert(id);
  var btn="<div onclick='removeSightSeeing($(this).parent(),"+id+")' class='sremove'>Remove</div>";
  el.find('.sadd').remove();
  el.append(btn);
  $('.sightinc').append(el);
  sightarray.push(id);
  document.getElementById('selsight').value=sightarray.toString();
  console.log(sightarray);
  console.log(document.getElementById('selsight').value);
}




</script>
                        
                        
						<script type="text/javascript" src="<?php echo $path; ?>/public/js/jquery.flexisel.js"></script>			 
				</div>
			</div>
                       
                            
								
								<div class="clearfix"> </div>
							</div>
							</div>
						</div>
					</div>
                    
                  </div> 
                  
                  
                  
                  </div> 
                    
					<div class="choose">
						<div class="choose-info">
							<h5>Choose Your Driver</h5>
                            
                            <input type="radio" name="mype" value="ve1" onClick="showMe('didfv1', this)" />Yes &nbsp; <input type="radio" name="mype" value="ve1" onClick="showMe1('didfv1', this)" />No
						</div>
						<div class="destinations-grid-info tours" id="didfv1" style="display:none;">
                           <div class="td-grids">
								<div class="col-md-3 sightmargin" align="center">
									<img src="<?php echo $path; ?>/public/images/driver_icon.jpg" alt="" />
								                                    
							</div>
                            
                            <div class="col-md-3 sightmargin" align="center">
									<p>Hindi understanding & speaking Driver</p>
															
									
									<p>
                                    Hindi (Rs 0)</p>
									
                                    <p><input type="radio" id="radiodriver1" name="driver" value="all" checked="checked" >
       <label for="radiodriver1">+Add</label></p>
							</div>
                            
                            <div class="col-md-3 sightmargin" align="center">
									<p>English understanding & speaking Driver</p>
															
									
									<p>
                                    Englisg (Rs 500)</p>
									
                                    <p><input type="radio" id="radiodriver2" name="driver" value="all" >
       <label for="radiodriver2">+Add</label></p>
							</div>
                            
                      
                            
                            
								<div class="col-xs-2 td-right">
									
								</div>
								<div class="clearfix"> </div>
						  </div>
							</div>
					</div>
                    	<?php
			            //echo $NoOfday;
						$j=1;
						for($i=1; $i<=$NoOfday; $i++)
						{
							//echo "hello";
						
						?>  
                    <div class="choose">
						<div class="choose-info">
							<h5>Choose Your Guide</h5>
                             <input type="radio" name="mype" value="ve1" onClick="showMe('didfv2<?php echo $j; ?>', this)" />Yes &nbsp; <input type="radio" name="mype"  value="ve1" onClick="showMe1('didfv2<?php echo $j; ?>', this)" />No
						</div>
						
						<div class="destinations-grid-info tours" id="didfv2<?php echo $j; ?>" style="display:;">
                           <div class="td-grids">
					 <strong><?php echo "Day ".$j; ?></strong>
            <div class="slider">
			
				<div class="arrival-grids">			 
					 <ul id="flexiselDemo2<?php echo $j; ?>">
					 <?php 
					// foreach($guide_fare as $GF)
						// {
							//echo $GF['nationality']; 
						  // echo $GF['language']; 
						   //echo $GF['guide_charge'];
						  
					 ?>
						<li>
                        <p>English Speaking & Understanding Guide</p>
																							
									<p>
                                    Hindi (Rs 1000)</p>
									
                                    <p><input type="radio" id="radioguide1<?php echo $j; ?>" name="guide" value="all" checked="checked" >
       <label for="radioguide1<?php echo $j; ?>">+Add</label></p>
						 </li>
						<?php  //} ?>
						 
						 <li>
							 <p>English Speaking & Understanding Guide</p>
															
									
									<p>
                                    Hindi (Rs 1000)</p>
									
                                    <p><input type="radio" id="radioguide2<?php echo $j; ?>" name="guide" value="all" checked="checked" >
       <label for="radioguide2<?php echo $j; ?>">+Add</label></p>
						 </li>
                         <li>
							<p>English Speaking & Understanding Guide</p>
															
									
									<p>
                                    Hindi (Rs 1000)</p>
									
                                    <p><input type="radio" id="radioguide3<?php echo $j; ?>" name="guide" value="all" checked="checked" >
       <label for="radioguide3<?php echo $j; ?>">+Add</label></p>
						 </li>
                         <li>
							 <p>English Speaking & Understanding Guide</p>
															
									
									<p>
                                    Hindi (Rs 1000)</p>
									
                                    <p><input type="radio" id="radioguide4<?php echo $j; ?>" name="guide" value="all" checked="checked" >
       <label for="radioguide4<?php echo $j; ?>">+Add</label></p>
						 </li>
                         <li>
							 <p>English Speaking & Understanding Guide</p>
															
									
									<p>
                                    Hindi (Rs 1000)</p>
									
                                    <p><input type="radio" id="radioguide5<?php echo $j; ?>" name="guide" value="all" checked="checked" >
       <label for="radioguide5<?php echo $j; ?>">+Add</label></p>
						 </li>
                         <li>
							 
                            <p>English Speaking & Understanding Guide</p>
															
									
									<p>
                                    Hindi (Rs 1000)</p>
									
                                    <p><input type="radio" id="radioguide6" name="guide" value="all" checked="checked" >
       <label for="radioguide6<?php echo $j; ?>">+Add</label></p>
						 </li>
						</ul>
						<script type="text/javascript">
						 $(window).load(function() {			
						  $("#flexiselDemo2<?php echo $j; ?>").flexisel({
							visibleItems: 4,
							animationSpeed: 1000,
							autoPlay: true,
							autoPlaySpeed: 5000,    		
							pauseOnHover:true,
							enableResponsiveBreakpoints: true,
							responsiveBreakpoints: { 
								portrait: { 
									changePoint:480,
									visibleItems: 1
								}, 
								landscape: { 
									changePoint:640,
									visibleItems: 2
								},
								tablet: { 
									changePoint:768,
									visibleItems: 3
								}
							}
						});
						});
						</script>
									 
				</div>
				
			</div>
				
			<br>
            
            <div class="choose-info">
							<h5>Select for Full Days</h5>
                            
                            <input type="radio" name="mype" value="ve1" onClick="showMe1('didfv7<?php echo $j; ?>', this)" />Yes &nbsp; <input type="radio" name="mype" value="ve1" onClick="showMe('didfv7<?php echo $j; ?>', this)" />No
						</div>
                        
                          <div class="destinations-grid-info tours" id="didfv7<?php echo $j; ?>" style="display:none;">
                           <div class="td-grids">
								
                                <div class="mapcantiner_inner1" style="padding:0 !important;">
	<div class="" style="margin:0 0 10px; padding:5px 0 10px;">
     
                            
                             <div class="col-md-31 sightmargin overviueimg3" align="left" style="padding:0 !important;">
							
Day 1-
<br>

                			</div>
    
      <div class="col-md-31 sightmargin overviueimg5" align="left" >
									 <span class="vehicle_name">Tajmahal, Agra Fort,</span><br>
                                     
	
									
							</div>
                            
      
                            
                            <div class="col-md-31 sightmargin overviueimg3" align="left" >
									 <input name="" type="checkbox" value="">
                                      
	
									
							</div>  
                            
          
	
	
    </div>
    
    </div>
    
    <div class="mapcantiner_inner1" style="padding:0 !important;">
	<div class="" style="margin:0 0 10px; padding:5px 0 10px;">
     
                            
                             <div class="col-md-31 sightmargin overviueimg3" align="left" style="padding:0 !important;">
							
Day 2-
<br>

                			</div>
    
      <div class="col-md-31 sightmargin overviueimg5" align="left" >
									 <span class="vehicle_name">Tajmahal, Agra Fort,</span><br>
                                     
	
									
							</div>
                            
      
                            
                            <div class="col-md-31 sightmargin overviueimg3" align="left" >
									 <input name="" type="checkbox" value="">
                                      
	
									
							</div>  
                            
          
	
	
    </div>
    
    </div>
    
    <div class="mapcantiner_inner1" style="padding:0 !important;">
	<div class="" style="margin:0 0 10px; padding:5px 0 10px;">
     
                            
                             <div class="col-md-31 sightmargin overviueimg3" align="left" style="padding:0 !important;">
							
Day 2-
<br>

                			</div>
    
      <div class="col-md-31 sightmargin overviueimg5" align="left" >
									 <span class="vehicle_name">Tajmahal, Agra Fort,</span><br>
                                     
	
									
							</div>
                            
      
                            
                            <div class="col-md-31 sightmargin overviueimg3" align="left" >
									 <input name="" type="checkbox" value="">
                                      
	
									
							</div>  
                            
          
	
	
    </div>
    
    </div>
                              
								<div class="clearfix"> </div>
						  </div>
							</div>  
                                
								<div class="clearfix"> </div>
						  </div>
						  	
							</div>
							
								
					</div>
                    <?php 
					$j++;
					} ?>
                    <div class="choose">
						<div class="choose-info">
							<h5>Choose Your Hotel</h5>
                            
                            <input type="radio" name="mype" value="ve1" onClick="showMe('didfv3', this)" />Yes &nbsp; <input type="radio" name="mype" value="ve1" onClick="showMe1('didfv3', this)" />No
						</div>
						<div class="destinations-grid-info tours" id="didfv3" style="display:none;">
                           <div class="td-grids">
								<div class="tab-pane fade in active" id="tab-1">
                                                
                                                
                                                <div class="form-group form-group-lg form-group-icon-left">
                                                    <i class="fa fa-map-marker input-icon"></i>
                                                    <label>
                                                        Where are you going?</label>
                                                    <input class="form-control tt-input tt-hint  ac_input" name="HDestTo" id="HDestTo" size="31" value="Please Enter Destination" onblur="if(this.value==''){this.value='Please Enter Destination';}" onfocus="if(this.value=='Please Enter Destination'){this.value='';};" onkeypress="if ((event.keyCode > 64 &amp;&amp; event.keyCode < 91 ) || (event.keyCode > 96 &amp;&amp; event.keyCode < 123) || (event.keyCode==32)) event.returnValue = true; else event.returnValue = false" autocomplete="off" type="text">
                                                </div>
                                                <div class="input-daterange" data-date-format="M d, D">
                                                    <div class="row">
                                                        <div class="col-md-3">
                                                            <div class="form-group form-group-lg form-group-icon-left">
                                                                <i class="fa fa-calendar input-icon input-icon-highlight"></i>
                                                                <label>
                                                                    Check-in</label>
                                                                
                                                                <input value="8 October 2015" id="txt_ChekinDate" name="txt_ChekinDate" class="form-control hasDatepicker">
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3">
                                                            <div class="form-group form-group-lg form-group-icon-left">
                                                                <i class="fa fa-calendar input-icon input-icon-highlight"></i>
                                                                <label>
                                                                    Check-out</label>
                                                                
                                                                <input value="11 October 2015" id="txt_ChekOut" name="txt_ChekOut" class="form-control hasDatepicker">
                                                            </div>
                                                        </div>
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <label>
                                                                    Star</label>
                                                                <select class="form-control " id="cboStar" name="cboStar" style="width: 100%; padding-left: 5px;">
                                                                    <option value="All" selected="selected">All</option>
                                                                    <option value="5">5 Star</option>
                                                                    <option value="4">4 Star</option>
                                                                    <option value="3">3 Star</option>
                                                                    <option value="2">2 Star</option>
                                                                    <option value="1">1 Star</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <label>
                                                                    No of Rooms</label>
                                                                <select name="ctl00$cph_main$roomsNo" id="cph_main_roomsNo" class="form-control " style="width: 100%; padding-left: 5px;" onchange="javascript:showRoomsSearchPage();">
	<option value="1">1 Rooms</option>
	<option selected="selected" value="2">2 Rooms</option>
	<option value="3">3 Rooms</option>
	<option value="4">4 Rooms</option>
</select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="input-daterange" data-date-format="M d, D" id="trRoom1">
                                                    <div class="row">
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-icon-left">
                                                                <label style="line-height: 50px; padding-top: 25px;">
                                                                    Rooms 1</label>
                                                                
                                                            </div>
                                                        </div>
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-icon-left">
                                                                <label>
                                                                    ADULTS</label>
                                                                
                                                                <select name="drpAdults1" id="drpAdults1" class="form-control" style="width: 100%;
                                                                    padding-left: 5px;" onchange="javascript:ShowRoomType(1)">
                                                                    <option value="1">1</option>
                                                                    <option value="2" selected="selected">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <label>
                                                                    KIDS</label>
                                                                
                                                                <select name="drpChilds1" id="drpChilds1" style="width: 100%; padding-left: 5px;" class="form-control" onchange="javascript:ChangeChildSearchPage(1)">
                                                                    <option value="0" selected="selected">0</option>
                                                                    <option value="1">1</option>
                                                                    <option value="2">2</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <label>
                                                                    Child(Age 1)</label>
                                                                
                                                                <select id="drpChdAge11" name="drpChdAge11" class="form-control" style="display: none;
                                                                    width: 100%; padding-left: 5px;">
                                                                    <option value="0">0</option>
                                                                    <option value="1" selected="selected">1</option>
                                                                    <option value="2">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                    <option value="5">5</option>
                                                                    <option value="6">6</option>
                                                                    <option value="7">7</option>
                                                                    <option value="8">8</option>
                                                                    <option value="9">9</option>
                                                                    <option value="10">10</option>
                                                                    <option value="11">11</option>
                                                                    <option value="12">12</option>
                                                                    <option value="13">13</option>
                                                                    <option value="14">14</option>
                                                                    <option value="15">15</option>
                                                                    <option value="16">16</option>
                                                                    <option value="17">17</option>
                                                                    <option value="18">18</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <label>
                                                                    Child(Age 1)</label>
                                                                
                                                                <select id="drpChdAge12" name="drpChdAge12" class="form-control" style="display: none;
                                                                    width: 100%; padding-left: 5px;">
                                                                    <option value="0">0</option>
                                                                    <option value="1" selected="selected">1</option>
                                                                    <option value="2">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                    <option value="5">5</option>
                                                                    <option value="6">6</option>
                                                                    <option value="7">7</option>
                                                                    <option value="8">8</option>
                                                                    <option value="9">9</option>
                                                                    <option value="10">10</option>
                                                                    <option value="11">11</option>
                                                                    <option value="12">12</option>
                                                                    <option value="13">13</option>
                                                                    <option value="14">14</option>
                                                                    <option value="15">15</option>
                                                                    <option value="16">16</option>
                                                                    <option value="17">17</option>
                                                                    <option value="18">18</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="input-daterange" id="trRoom2" style="">
                                                    <div class="row">
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-icon-left">
                                                                <label style="line-height: 40px;">
                                                                    Rooms 2</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-icon-left">
                                                                <select name="drpAdults2" id="drpAdults2" style="width: 100%; padding-left: 5px;" class="form-control" onchange="javascript:ShowRoomType(2)">
                                                                    <option value="1" selected="selected">1</option>
                                                                    <option value="2">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <select name="drpChilds2" id="drpChilds2" style="width: 100%; padding-left: 5px;" class="form-control" onchange="javascript:ChangeChildSearchPage(2)">
                                                                    <option value="0" selected="selected">0</option>
                                                                    <option value="1">1</option>
                                                                    <option value="2">2</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <select id="drpChdAge21" name="drpChdAge21" class="form-control" style="display: none;
                                                                    width: 100%; padding-left: 5px;">
                                                                    <option value="0">0</option>
                                                                    <option value="1" selected="selected">1</option>
                                                                    <option value="2">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                    <option value="5">5</option>
                                                                    <option value="6">6</option>
                                                                    <option value="7">7</option>
                                                                    <option value="8">8</option>
                                                                    <option value="9">9</option>
                                                                    <option value="10">10</option>
                                                                    <option value="11">11</option>
                                                                    <option value="12">12</option>
                                                                    <option value="13">13</option>
                                                                    <option value="14">14</option>
                                                                    <option value="15">15</option>
                                                                    <option value="16">16</option>
                                                                    <option value="17">17</option>
                                                                    <option value="18">18</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-32">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <select id="drpChdAge22" name="drpChdAge22" class="form-control" style="display: none;
                                                                    width: 100%; padding-left: 5px;">
                                                                    <option value="0">0</option>
                                                                    <option value="1" selected="selected">1</option>
                                                                    <option value="2">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                    <option value="5">5</option>
                                                                    <option value="6">6</option>
                                                                    <option value="7">7</option>
                                                                    <option value="8">8</option>
                                                                    <option value="9">9</option>
                                                                    <option value="10">10</option>
                                                                    <option value="11">11</option>
                                                                    <option value="12">12</option>
                                                                    <option value="13">13</option>
                                                                    <option value="14">14</option>
                                                                    <option value="15">15</option>
                                                                    <option value="16">16</option>
                                                                    <option value="17">17</option>
                                                                    <option value="18">18</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="input-daterange" data-date-format="M d, D" id="trRoom3" style="display: none">
                                                    <div class="row">
                                                        <div class="col-md-3" style="width: 20%;">
                                                            <div class="form-group form-group-lg form-group-icon-left">
                                                                <label style="line-height: 40px;">
                                                                    Rooms 3</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3" style="width: 20%;">
                                                            <div class="form-group form-group-lg form-group-icon-left">
                                                                <select name="drpAdults3" id="drpAdults3" class="form-control" style="width: 100%;
                                                                    padding-left: 5px;" onchange="javascript:ShowRoomType(3)">
                                                                    <option value="1" selected="selected">1</option>
                                                                    <option value="2">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3" style="width: 20%;">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <select name="drpChilds3" id="drpChilds3" style="width: 100%; padding-left: 5px;" class="form-control" onchange="javascript:ChangeChildSearchPage(3)">
                                                                    <option value="0" selected="selected">0</option>
                                                                    <option value="1">1</option>
                                                                    <option value="2">2</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3" style="width: 20%;">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <select id="drpChdAge31" name="drpChdAge31" class="form-control" style="display: none;
                                                                    width: 100%; padding-left: 5px;">
                                                                    <option value="0">0</option>
                                                                    <option value="1" selected="selected">1</option>
                                                                    <option value="2">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                    <option value="5">5</option>
                                                                    <option value="6">6</option>
                                                                    <option value="7">7</option>
                                                                    <option value="8">8</option>
                                                                    <option value="9">9</option>
                                                                    <option value="10">10</option>
                                                                    <option value="11">11</option>
                                                                    <option value="12">12</option>
                                                                    <option value="13">13</option>
                                                                    <option value="14">14</option>
                                                                    <option value="15">15</option>
                                                                    <option value="16">16</option>
                                                                    <option value="17">17</option>
                                                                    <option value="18">18</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3" style="width: 20%;">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <select id="drpChdAge32" name="drpChdAge32" class="form-control" style="display: none;
                                                                    width: 100%; padding-left: 5px;">
                                                                    <option value="0">0</option>
                                                                    <option value="1" selected="selected">1</option>
                                                                    <option value="2">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                    <option value="5">5</option>
                                                                    <option value="6">6</option>
                                                                    <option value="7">7</option>
                                                                    <option value="8">8</option>
                                                                    <option value="9">9</option>
                                                                    <option value="10">10</option>
                                                                    <option value="11">11</option>
                                                                    <option value="12">12</option>
                                                                    <option value="13">13</option>
                                                                    <option value="14">14</option>
                                                                    <option value="15">15</option>
                                                                    <option value="16">16</option>
                                                                    <option value="17">17</option>
                                                                    <option value="18">18</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="input-daterange" data-date-format="M d, D" id="trRoom4" style="display: none">
                                                    <div class="row">
                                                        <div class="col-md-3" style="width: 20%;">
                                                            <div class="form-group form-group-lg form-group-icon-left">
                                                                <label style="line-height: 40px;">
                                                                    Rooms 4</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3" style="width: 20%;">
                                                            <div class="form-group form-group-lg form-group-icon-left">
                                                                <select name="drpAdults4" id="drpAdults4" class="form-control" style="width: 100%;
                                                                    padding-left: 5px;" onchange="javascript:ShowRoomType(4)">
                                                                    <option value="1" selected="selected">1</option>
                                                                    <option value="2">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3" style="width: 20%;">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <select name="drpChilds4" id="drpChilds4" style="width: 100%; padding-left: 5px;" class="form-control" onchange="javascript:ChangeChildSearchPage(4)">
                                                                    <option value="0" selected="selected">0</option>
                                                                    <option value="1">1</option>
                                                                    <option value="2">2</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3" style="width: 20%;">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <select id="drpChdAge41" name="drpChdAge41" class="form-control" style="display: none;
                                                                    width: 100%; padding-left: 5px;">
                                                                    <option value="0">0</option>
                                                                    <option value="1" selected="selected">1</option>
                                                                    <option value="2">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                    <option value="5">5</option>
                                                                    <option value="6">6</option>
                                                                    <option value="7">7</option>
                                                                    <option value="8">8</option>
                                                                    <option value="9">9</option>
                                                                    <option value="10">10</option>
                                                                    <option value="11">11</option>
                                                                    <option value="12">12</option>
                                                                    <option value="13">13</option>
                                                                    <option value="14">14</option>
                                                                    <option value="15">15</option>
                                                                    <option value="16">16</option>
                                                                    <option value="17">17</option>
                                                                    <option value="18">18</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3" style="width: 20%;">
                                                            <div class="form-group form-group-lg form-group-select-plus">
                                                                <select id="drpChdAge42" name="drpChdAge42" class="form-control" style="display: none;
                                                                    width: 100%; padding-left: 5px;">
                                                                    <option value="0">0</option>
                                                                    <option value="1" selected="selected">1</option>
                                                                    <option value="2">2</option>
                                                                    <option value="3">3</option>
                                                                    <option value="4">4</option>
                                                                    <option value="5">5</option>
                                                                    <option value="6">6</option>
                                                                    <option value="7">7</option>
                                                                    <option value="8">8</option>
                                                                    <option value="9">9</option>
                                                                    <option value="10">10</option>
                                                                    <option value="11">11</option>
                                                                    <option value="12">12</option>
                                                                    <option value="13">13</option>
                                                                    <option value="14">14</option>
                                                                    <option value="15">15</option>
                                                                    <option value="16">16</option>
                                                                    <option value="17">17</option>
                                                                    <option value="18">18</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <input name="ctl00$cph_main$IbSearch" value="Search for Hotels" onclick="return gotoResult('frmHotelSearch');" id="cph_main_IbSearch" class="btn btn-primary btn-lg" type="submit">
                                                
                                                
                                            </div>
                      
                            
                            
								<div class="col-xs-2 td-right">
									
								</div>
								<div class="clearfix"> </div>
						  </div>
							</div>
					</div>
                    
                    <div class="choose">
						<div class="choose-info">
							<h5>Choose Attrections/Pay Entrance or Ticket</h5>
                            
                            <input type="radio" name="mype" value="ve1" onClick="showMe('didfv4', this)" />Yes &nbsp; <input type="radio" name="mype" value="ve1" onClick="showMe1('didfv4', this)" />No
						</div>
						<div class="destinations-grid-info tours" id="didfv4" style="display:none;">
                           <div class="td-grids">
								<div id="addonsBlock">
			<form action="/updateAddons" id="update_addons" method="post">
<h5>Addons</h5> 


<p><input name="order[yamuna]" type="hidden" value="600" /><input id="order_yamuna" name="order[yamuna]" type="checkbox" value="1" />	<span class="txtdgrey mL10">Travel via Yamuna Expressway :</span> <span class="txtblue txtbold">Rs. 600</span></p>


<br>
<h5>Entrance Tickets, Activities, Cultural Shows & Theatre</h5><br>
<table>

		<form action="/addOrUpdateReservation?update=" method="post" onsubmit="jQuery.ajax({beforeSend:function(request){$('#wrapper').ajaxloader('show','tata-ajax-loader-img2');}, complete:function(request){$('#wrapper').ajaxloader('hide')}, data:jQuery.param(jQuery(this).serializeArray()), dataType:'script', type:'post', url:'/addOrUpdateReservation?update='}); return false;" >
			
			<?php
                foreach($ShowsDetails as $SD)
				 {
				   //echo $SD['s_id']; 
				   //echo $SD['name']; 
				   //echo $SD['fare'];    
			?>
			<tr style="margin-bottom:5px; padding-bottom:10px;">
			<td width="30%">
			<a href="#" class="tooltipF"><p class="txtdgrey mL10"><?php echo $SD['name']; ?></i></p>
				<span>
					<table><tr><td width=""><img alt="2976" class="imgborder2" height="60" src="http://www.ziptrips.in/photos/2976.png" width="80" style="width:80px;" /></td>
                    <td>
					<strong>Details: </strong>Organized to promote Indian culture as well as the history of Agra, that houses one of the seven wonders of the world - Taj Mahal, the 80-minute light and sound show is a major success, nearly 70 artists from different part of the country participates in this show, a must watch in Agra</br></br>
					<strong>Includes: </strong>Light And Sound Show @ Agra Fort</br></br>
					
					</td></tr></table>
</span></a>		
			</td>
			
			<?php 
			
			
             
			?>
            <td width="60%">
			<table cellpadding="10" cellspacing="10" width="100%">
				
				
					<tr>
						<td width="70%">Time: 6:30 PM, Language: English, Nationality: Indian</td><td width="20%">Rs. 100 </td>
						<td width="10%">
							
							 		
							<select id="reservation_1" name="reservation[adults]"><option value="0" selected="selected">0</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option></select>
							<script type="text/javascript">
//<![CDATA[
jQuery('#reservation_1').delayedObserver(0.25, function(element, value) {jQuery.ajax({beforeSend:function(request){$('#wrapper').ajaxloader('show','tata-ajax-loader-img2');}, complete:function(request){$('#wrapper').ajaxloader('hide')}, data:'adults=' + value, dataType:'script', type:'post', url:'/addOrUpdateReservationD?offer_id=1&order_id=696342&update='})})
//]]>
</script> 
						</td>
					</tr>
				
					<tr>
						<td width="70%">Time: 6:30 PM, Language: English, Nationality: Non-Indian</td><td width="20%">Rs. 300 </td>
						<td width="10%">
							
							 
							
							<select id="reservation_2" name="reservation[adults]"><option value="0" selected="selected">0</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option></select>
							<script type="text/javascript">
//<![CDATA[
jQuery('#reservation_2').delayedObserver(0.25, function(element, value) {jQuery.ajax({beforeSend:function(request){$('#wrapper').ajaxloader('show','tata-ajax-loader-img2');}, complete:function(request){$('#wrapper').ajaxloader('hide')}, data:'adults=' + value, dataType:'script', type:'post', url:'/addOrUpdateReservationD?offer_id=2&order_id=696342&update='})})
//]]>
</script> 
						</td>
					</tr>
				
					<tr>
						<td width="70%">Time: 7:30 PM, Language: Hindi, Nationality: Indian</td><td width="20%">Rs. 100 </td>
						<td width="10%">
							
							 
							
							<select id="reservation_3" name="reservation[adults]"><option value="0" selected="selected">0</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option></select>
							<script type="text/javascript">
//<![CDATA[
jQuery('#reservation_3').delayedObserver(0.25, function(element, value) {jQuery.ajax({beforeSend:function(request){$('#wrapper').ajaxloader('show','tata-ajax-loader-img2');}, complete:function(request){$('#wrapper').ajaxloader('hide')}, data:'adults=' + value, dataType:'script', type:'post', url:'/addOrUpdateReservationD?offer_id=3&order_id=696342&update='})})
//]]>
</script> 
						</td>
					</tr>
				
					<tr>
						<td width="70%">Time: 7:30 PM, Language: Hindi, Nationality: Non-Indian</td><td width="20%">Rs. 300 </td>
						<td width="10%">
							
							 
							
							<select id="reservation_4" name="reservation[adults]"><option value="0" selected="selected">0</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option></select>
							<script type="text/javascript">
//<![CDATA[
jQuery('#reservation_4').delayedObserver(0.25, function(element, value) {jQuery.ajax({beforeSend:function(request){$('#wrapper').ajaxloader('show','tata-ajax-loader-img2');}, complete:function(request){$('#wrapper').ajaxloader('hide')}, data:'adults=' + value, dataType:'script', type:'post', url:'/addOrUpdateReservationD?offer_id=4&order_id=696342&update='})})
//]]>
</script> 
						</td>
					</tr>
				
			</table>
			</td>
            <td width="10%">
			<span class="txtblue txtbold">Rs. 0 </span>
			</td>
			</tr>
			<?php } ?>
		</form>
	

	
		
	
		
	

	
		
	
</table>
</form>
<script type="text/javascript">
//<![CDATA[
jQuery('#update_addons').delayedObserver(0.25, function(element, value) {jQuery.ajax({beforeSend:function(request){$('#wrapper').ajaxloader('show','tata-ajax-loader-img2');}, complete:function(request){$('#wrapper').ajaxloader('hide')}, data:value, dataType:'script', type:'post', url:'/updateAddons?order_id=696342'})})
//]]>
</script>

</div>
                      
                            
                            
								<div class="col-xs-2 td-right">
									
								</div>
								<div class="clearfix"> </div>
						  </div>
							</div>
					</div>
                    
				</div>
				<div class="col-md-4 banner-bottom-grid" style="float:right; height:;">
                
                <div class="top-destinations-grids" style="margin-top:0;">
						
						<div class="top-destinations-bottom">
							<div class="td-grids">
                            
                            
                            <div class="summary">
                            <div class="col-md-31 sightmargin overviueimg5" align="left" style="width:100%; padding-left:0;">
									<select class="input-sm hidden-xs currency_selection ng-pristine ng-valid form-control" ng-change="currencyChanged(selectedCurrency)" ng-options="currency.name for currency in availableCurrencies" ng-model="selectedCurrency" name="currency_selection">
<option value="0">US Dollar (USD)</option>
<option value="1">Indian Rupee (INR)</option>
<option value="2">Algerian Dinar (DZD)</option>
<option value="3">Argentine Peso (ARS)</option>
<option value="4">Australian Dollar (AUD)</option>
<option value="5">Bahraini Dinar (BHD)</option>
<option value="6">Bangladeshi Taka (BDT)</option>
<option value="7">Bolivian Boliviano (BOB)</option>
<option value="8">Botswanan Pula (BWP)</option>
<option value="9">Brazilian Real (BRL)</option>
<option value="10">British Pound Sterling (GBP)</option>
<option value="11">Brunei Dollar (BND)</option>
<option value="12">Bulgarian Lev (BGN)</option>
<option value="13">Cayman Islands Dollar (KYD)</option>
<option value="14">Chinese Yuan Renminbi (CNY)</option>
<option value="15">Colombian Peso (COP)</option>
<option value="16">Costa Rican Colon (CRC)</option>
<option value="17">Croatian Kuna (HRK)</option>
<option value="18">Danish Krone (DKK)</option>
<option value="19">Dominican Peso (DOP)</option>
<option value="20">Egyptian Pound (EGP)</option>
<option value="21">Estonian Kroon (EEK)</option>
<option value="22">Euro (EUR)</option>
<option value="23">Fijian Dollar (FJD)</option>
<option value="24">Honduran Lempira (HNL)</option>
<option value="25">Hong Kong Dollar (HKD)</option>
<option value="26">Hungarian Forint (HUF)</option>
<option value="27">Indonesian Rupiah (IDR)</option>
<option value="28">Israeli New Sheqel (ILS)</option>
<option value="29">Jamaican Dollar (JMD)</option>
<option value="30">Japanese Yen (JPY)</option>
<option value="31">Jordanian Dinar (JOD)</option>
<option value="32">Kazakhstan Tenge (KZT)</option>
<option value="33">Kuwaiti Dinar (KWD)</option>
<option value="34">Macedonian Denar (MKD)</option>
<option value="35">Malaysian Ringgit (MYR)</option>
<option value="36">Maldivian Rufiyaa (MVR)</option>
<option value="37">Mauritian Rupee (MUR)</option>
<option value="38">Mexican Peso (MXN)</option>
<option value="39">Moldovan Leu (MDL)</option>
<option value="40">Moroccan Dirham (MAD)</option>
<option value="41">Nepalese Rupee (NPR)</option>
<option value="42">Netherlands Antillean Guilder (ANG)</option>
<option value="43">New Taiwan Dollar (TWD)</option>
<option value="44">New Zealand Dollar (NZD)</option>
<option value="45">Omani Rial (OMR)</option>
<option value="46">Pakistani Rupee (PKR)</option>
<option value="47">Papua New Guinean Kina (PGK)</option>
<option value="48">Paraguayan Guarani (PYG)</option>
<option value="49">Philippine Peso (PHP)</option>
<option value="50">Polish Zloty (PLN)</option>
<option value="51">Qatari Rial (QAR)</option>
<option value="52">Romanian Leu (RON)</option>
<option value="53">Russian Ruble (RUB)</option>
<option value="54">Salvadoran Colon (SVC)</option>
<option value="55">Saudi Riyal (SAR)</option>
<option value="56">Serbian Dinar (RSD)</option>
<option value="57">Seychellois Rupee (SCR)</option>
<option value="58">Sierra Leonean Leone (SLL)</option>
<option value="59">Singapore Dollar (SGD)</option>
<option value="60">Slovak Koruna (SKK)</option>
<option value="61">South African Rand (ZAR)</option>
<option value="62">South Korean Won (KRW)</option>
<option value="63">Sri Lanka Rupee (LKR)</option>
<option value="64">Swiss Franc (CHF)</option>
<option value="65">Tanzanian Shilling (TZS)</option>
<option value="66">Thai Baht (THB)</option>
<option value="67">Trinidad and Tobago Dollar (TTD)</option>
<option value="68">Tunisian Dinar (TND)</option>
<option value="69">Turkish Lira (TRY)</option>
<option value="70">Ugandan Shilling (UGX)</option>
<option value="71">Ukrainian Hryvnia (UAH)</option>
<option value="72">United Arab Emirates Dirham (AED)</option>
<option value="73">Uzbekistan Som (UZS)</option>
<option value="74">Venezuelan Bolìvar Fuerte (VEF)</option>
<option value="75">Vietnamese Dong (VND)</option>
<option value="76">Yemeni Rial (YER)</option>
<option value="77">Zambian Kwacha (ZMK)</option>
</select>
							</div><br>
                            
                            <div class="top-destinations-info">
							<h4>Booking Amount</h4>
						</div>
                            <div class="inner">
								<div class="infopay">
	<div class="title">Booking Amount</div>
			<div class="price">
		  		 
		  <span class=""><span class="WebRupee"> Rs. </span></span><span class="paybooking"><?php echo $_SESSION['cab_charge'] ?></span>
		</div>
		
		<div class="title">Addon Amount</div>
	<div class="price"><span class="WebRupee"><span class="WebRupee"> Rs. </span></span><span class="payaddon">0</span></div>

	<div class="title">Total Amount</div>
	<div class="price"><span class="WebRupee"><span class="WebRupee"> Rs. </span></span><span class="payamount"><?php echo $_SESSION['cab_charge'] ?> </span></div>
		
		<div class="clear"></div>

		<div class="title" style="color:#C22815; font-weight:bold" title="Only for booking amount">Discount(10%)</div>
		<div class="price" style="color:#C22815; font-weight:bold" title="Only for booking amount"><span class="WebRupee"> Rs. </span><span class="discount"><?php echo $chrge = intval($_SESSION['cab_charge']*10/100)?></span> </div>

		<div class="title">Net Amount</div>
		<div class="price"><span class="WebRupee"> Rs. </span><span class="netamnt"><?php echo $_SESSION['cab_charge']- $chrge; ?></span> </div>

		<div class="title">Service Tax(<span id="st_text">4.94</span>%)</div>
		<div class="price"><span class="WebRupee"> Rs. </span><span class="payservice"><?php echo $tax = intval($_SESSION['cab_charge']*4.94/100) ?></span> </div>
		
		<div class="clear"></div>
		<div class="title">Payable Amount</div>
		<div class="price"><span class="WebRupee"> Rs. </span><span class="paytotal"><?php echo $tax+($_SESSION['cab_charge']- $chrge); ?></span><span id="usdvalue"></span> </div>
        
        <div class="clear"></div>
		<div class="title">
        <form action="bookingcheckout.html">
        
         <input type="button" class="btn btn-lg bg-primary col-sm-12 makebookingbtn outstationBooking"  title="Submit" value="Book Now">
         </form>
         </div>
         
         <div class="clear"></div>
        <div class="title" style="width:100%; margin-bottom:5px;">
         <label class="radio-inline specs" style="padding-left:0 !important;">
        <div class="radioWrap" style="float:left;">
          <input type="text" name="coupan_code" placeholder="Coupan Code" style="height:34px;" id="coupan_code" onclick="" class="radiobtnalign" >
          <span></span></div>
		  <label id="apply_coupancode" style="float:left; margin-left:10px;"><a href="#" style="display:inline; line-height:35px;" > Apply Coupan </a></label>
		  <div id="coupan_msg"></div>
		  <div id="coupan_disount"></div>
        <small id="booklater_conditions_local"></small>
        </label>
        </div>
		
		


	<script>
		document.getElementById('payamnt').value="19600";
		document.getElementById('paytotal').value="18512";
	</script>
</div>
</div>
</div>
								<div class="clearfix"> </div>
							</div>
							
						</div>
					</div>
					<div class="destinations" style=" display:;">
						<div class="top-destinations-bottom">
							<div class="td-grids">
                            <div class="info"><b>Car Type</b> :<?php  $cartype = $_SESSION['cartype'];
								     if($cartype ==1)
									 {
										 echo "Economy";
									 }
									 elseif($cartype == 2)
									 {
										 echo "Sedan";
									 }
									 else
									 {
										echo "Prime"; 
									 }

								  ?>, <?php echo $_SESSION['cabname']; ?></div>
<div class="info"><b>Service</b> : Outstation</div>


<div class="info"><b>From</b> : <?php echo $_SESSION['outRoundtripfrom']; ?></div>

<div class="info"><b>Destination</b> : <?php echo $_SESSION['outRoundtripto']; ?></div>
<div class="info"><b>Round Trip</b> : Yes</div>

<div class="info"><b>Pickup Address</b> : <?php echo $_SESSION['outPickupAddress'];  ?></div>

<div class="info"><b>Departure Date</b> : <?php echo $_SESSION['outstation_Ddate']; ?></div>
<div class="info"><b>Return Date</b> : <?php echo $_SESSION['outstation_Rdate']; ?></div><div class="info"><b>Pickup Time</b> : 12:05</div>



<div class="info">
	<b>Fare Details:</b>
	<ul>
				<li>Minimum charged distance is 2000 Km</li>
		<li>Fare calculated :
		2000 Km x<span class="WebRupee"> Rs. </span>9 +<span class="WebRupee"> Rs. </span>1600(Driver allowance)		
		</li>
		<li>Per day extra charge :<span class="WebRupee"> Rs. </span>250</li>
		<li>Per km extra charge :<span class="WebRupee"> Rs. </span>9</li>
		<li>Per day driver allowance :<span class="WebRupee"> Rs. </span>200</li>
				<li>If the vehicle will come after 2400 Hrs than One Extra day charge will be applicable with Driver Allowance</li>

				<li>Tolls and parking charge extra</li>
	</ul>
</div>
<div class="info">Final Fare shall depend upon actual Kms Travelled + Service Tax extra </div>
								<div class="clearfix"> </div>
							</div>
							
						</div>
					</div>
                    
                    
                    <div class="top-destinations-grids" style="margin-top:20px;">
						
						<div class="top-destinations-bottom">
							<div class="td-grids">
                            <div class="summary">
                            <div class="top-destinations-info">
							<h4>Fair Detail</h4>
						</div>
                            <div class="inner">
								<div class="infopay">
	<div class="title">Sight Sightseeings</div>
			<div class="price">
		  		  <input name="exact_km" value="" id="exact_km" type="hidden">
		  		  <input name="actual_km" value="2000" id="actual_km" type="hidden">
		  <span class=""><span class="WebRupee"> Rs. </span></span><span class="paybooking">19600</span>
		</div>
		
		<div class="title">Driver Charge</div>
	<div class="price"><span class="WebRupee"><span class="WebRupee"> Rs. </span></span><span class="payaddon">500</span></div>

	<div class="title">Guide Charge</div>
	<div class="price"><span class="WebRupee"><span class="WebRupee"> Rs. </span></span><span class="payamount">1000 </span></div>
		
		<div class="clear"></div>

		<div class="title">Hotel Charge</div>
		<div class="price"><span class="WebRupee"> Rs. </span><span class="netamnt">1240</span> </div>

		<div class="title">Entrance Charge</div>
		<div class="price"><span class="WebRupee"> Rs. </span><span class="payservice">872</span> </div>
		
		<div class="clear"></div>
        
        <div class="title">Service Tax(<span id="st_text">4.94</span>%)</div>
		<div class="price"><span class="WebRupee"> Rs. </span><span class="payservice">872</span> </div>
		
        <div class="title" style="color:#C22815; font-weight:bold" title="Only for booking amount">Discount(10%)</div>
		<div class="price" style="color:#C22815; font-weight:bold" title="Only for booking amount"><span class="WebRupee"> Rs. </span><span class="discount">1960</span> </div>
        
        
		<div class="clear"></div>
		<div class="title">Payable Amount</div>
		<div class="price"><span class="WebRupee"> Rs. </span><span class="paytotal">18512</span><span id="usdvalue"></span> </div>
        
	
</div>
</div>
</div>
								<div class="clearfix"> </div>
							</div>
							
						</div>
					</div>
                    
                    <div class="top-destinations-grids">
						<div class="top-destinations-info">
							<h4></h4>
						</div>
						<div class="top-destinations-bottom">
							<section class="slider2">
					<div class="flexslider">
						<ul class="slides">
							<li>
								<div class="slider-info">
									<img src="<?php echo $path; ?>/public/images/1.jpg" alt="">
								</div>
							</li>
                            <li>
								<div class="slider-info">
									<img src="<?php echo $path; ?>/public/images/2.jpg" alt="">
								</div>
							</li>
                            <li>
								<div class="slider-info">
									<img src="<?php echo $path; ?>/public/images/3.jpg" alt="">
								</div>
							</li>
							
						</ul>
					</div>
				</section>
						</div>
					</div>
                    
                    
                    <div class="top-destinations-grids">
						<div class="top-destinations-info">
							<h4>Trip Details</h4>
                            Agra first, then Jaipur (stay overnight in Jaipur)
						</div>
						<div class="destinations" id="dragdiv">
                        
						 <ul id="allItems" runat="server">
							<li class="button" id="node1"><a href="#">Day 1</a>
								<li class="dropdown active">
									
									<div class="destinations-grid-info">
									  <div class="destinations-hotel">06:00 AM     Start from Delhi</div>
                                      <div class="destinations-hotel">11:00 AM Arrive in Agra, visit Taj Mahal</div>
                                      <div class="destinations-hotel">01:00 PM Lunch</div>
                                       <div class="destinations-hotel">03:00 PM     Visit Agra Fort</div>
                                      <div class="destinations-hotel">06:00 PM     Depart for Jaipur</div>
                                      <div class="destinations-hotel">11:00 PM     Arrive in Jaipur &amp; Check into hotel</div>
                                      <div class="clearfix"> </div>
								  </div>
									
								 </li>
							</li>
							<li class="button" id="node2"><a href="#">Day 2</a>
								<li class="dropdown">
									
										
										<div class="destinations-grid-info">
									  <div class="destinations-hotel">06:00 AM     Start from Delhi</div>
                                      <div class="destinations-hotel">11:00 AM Arrive in Agra, visit Taj Mahal</div>
                                      <div class="destinations-hotel">01:00 PM Lunch</div>
                                       <div class="destinations-hotel">03:00 PM     Visit Agra Fort</div>
                                      <div class="destinations-hotel">06:00 PM     Depart for Jaipur</div>
                                      <div class="destinations-hotel">11:00 PM     Arrive in Jaipur &amp; Check into hotel</div>
									  <div class="clearfix"> </div>
										</div>
									
								 </li>
							</li>							
							<li class="button" id="node3"><a href="#">Day 3</a>
								 <li class="dropdown">
									
										
										<div class="destinations-grid-info">
									  <div class="destinations-hotel">06:00 AM     Start from Delhi</div>
                                      <div class="destinations-hotel">11:00 AM Arrive in Agra, visit Taj Mahal</div>
                                      <div class="destinations-hotel">01:00 PM Lunch</div>
                                       <div class="destinations-hotel">03:00 PM     Visit Agra Fort</div>
                                      <div class="destinations-hotel">06:00 PM     Depart for Jaipur</div>
                                      <div class="destinations-hotel">11:00 PM     Arrive in Jaipur &amp; Check into hotel</div>
                                      
									  
									  <div class="clearfix"> </div>
										</div>
									
								 </li>
							</li>
                            
                            <div class="btn btn-lg bg-primary col-sm-12 makebookingbtn outstationBooking" style="margin-top:5px;" align="center"><a href="#" style="color:#fff; font-size:16px;">Customise Trip</a>
								 
							</div>
														 
						 </ul>
					</div>
                    
                  
                    
            
            
                   
					</div>
					
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
        
        
        </div>
        
        
        
        </div>
		<!-- //container -->
	</div>
	<!-- //banner-bottom -->
	<!-- popular-grids -->
	
    
    
    <div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Sightseeings Name</h4>
      </div>
      <div class="modal-body">
       <div class="">
 
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">About</a></li>
    <li><a data-toggle="tab" href="#menu1">Menu 1</a></li>
    <li><a data-toggle="tab" href="#menu2">Menu 2</a></li>
    <li><a data-toggle="tab" href="#menu3">Menu 3</a></li>
  </ul>

  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <h3>HOME</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div id="menu1" class="tab-pane fade">
      <h3>Menu 1</h3>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
    <div id="menu2" class="tab-pane fade">
      <h3>Menu 2</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
    </div>
    <div id="menu3" class="tab-pane fade">
      <h3>Menu 3</h3>
      <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
    </div>
  </div>
</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
    
    
	<!-- popular-grids -->
	<!-- footer -->

	<script type="text/javascript" src="js/script.js"></script>
		
	<script type="text/javascript">
		$(function(){
			SyntaxHighlighter.all();
			});
			$(window).load(function(){
			$('.flexslider').flexslider({
			animation: "slide",
			start: function(slider){
			$('body').removeClass('loading');
			}
			});
		});
	</script>
    
    
    <style>


 .sightcont ul{list-style: none; padding:10px 0; margin:0;}
 
 .sightinc ul li{list-style: none; padding:10px 0; margin:0 5px 5px 0;}
 
  .sightcont ul li{list-style: none; padding:10px 0; margin:0 5px 5px 0;}
 
.sremove, .sadd{text-align: center; font-size: 12px; cursor: pointer; margin-top: 5px;
 border:1px solid #25729a; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px; padding: 3px 5px; text-decoration:none; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; color: #FFFFFF;
 background-color: #3093c7; background-image: -webkit-gradient(linear, left top, left bottom, from(#3093c7), to(#1c5a85));
 background-image: -webkit-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -moz-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -ms-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -o-linear-gradient(top, #3093c7, #1c5a85);
 background-image: linear-gradient(to bottom, #3093c7, #1c5a85);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#3093c7, endColorstr=#1c5a85);
 width:80px;
}

.sremove:hover, .sadd:hover{
 border:1px solid #1c5675;
 background-color: #26759e; background-image: -webkit-gradient(linear, left top, left bottom, from(#26759e), to(#133d5b));
 background-image: -webkit-linear-gradient(top, #26759e, #133d5b);
 background-image: -moz-linear-gradient(top, #26759e, #133d5b);
 background-image: -ms-linear-gradient(top, #26759e, #133d5b);
 background-image: -o-linear-gradient(top, #26759e, #133d5b);
 background-image: linear-gradient(to bottom, #26759e, #133d5b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#26759e, endColorstr=#133d5b);
}

.pright{border:1px solid #ccc; padding:5px 5px 20px; width:220px; float:right; box-shadow: 0px 0px 2px #ccc}
.pright .btns{text-align: center;}
.pright .btns p{font-weight: bold; margin:0 0 13px 0;}

.btnsubmit{text-align: center; font-size: 16px; cursor: pointer; margin:10px 0;
 border:1px solid #25729a; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px; padding: 10px 30px; text-decoration:none; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; color: #FFFFFF;
 background-color: #3093c7; background-image: -webkit-gradient(linear, left top, left bottom, from(#3093c7), to(#1c5a85));
 background-image: -webkit-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -moz-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -ms-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -o-linear-gradient(top, #3093c7, #1c5a85);
 background-image: linear-gradient(to bottom, #3093c7, #1c5a85);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#3093c7, endColorstr=#1c5a85);
}

.btnsubmit:hover{
 border:1px solid #1c5675;
 background-color: #26759e; background-image: -webkit-gradient(linear, left top, left bottom, from(#26759e), to(#133d5b));
 background-image: -webkit-linear-gradient(top, #26759e, #133d5b);
 background-image: -moz-linear-gradient(top, #26759e, #133d5b);
 background-image: -ms-linear-gradient(top, #26759e, #133d5b);
 background-image: -o-linear-gradient(top, #26759e, #133d5b);
 background-image: linear-gradient(to bottom, #26759e, #133d5b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#26759e, endColorstr=#133d5b);
}

.btncustom{text-align: center; font-size: 16px; cursor: pointer; margin:10px 0;
 border:1px solid #ff2596; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px; padding: 5px 18px; text-decoration:none; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; color: #FFFFFF !important;
 background-color: #ff5db1; background-image: -webkit-gradient(linear, left top, left bottom, from(#ff5db1), to(#ef007c));
 background-image: -webkit-linear-gradient(top, #ff5db1, #ef007c);
 background-image: -moz-linear-gradient(top, #ff5db1, #ef007c);
 background-image: -ms-linear-gradient(top, #ff5db1, #ef007c);
 background-image: -o-linear-gradient(top, #ff5db1, #ef007c);
 background-image: linear-gradient(to bottom, #ff5db1, #ef007c);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#ff5db1, endColorstr=#ef007c);
}

.btncustom:hover{
 border:1px solid #f60080;
 background-color: #ff2a98; background-image: -webkit-gradient(linear, left top, left bottom, from(#ff2a98), to(#bc0062));
 background-image: -webkit-linear-gradient(top, #ff2a98, #bc0062);
 background-image: -moz-linear-gradient(top, #ff2a98, #bc0062);
 background-image: -ms-linear-gradient(top, #ff2a98, #bc0062);
 background-image: -o-linear-gradient(top, #ff2a98, #bc0062);
 background-image: linear-gradient(to bottom, #ff2a98, #bc0062);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#ff2a98, endColorstr=#bc0062);
}


.fromcity{width:160px; margin-left:5px; padding:1px 0; border:1px solid #aaa;}

.fields .label{text-align: left; margin:15px 0 5px 10px; font-weight:bold; color: #333}
.fields .label:first-child{margin-top: 0 !important}
.fields h4{background:#E76B3F; color: #fff; padding: 4px 0; }
</style>
    	
 
     <script defer src="<?php echo $path; ?>/public/js/jquery.flexslider.js"></script>
  
	<script type="text/javascript">
		$(function(){
			SyntaxHighlighter.all();
			});
			$(window).load(function(){
			$('.flexslider').flexslider({
			animation: "slide",
			start: function(slider){
			$('body').removeClass('loading');
			}
			});
		});
	</script>    
            
        	
</body>

</html>