<div class="signinbg">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 pull-left">
						<h3 style="display:none;">Email Or Number</h3>
                        <strong style="display:block; width:130px; color:white; font-size:14px;">Forgot Password</strong>
                        <h3 style="display:none;">Segment</h3>

                      </div>
					<div class="col-lg-5 col-lg-offset-1" id="crum" style="display:none;">
					  <ul class=" badcarmlist">
                     	<li class="active"><a class="active" href="">Email</a></li>
                        <li class='segment_crum'><a class="segment_crum" href="">Segment</a></li>
                      	 <li><a href="">Verification</a></li>
                   
                       	 <li style="background:none;"><a href="
                         ">Done</a></li>
                     </ul>
					</div>
 				</div>
			</div>
		</div>
<div class="container">
 
<form id="login_form4" novalidate="novalidate">
        <!--Login START-->
		<div class="container leftbox" id="login_start" style="display:block;margin-top:35px;">
				<div class="row text-center">
					<div class="col-md-12">
						<div class="exit_iconbox">
							<a href="#">
                               <!-- <div class="circle-tile-heading red">
                                     <i class="fa fa-sign-in fa-fw fa-5x"></i>
                                </div>-->
								<div class="circle-tile-heading red">
                                     <i class="fa fa-sign-in fa-fw fa-1_5x sicon" style="cursor:pointer;"></i>
                                </div>
                            </a>
                            

						</div>
					</div><div class="clearfix"></div>
				</div>
 			<div class="row text-center">
             <div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1">
             </div>
				<div class="leftbox col-md-6 col-lg-5 col-md-offset-3 col-lg-offset-3">
 					<div class="col-lg-12">
                    
							<div class="spance">
                            <p class="invalid" style="display:none;color:red">Invalid Username or Password</p>
							<strong style="font-size:14px;color:grey;">Enter your email to Reset Password</strong><br/><br/>
							<input style="width: 250px;margin: 0 0 0 164px; font-size:14px;" type="text" id="email" name="login_email" placeholder="Type your email here" class="form-control login form-horizontal border">
							</div>
                           
                            <div class="spance">
                            	<!--<div class="col-sm-12 col-md-12 col-lg-12 loginboxpading">
                                    <button type="button" id="forget"  class="form-control form-horizontal loginbtn textsize17">Submit<i class="fa fa-spinner fa-spin" style="font-size:1.5em;float:right; display: none;"></i></button>
                            	</div>-->
								<div class="col-sm-2 col-md-2 col-lg-2 loginboxpading" style="margin-left: 236px;margin-bottom: 50px;margin-top:9px;">
                                    <input type="button" id="forget" value="Submit" class="form-control form-horizontal loginbtn" style="font-size:14px;padding-top: 3px;margin-left:8px;">
									<!--<i class="fa fa-spinner fa-spin" style="font-size:1.5em;float:right; display: none;"></i>-->
									
                            	</div>
                               
							</div>
                              
                            
                            
  						</div>
				</div>
			</div>
		</div>
        <!--Login END--> 
        </form>
        <div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Confirmation</h4>
            </div>
            <div class="modal-body">
                <p>An Confirmation Email has been sent on your account</p>
                <p class="text-warning"><small></small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default closeButton" data-dismiss="modal">Close</button>
                
            </div>
        </div>
    </div>
 
</div>
</div>

