<div class="signinbg">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 pull-left">
						<h3 style="display:none;">Email Or Number</h3>
                        <strong style="display:block; width:130px; color:white; font-size:14px;">Reset Password</strong>
                        <h3 style="display:none;">Segment</h3>

                      </div>
				
 				</div>
			</div>
		</div>
		
		
		
		<!--footer-->
		<div class="container">
<form id="reset_form">
         <!--EMAIL ID START-->
		<div class="container" id="email_id" style="margin-top:30px;">
				<div class="row text-center">
					<div class="col-md-12">
						<div class="exit_iconbox">
							<a href="#">
                               <!--<div class="circle-tile-heading red">
                                    <i class="fa fa-envelope fa-fw fa-4x" style="position: absolute;margin:2px 0 0 -48px;transform: rotate(-21deg) !important;text-shadow: -1px 1px 1px #ccc!important;"></i>
                                    <i class="fa fa-mobile fa-fw fa-7x" style="position: absolute;margin: 0 0 0 -49px;text-shadow: 1px 1px 0px #999;"></i>
                                </div>-->
								<div class="circle-tile-heading red">
                                     <i class="fa fa-sign-in fa-fw fa-1_5x sicon" style="cursor:pointer;"></i>
                                </div>
                            </a>
                            

						</div>
					</div><div class="clearfix"></div>
				</div>
 			<div class="row text-center">
             <div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1">
             	<!--<h2 class="darkcolor spance20">Reset Password</h2>-->
				<strong style="font-size:14px;color:grey;">Reset Password</strong><br/><br/>
             </div>
				<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1">
 					<div class="col-lg-6">
                    
							<div class="spance">
                                                            
							<input style="width: 250px;margin: 0 0 0 363px; font-size:14px;"  id="firstpass" name="firstpass" type="password" placeholder="Enter Password" class="signup form-control form-horizontal border "/>
							<p style="display:none;color:red" class="valid_error email_error"></p>
							</div>
							<div class="spance">
							<input style="width: 250px;margin: 0 0 0 363px; font-size:14px;"  id="secondpass" name="secondpass" type="password" placeholder="Confirm Password" class="signup form-control form-horizontal border "/>
			          <input id="token" value='<?php echo $_REQUEST['id'] ?>' name="confirmpassword" type="hidden" placeholder="Confirm Password" class="signup form-control form-horizontal border"/>				
                                                        <p style="display:none;color:red" class="valid_error pass_error"></p>
							</div>
						<div class="spance">
                            	<div class="col-sm-2 col-md-2 col-lg-2 loginboxpading">
                                    <input type="button" id="resetpass" style="width:100px;margin-left:443px;margin-bottom:30px;"  class="form-control form-horizontal loginbtn1 " value="Submit">
									<!--<i class="fa fa-spinner fa-spin" style="font-size:1.5em;float:right; display: none;"""></i>-->
									
                            	</div>	
  						</div>
				</div>
			</div>
		</div>
                    <div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Confirmation</h4>
            </div>
            <div class="modal-body">
                <p>An Confirmation Email has been sent on your account</p>
                <p class="text-warning"><small></small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default closeButton" data-dismiss="modal">Close</button>
                
            </div>
        </div>
    </div>
 
</div>
                </div>
	</form>
</div>