<?php $session=new Zend\Session\Container('user'); 
 $token_session	=	$session->offsetGet('token');
?>
<?php if($token_session==""){ ?>
 	<script>
	window.location='<?php echo $this->basePath();?>';
 	</script>
 	<?php 
 }?>

<?php
//$this->plugin('basePath')->setBasePath($this->basePath().'/public');
$path=$this->basePath().'/';
?> 
		<!--footer-->
     <div class="container-fluid">     
 	<div class="row">
	 	<div class="col-lg-12 col-lg-col-lg-offset-2 text-center headingbg">
			<h2>My Account</h2>
		</div>
	 </div>	 
	  <div style="display:none;">
	<div id="success-msg" style="font-weight:bold;font-size:15px;color:green;text-align:center;">Your Profile updated Successfully</div>
      <div id="error-msg" style="font-weight:bold;font-size:13px;color:red;text-align:center;">Please Enter Email or Firstname</div>	
      </div>
     <div class="container marginbottom20">
      	<div class="row">
			<div class="col-lg-12">
				<div class="col-sm-3 col-md-3 col-lg-2">					 
					 <div class="list-group">
            <a href="<?php echo $this->basepath(); ?>/login/driver" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Dashboard</a>
            <a href="<?php echo $this->basepath(); ?>/login/driver/drivereditprofile" class="list-group-item "><i class="fa fa-arrow-circle-right"></i> &nbsp;Edit Profile</a>
            <a href="<?php echo $this->basepath(); ?>/login/driver/changepassword" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Change Password</a>
            <a href="<?php echo $this->basepath(); ?>/login/driver/driverorderhistory" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Booking History</a>
            <!--<a href="<?php echo $this->basepath(); ?>/login/driver/accountbalance" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Account Balance</a>
			<!--<a href="<?php echo $this->basepath(); ?>/login/driver/markupmanagement" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Markup Management</a>-->
			<a href="<?php echo $this->basepath(); ?>/login/driver/transaction" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Transaction</a>
             <a href="<?php echo $this->basepath(); ?>/login/driver/creditrequest" class="list-group-item yellactive"><i class="fa fa-arrow-circle-right"></i> &nbsp;Credit Request</a>
                <a href="<?php echo $this->basepath(); ?>/login/driver/bankdetail" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Bank Details</a>
			<a href="<?php echo $this->basepath(); ?>/login/driver/vehicleupdate" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Vehicle Details</a>
          </div>
				</div>				
        <div class="col-sm-9 col-md-9 col-lg-10">
            <div class="row" style="display:block;">
                <div class="col-lg-12">
                    <!--EDIT PROFILE START-->                    
                    <div class="panel panel-default">
                        <div   class="panel-heading tabheading text-center text-uppercase ">
                           <b style="display:;">Credit Limit Request</b>
						   <b style="display:none;">Change Password</b>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">						
						<!-- Dashboard Start-->	
        <div class="col-sm-12 col-md-12" style="display:block;">
            <div class="right_panel">
         	<div id="">
    <!-- Current avatar --><!-- Cropping modal -->
    <div id="crop-avatar">
	<!-- Current avatar -->	 
	<!-- Cropping modal -->
	<div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
	  <div class="modal-dialog modal-lg" style="margin-top:225px;">
		<div class="modal-content">
		  <form class="avatar-form" id="change_profileImage" name="change_profileImage" method="POST" action="<?php echo $this->basePath().'/tunnel/menu/updateDriverProfileImage';?>" enctype="multipart/form-data">
																	
			
			<div class="modal-footer">
			  <button class="btn btn-primary avatar-save col-sm-2 pull-right" id="save_image" type="submit" style="margin-left:10px;" onclick="changeProfileImage();">Save</button>
			  <button class="btn btn-default col-sm-2 pull-right" type="button" data-dismiss="modal">Close</button>														  
			</div>
		  </form>
		</div>
	  </div>
	</div><!-- /.modal -->
	<!-- Loading state -->											   
  </div><!-- /.modal -->
    <!-- Loading state -->   
  </div>             		
		<!-- <h5><center><b>Management</b></center></h5>
<center><div class="btn defaultbtnsearch ">Send SMS</div></center>
<h5><center>Current Status</center></h5>
<input type="text" id="driverStatus" name="dName" aria-controls="driver" class="form-control input-sm" disabled="">
<h5><center>Signup status</center></h5>
<center>
    <input type="text" id="driver_length" name="dName" aria-controls="driver" class="form-control input-sm" disabled="">
</center>-->
        </div>
                <div class="change_password">
                    <div class="left_panel">
					  <form action="" method="POST" name="driver_editProfile" id="driver_editProfile"> 
						<label><b>Deposit Date <span style="color:#f00 !important;">*</span></b></label>
						<div>
						<input type="text" class="input" name="deposit_date" id="deposit_date" style="text-transform:uppercase;">
						</div>
                        <div class="clear"></div>
                      
                                      
                                            <label><b>Payment Mode <span style="color:#f00 !important;">*</span></b></label>
                                            <div>
                                            <select name="ctl00$cph_main$drpPaymentMode" id="cph_main_drpPaymentMode"  class="input" onchange="javascript:control(this.value);">
	<option value="0">----Transaction Mode----</option>
	<option value="Cheque">Cheque</option>
	<option value="Demand Draft">Demand Draft</option>
	<option value="Online Transfer">Online Transfer</option>
	<option selected="selected" value="Cash Deposit">Cash Deposit</option>
</select></div>
<div class="clear"></div>
                                    <div id="fileupload" class="" style="width:100%; float:left;">
                                        
                                            <label><b>Upload Cheque / DD Copy/Transaction Slip</b></label>
                                            
                                                       
                                                        <input name="ctl00$cph_main$upldChq" id="cph_main_upldChq" class="" type="file">
                                     
                                    </div>
                                    <div id="trans" class="" style="display: none; width:100%; float:left;">
                                       
                                            <label><b>Transaction number</b> </label>
                                         
                                             <input name="ctl00$cph_main$txttransactionno" maxlength="20" id="cph_main_txttransactionno" class="input" type="text">
                                           
                                          
                                       
                                    </div>
                                    <div id="chequeno" class="" style="display: none; width:100%; float:left;">
                                       
                                            <label><b>Cheque / DD No.</b>  </label>
                                            <input name="ctl00$cph_main$txtChqNo" id="cph_main_txtChqNo" class="input" type="text">
                                        
                                    </div>
                                    <div class="" style="width:100%; float:left;">
                                       
                                            <label><b>Partner Bank Accounts</b> </label>
                                         
                                             <input name="ctl00$cph_main$drpBankAccounts" maxlength="20" id="cph_main_drpBankAccounts" 
                                             class="input" onchange="validate();" type="text">
                                           
                                                
                                           
                                    
                                    </div>	
                                           
                                                
                                           
                                   
                        
                        <div class="clear"></div>
						<div>
                        <label><b>Amount<span style="color:#f00 !important;">*</span></b></label>
						<input type="text" class="input" name="amount" id="amount"><p style="display:none;" class="vip-pin-ent-only-num">Please enter only number</p>
						</div>
                        <div class="clear"></div>
						<div>
                        <label><b>Deposited Bank<span style="color:#f00 !important;">*</span></b></label>
						<input type="text" class="input" name="deposit_bank" id="deposit_bank" style="text-transform:uppercase;">
                        </div>
						<div class="clear"></div>
						<div>
                        <label><b>Deposited Branch <span style="color:#f00 !important;">*</span></b></label>
						<input type="text" class="input" name="deposited_branch" id="deposited_branch">
                        </div>
						<div class="clear"></div>                        
                        <div class="clear"></div>
                        <label><b>Remark /Request </b></label> 
                        <input type="text" class="input" name="remark" id="remark">
                        
                        
                        <div class="clear"></div>
                        
						<div class="clear"></div>
						<input type="hidden" name="id_tbluser" id="id_tbluser">
						<input type="hidden" name="id_tbluserinfo" id="id_tbluserinfo">
						<input type="hidden" name="id_tbldriver" id="id_tbldriver">
						<button type="button" class="btn btn-primary submitbtn" style="margin-left:27% !important;" onclick="driver_payment_upload()" >Save</button>
						</form>
                    </div>
                    
                    
    </div>
	<div class="clear"></div>		
	<div class="col-sm-4 col-sm-offset-2 paddinttop10"></div>
						</div>
								</div>
							<!-- /.table-responsive End-->
                        </div>
							<!--EDIT PROFILE END-->
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
				</div>
			</div>
       	</div>
	 </div>

<script type="text/javascript">
var base_url = '<?php echo $this->basePath();?>';
function changeProfileImage(){	      	  
	  $("#change_profileImage").on('submit',(function(e){
		e.preventDefault();
			$.ajax({			
			type: "POST",
			data:  new FormData(this),
			contentType: false,
			cache: false,
			processData:false,
			url: $("#change_profileImage").attr('action'),
           dataType: "json",		 
           success: function(data){
                            if(data.status == 'true'){
								alert(data.Message);
								window.location.href = base_url+'/login/driver/drivereditprofile';																	
                             }else{
                                 alert(data.Message);
								 window.location.href = base_url+'/login/driver/drivereditprofile';
                             }
                        },		
                        error: function(error){
                            console.log(error);	
                        }	        
		});
	}));  
 }
        $(document).ready(function() {
            //$('#jsCarousel').jsCarousel({ onthumbnailclick: function(src) { alert(src); }, autoscroll: true });
            $.fn.dataTableExt.sErrMode = 'throw';
            fetch_driver_id();
        });
        
    function fetch_driver_id(){
        var token = $.cookie('token');
        $.ajax({
		url: '<?php echo $this->basePath();?>'+'/tunnel/menu/fetchDriverId',
		cache: false,
		dataType:"json",
		data:{
                    token:token
		},
                success: function(data){
                      //alert(data.driverId);
                      driverProfile(data.driverId); 
                },
                error:function (error){
                      //alert(error);
                      console.log(error);
                }
   });
}

function driverProfile(id){
//var token = $.cookie('token'); 
var token	=	$('#token').val();
 var uid=id;
  var site_url = jQuery.cookie('BaseUrl');      
        
         $.ajax({
                    dataType:'json',
                    url:site_url+'/tunnel/menu/profileDriver',
                    type:'POST',
                    data:{token:token},
                    success:successProfile,
                    error:errorProfile

                });

}

var global_url='<?php echo $this->basePath();?>';

function successProfile(data){
  // alert("qwe");     
   $("#profile_update").attr('id','profile_update_'+data.data.ID_tbluser);
   $("#vehicle_update").attr('id','vehicle_update_'+data.data.ID_tbluser);
    $("#driver_firstName").val(data.data.name);
    $("#driver_name").html(data.data.name);
   //alert(ss);
   $("#driver_lastName").val(data.data.lastname);
   $("#driver_father").val(data.data.fathername);
   $("#externalRef").val(data.data.refn);
   $("#city_driver").val(data.data.city);
   $("#createdDate").text(data.data.createDate);
   $("#email_driver").val(data.data.email);
   $("#driver_adds").val(data.data.address);
    $("#driver_addofc").val(data.data.ofcadds);
   $("#driver_phone").val(data.data.phone);
   $("#driver_username").val(data.data.userName);
   $("#driverBirth").val(data.data.db);
   $("#driverDefaullag").val('Hindi');
   //$("#driverGender").val(data.data.gender);
   $("#vehicleid").text(data.data.vehicleName);
   $("#driver_account").text(data.data.account);
   $("#driver_fleetNo").val(data.data.fleet);
   $("#driver_amount").val(data.data.amount);
   
   $("#driver_panNos").val(data.data.panNo);
   $("#driver_licence").val(data.data.licence);
   $("#driver_vehicleNo").val(data.data.vehicle);
   $("#driver_lstate").val(data.data.lstate);
   $("#driver_modely").val(data.data.modelV);
   $("#driver_zone").val(data.data.zone);
   $("#driver_route").val(data.data.route);
   $("#driver_pref").val(data.data.prflocation);
   $("#driver_weekoff").val(data.data.weekoff);
   $("#driveimei").val(data.data.iemi);
   $("#drivergps").val(data.data.gps);
   $("#id_tbluser").val(data.data.ID_tbluser);
   $("#id_tbluserinfo").val(data.data.ID_tbluserinfo);
   $("#id_tbldriver").val(data.data.ID_tbldriver);
   if(data.data.prof_img != ''){
       $("#profile_pic_update").attr("src",global_url+'/'+data.data.prof_img);
   }else{
       $("#profile_pic_update").attr("src",global_url+'/public/image/default_user.png');
       //alert(empty);
   }
   
   var pic = global_url+'/public/image/default_user.png';
   //alert(global_url);
   
   if(data.data.veh_img != ''){
       $("#vehicle_pic_update").attr("src",global_url+'/'+data.data.veh_img);
   }else{
       $("#vehicle_pic_update").attr("src",global_url+'/public/image/vehicle.png');
       //alert(empty);
   }
   
   //$("#vehicle_pic").attr("src",global_url+'/'+data.data.veh_img);
   $("#driver_name_head").html(data.data.name);
   $(".samount").val(data.data.amount);
   $("#emailVerify").val(data.data.verify);
   
   
   
   var emailv =$("#emailVerify").val();
   //alert(emailv);
   if(emailv == "1"){
        $('#emailVerify').prop('checked',true);
        $("#phoneverify").prop('checked',true);
   }
 var write = data.data.write;
 var write_lang = write.split(',');
 $("#write1").val(write_lang[0]);
 $("#write2").val(write_lang[1]);
 $("#write3").val(write_lang[2]);
 $("#write4").val(write_lang[3]);
 
 var speak = data.data.speak;
 var speak_lang = speak.split(',');
 $("#speak1").val(speak_lang[0]);
 $("#speak2").val(speak_lang[1]);
 $("#speak3").val(speak_lang[2]);
 $("#speak4").val(speak_lang[3]);
 
 
 var timing = data.data.timing;
 var timing_driver = timing.split(",");
 $("#time1").val(timing_driver[0]);
 $("#time2").val(timing_driver[1]);
 $("#time3").val(timing_driver[2]);
 
 var duty_pref = data.data.dutyprf;
 var pref_duty = duty_pref.split(',');
 for(i=0;i<=pref_duty.length;i++){
   $(".driver"+pref_duty[i]).prop('checked',true);  
 }
 
 
 var cash = data.data.cash;
 var driver_cash = cash.split(",");
 for(i=0;i<=driver_cash.length;i++){
   $(".driverCash"+driver_cash[i]).prop('checked',true);  
 } 
     var driver_status = data.data.active;
     if(driver_status == 1){
          $('#isActive').prop('checked', true);
          $('#driver_length').val('Active');
     }
     else if(driver_status == 2){
         $('#isHold').prop('checked', true);
         $('#driver_length').val('On Hold'); 
     }
     else if(driver_status == 3){
          $('#isBlack').prop('checked', true);
          $('#driver_length').val('Black Listed'); 
     }
     else if(driver_status == 4){
          $('#isInactive').prop('checked', true);
          $('#driver_length').val('Inactive'); 
     }
     else{
          $('#Unapproved').prop('checked', true);
          $('#driver_length').val('Unapproved'); 
     }
     
     
     var data_specs = data.data.eyetest;
	 if(data_specs == 1){
		 $('#specs_active').prop('checked', true); 
	 }else{
		$('#specs_inactive').prop('checked', true); 
	 }
     
 
    if(data.data.status_driver == "1"){
       var txt='Online';
      $("#driverStatus").val(txt);
   }
   else{
       var txt2 ="Offline";
       $("#driverStatus").val(txt2);
   }
   
   $("#driver_signup_comts").text(data.data.signup_comts);
   $("#driver_internal_comts").text(data.data.internal_comts);
   
   if(data.data.vendorName != null){
    $("#vName").text(data.data.vendorName); 
   }
   else if(data.data.vendorName == null){
     var name = "No Boss";
     $("#vName").text(name);    
   }
   
   
   if(data.data.photo == "1"){
      $(".photo").prop('checked',true); 
   }
   
   
        
}
function errorProfile(error){
     
    console.log(error);
    
}  

 function control(id) {
            debugger;
            document.getElementById("cph_main_drpPaymentMode").style.border = "0px";
            if (id == "Cheque") {
                document.getElementById("chequeno").style.display = 'block';
                document.getElementById("trans").style.display = 'none';
                document.getElementById("fileupload").style.display = 'block';
            }
            if (id == "Demand Draft") {
                document.getElementById("chequeno").style.display = 'block';
                document.getElementById("trans").style.display = 'none';
                document.getElementById("fileupload").style.display = 'block';
            }
            if (id == "Online Transfer") {
                document.getElementById("chequeno").style.display = 'none';
                document.getElementById("trans").style.display = 'block';
                document.getElementById("fileupload").style.display = 'none';
            }
            if (id == "Cash Deposit") {
                document.getElementById("chequeno").style.display = 'none';
                document.getElementById("trans").style.display = 'none';
                document.getElementById("fileupload").style.display = 'block';
            }


        }

$("#amount").keypress(function(evt){
	var event	=	$(this).val();
	var charCode = (evt.which) ? evt.which : event.keyCode
	if (charCode != 46 && charCode > 31 && (charCode < 48 || charCode > 57)){
	$(".vip-pin-ent-txt").css({"display":"none"});
	$(".vip-pin-ent-only-num").css({"display":"block","color":"red"});
	return false;
	}else{
	return true;
	}
});
   
</script>
    
<style>
label {
    color: #5c5c5c;
    font-family: "Conv_GothamRounded-Light",sans-serif;
    font-size: 13px;
    font-weight: normal !important;
    padding: 5px 0 0;
}

</style>