<style>
span
{
	font-size:13px;
}
.panel-heading
{
	font-size:13px;
}
.newheaing {
    font-size: 13px !important;
    line-height: 1.42857;
}
body {
    color: #000;
    font-family: "Conv_GothamRounded-Light",sans-serif;
    font-size: 13px;
    line-height: 1.42857;
}

</style>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12 col-lg-col-lg-offset-2 text-center headingbg">
      <h2>My Account</h2>
    </div>
  </div>
  <div class="container marginbottom20">
    <div class="row">
      <div class="col-lg-12">
        <div class="col-sm-3 col-md-3 col-lg-2">
          <div class="list-group"> 
			  <a href="<?php echo $this->basepath(); ?>/login/driver" class="list-group-item yellactive"><i class="fa fa-arrow-circle-right"></i> &nbsp;Dashboard</a> 
			  <a href="<?php echo $this->basepath(); ?>/login/driver/drivereditprofile" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Edit Profile</a> 
			  <a href="<?php echo $this->basepath(); ?>/login/driver/changepassword" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Change Password</a> 
			  <a href="<?php echo $this->basepath(); ?>/login/driver/driverorderhistory" class="list-group-item "><i class="fa fa-arrow-circle-right"></i> &nbsp;Booking History</a> 
			  <!--<a href="<?php echo $this->basepath(); ?>/login/driver/accountbalance" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Account Balance</a> -->
			  <!--<a href="<?php echo $this->basepath(); ?>/login/driver/markupmanagement" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Markup Management</a> -->
			  <a href="<?php echo $this->basepath(); ?>/login/driver/transaction" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Transaction</a>
              <a href="<?php echo $this->basepath(); ?>/login/driver/creditrequest" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Credit Request</a>
              <a href="<?php echo $this->basepath(); ?>/login/driver/bankdetail" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Bank Details</a>
			  <a href="<?php echo $this->basepath(); ?>/login/driver/vehicleupdate" class="list-group-item"><i class="fa fa-arrow-circle-right"></i> &nbsp;Vehicle Details</a>			  
		  </div>
        </div>
        <div class="col-sm-9 col-md-9 col-lg-10">
          <div class="row" style="display:block;">
            <div class="col-lg-12">
              <div class="panel panel-default">
                <div class="panel-heading tabheading text-center text-uppercase "> <b style="display:;">Dashboard</b> </div>
                <!-- /.panel-heading -->
                <div class="panel-body"> 
                  
                  <!-- Dashboard Start-->
                  <div class="col-sm-12 col-md-12" style="display:block;">
                  <div class="row">
				  <div style="height:">
				     <center>
                      <h2 id="welcome"></h2>
                     </center>
					 <div class="image_box" style="margin-top:-33px;">
					 <div id="crop-avatar">
						<!-- Current avatar -->											   
						<div class="avatar-view userimg_byratio" title="Profile Picture">
						<a href="#avatar-modal" data-toggle="modal" title="Update Profile Picture">
						<img id="d_image" src="" style="float:right;margin-right:25px" width="80" height="70" /></a>
						  <!--<img src="public/image/default_user.png" alt="Avatar" class="resimg">-->
						</div>
					 <!--<a href="#avatar-modal" data-toggle="modal" title="Profile Picture"><strong style="color: rebeccapurple;margin-left:128px;">Change Profile Picture</strong></a>-->
						<!-- Cropping modal -->
						<div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
						  <div class="modal-dialog modal-lg" style="margin-top:225px;">
							<div class="modal-content">
							  <form class="avatar-form" id="change_profileImage" name="change_profileImage" method="POST" action="<?php echo $this->basePath().'/tunnel/menu/updateDriverProfileImage';?>" enctype="multipart/form-data">
								<div class="modal-header">
								 <h1 class="closbtn" style="right: ; top:; border: none !important;" data-dismiss="modal"><i class="fa fa-close"></i></h1>
								  <h4 class="modal-title" id="avatar-modal-label">Profile Picture</h4>
								</div>														
								<div class="modal-body">
								  <div class="avatar-body">
									<!-- Upload image and data -->
									<div class="avatar-upload">
									  <input class="avatar-src" name="avatar_src" type="hidden">
									  <input class="avatar-data" name="avatar_data" type="hidden">
									  <label for="avatarInput">&nbsp;</label>														   
									  <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
									</div>
									<!-- Crop and preview -->
									<div class="row">
									  <div class="col-md-9">
										  <div class="loading" tabindex="-1" role="img" aria-label="Loading"></div>
										<div class="avatar-wrapper"></div>
									  </div>
									  <div class="col-md-3">
										<div class="avatar-preview preview-lg" style="position:relative"></div>
										<div class="avatar-preview preview-md" style="position:relative"></div>
										<div class="avatar-preview preview-sm" style="position:relative"></div>
									  </div>
									</div>
								  </div>
								</div>
								<div class="modal-footer">
								  <button class="btn btn-primary avatar-save col-sm-2 pull-right" id="save_image" type="submit" style="margin-left:10px;" onclick="changeProfileImage();">Save</button>
								  <button class="btn btn-default col-sm-2 pull-right" type="button" data-dismiss="modal">Close</button>														  
								</div>
							  </form>
							</div>
						  </div>
						</div><!-- /.modal -->
						<!-- Loading state -->											   
					  </div>
					  <!--<img id="d_image" src="" style="float:right;margin-right: 11px;" width="80" height="70" /> -->
					  <!--<img id="d_veh_image" src="" style="float:right; margin-right: 5px;" width="129" height="120" />-->
					  </div>
				  </div>
                   </div>
                    <div class="col-sm-4 paddinttop10">
                      <div class="portlet portlet-de" style="border:1px solid #d5d3d4;">
                        <div class="panel-heading text-center text-uppercase" style="background:#f5f5f5;"> <b style="display:;">Segment</b> </div>
                        <div class="portlet-body">
                          <div class="table-responsive ">
                            <center>
                              <label id="userType"></label>
                            </center>
                          </div>
                        </div>
                      </div>
                      <!-- /.portlet --> 
                      
                    </div>
                    <div class="col-sm-4 paddinttop10">
                      <div class="portlet portlet-de" style="border:1px solid #d5d3d4;">
                        <div class="panel-heading text-center text-uppercase" style="background:#f5f5f5;"> <b style="display:;">Discount</b> </div>
                        <div class="portlet-body">
                          <div class="table-responsive ">
                            <center>
                              <label>%</label>
                            </center>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-4 paddinttop10">
                      <div class="portlet portlet-de" style="border:1px solid #d5d3d4;">
                        <div class="panel-heading text-center text-uppercase" style="background:#f5f5f5;"> <b style="display:;"><a href="<?php echo $this->basepath(); ?>/login/driver/transaction" class="">Account Balance</a></b> </div>
                        <div class="portlet-body">
                          <div class="table-responsive ">
                            <center><a href="<?php echo $this->basepath(); ?>/login/driver/transaction" class="list-group-item">
                              <label id="acc_bal"></label>
                              </a>
                            </center>
                          </div>
                        </div>
                      </div>
                      <!-- /.portlet --> 
                      
                    </div>
                   
                      <div class="clear"></div> 
					  <div class="col-sm-4 paddinttop10" >
						  <div class="portlet portlet-de" style="border:1px solid #d5d3d4;">
							<div class="panel-heading text-center text-uppercase" style="background:#f5f5f5;"> <b style="display:;">Personal Details</b> </div>
							<div class="portlet-body" style="height: 100px;">
							  <div class="table-responsive ">
									<table class="table3" style="border:0px;">
										<tr>
											<td>
											<span><strong>Name:&nbsp;&nbsp;&nbsp;</strong></span><span id="driver_firstName"></span><br/>
											<span><strong>Email:&nbsp;&nbsp;&nbsp;</strong></span><span id="email_driver"></span><br/>
											<br/>
											<span><strong>Mobile:&nbsp;&nbsp;</strong></span><span id="d_mob"></span>
											</td>
										</tr>										
									</table>
							  </div>
							</div>
						  </div>
                      </div>
					  <div class="col-sm-4 paddinttop10" style="width: ;">
						  <div class="portlet portlet-de" style="border:1px solid #d5d3d4;">
							<div class="panel-heading text-center text-uppercase" style="background:#f5f5f5;"> <b style="display:;">Official Address</b> </div>
							<div class="portlet-body" style="height: 100px;">
							  <div class="table-responsive ">
									<table class="table3" style="border:0px;">
										<tr>
											<td>
											<span><strong>Address:&nbsp;&nbsp;</strong></span><span id="v_address"></span><br/>	
											<br/>
											<span><strong>Mobile:&nbsp;&nbsp;</strong></span><span id="v_mob2"></span>
											</td>											
										</tr>										
									</table>
								  <!--<label style="margin-left: 5;"><strong>Name: </strong></label><label id="v_name" style=""></label><br/>
								  <label style="margin-left: 5;"><strong>Email: </strong></label><label id="v_email" style=""></label><br/>-->
							  </div>
							</div>
						  </div>
                      </div>
					   <div class="col-sm-4 paddinttop10" style="width:;">
						  <div class="portlet portlet-de" style="border:1px solid #d5d3d4;">
							<div class="panel-heading text-center text-uppercase" style="background:#f5f5f5;"> <b style="display:;">Residential Address</b> </div>
								<div class="portlet-body" style="height: 100px;">
								  <div class="table-responsive ">
										<table class="table3" style="border:0px;">
											<tr>
												<td>
													<span><strong>Address:&nbsp;&nbsp;</strong></span><span id="d_address"></span><br/>
													<span id="d_city"></span><span id="d_state"></span><br/>
													<span id="d_country"></span><span id="d_pin"></span><br/>
													<span><strong>Mobile: </strong></span><span id="res_mob"></span>
												</td>											
											</tr>										
										</table>
								  </div>
								</div>
						  </div>
                      </div>					                       
					  <div class="col-sm-6 paddinttop10" >
                        <div class="portlet portlet-de" style="border:1px solid #d5d3d4; height:186px;">
                          <div class="panel-heading text-uppercase" style="background:#f5f5f5;"> <b style="display:;"><a href="<?php echo $this->basepath(); ?>/login/driver/driverorderhistory" class=" " style="cursor:pointer;">Booking Details</a></b> </div>
                          <div class="portlet-body" style="height:156px;">
                            <div class="table-responsive " style="overflow-x: auto;">
                              <table class="table borderless table-responsive">
                                <tr>
                                  <td><b>Total</b></td>
                                  <td><b>Completed</b></td>
                                  <td><b>Pending</b></td>
                                  <td><b>Canceled</b></td>
                                </tr>
                                <tr>
                                  <td id="total_book"></td>
                                  <td id="completed_book">
                                  <td id="pending_book"></td>
                                  <td id="canceled_book"></td>
                                    </td>
                                </tr>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-6 paddinttop10" >
                        <div class="portlet portlet-de" style="border:1px solid #d5d3d4;">
                          <div class="panel-heading text-uppercase" style="background:#f5f5f5;"> <b style="display:;">Log Details</b> </div>
                          <div class="portlet-body">
                            <div class="table-responsive " style="overflow-x: auto;">
                              <table class="table borderless table-responsive">
                                <tr>
                                  <td><b>Logs</b></td>
                                  <td><b>Monthly</b></td>
                                  <td><b>Weekly</b></td>
                                  <td><b>Daily</b></td>
                                </tr>
                                <tr>
                                  <td>Login Hours</td>
                                  <td id="month_log"></td>
                                  <td id="week_log">
                                  <td id="daily_log"></td>
                                </tr>
                                <tr>
                                  <td>Logout Hours</td>
                                  <td id="month_logout"></td>
                                  <td id="week_logout">
                                  <td id="daily_logout"></td>
                                </tr>
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-12 paddinttop10"> </div>
                  
                    
                    <!--						<div class="row">
							<div class="portlet portlet-de" style="border:1px solid #d5d3d4;">
			                         <div class="panel-heading text-uppercase" style="background: #e9e5e4;">
			                           <b style="display:;">Recent Orders</b>
			                         </div>
			                            <div class=" ">
			                                <div class="table-responsive ">
			    <table class="table" id="driver" style=" margin: 0; padding: 0;">
                                            <thead style="background:#f5f5f5">
                                                   <tr>
                                                       <th>Id</th>
                                                        <th style="width:81px !important;">Pick Up Time</th>
                                                        <th>Vehicle</th>
                                                        <th style="width:91px !important;">Booking Type</th>
                                                        <th>Partner</th>
                                                        <th>Client</th>
                                                        <th style="width:287px !important;">Departure</th>
                                                        <th style="width:130px !important;">Drop Area</th>
                                                        <th>Status</th>
                                                   </tr>
                                            </thead>
                              </table>
			                                </div>
			                            </div>
						</div>
									
									
								
								</div>--> 
                    
                    <!-- /.table-responsive End--> 
                    
                  </div>
                  <!-- Dashboard End--> 
                  
                  <!-- /.panel-body --> 
                </div>
                <!-- /.panel --> 
              </div>
              <!-- /.col-lg-12 --> 
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
var base_url = '<?php echo $this->basePath();?>';
function changeProfileImage(){	      	  
	  $("#change_profileImage").on('submit',(function(e){
		e.preventDefault();
			$.ajax({			
			type: "POST",
			data:  new FormData(this),
			contentType: false,
			cache: false,
			processData:false,
			url: $("#change_profileImage").attr('action'),
           dataType: "json",		 
           success: function(data){
                            if(data.status == 'true'){
								alert(data.Message);
								window.location.href = base_url+'/login/driver';																	
                             }else{
                                 alert(data.Message);
								 window.location.href = base_url+'/login/driver';
                             }
                        },		
                        error: function(error){
                            console.log(error);	
                        }	        
		});
	}));  
 }
	


function loginhome(){
	var base_url = "<?php echo $this->basePath(); ?>";
	//alert(base_url);
//window.open('http://50.62.22.158:8085/hello42test/public/login',"_self");
window.open(base_url+'/login',"_self");
}


function signuphome(){
	
	window.open(base_url+'/login',"_self");
	
}


</script> 
<script type="text/javascript">
        $(document).ready(function() {
            //$('#jsCarousel').jsCarousel({ onthumbnailclick: function(src) { alert(src); }, autoscroll: true });
            book_count();
            driverProfile();
            $.fn.dataTableExt.sErrMode = 'throw';
        });
        
       
//        function fetch_driver_id(){
//                        var token = $.cookie('token'); 
//                        table=$('#driver').dataTable({
//                        "ajax": '<?php echo $this->basePath();?>/tunnel/menu/driverOrderHistory?ids='+token,
//                        "deferRender": true
//                        });  
//                        $("#driver_wrapper").attr("style","border:1px solid #d2d2d2;");
//                        $("#driver_wrapper").addClass("clearfix");
//                        //$("#driver_wrapper").addClass("font12px");
//                        $("#driver_wrapper + div").removeClass("row");
//                        $("#driver_info").parent().parent().removeClass("row");
//                        $("#driver_wrapper div:first").attr("class","tbsearchrow clearfix");
//                        $('#driver_filter label').attr("style","display:none;");
//                        $(".paginate_button").attr("style","z-index:999 !important;");
//                        driverProfile(token);
//}

function driverProfile(id){

  var site_url = jQuery.cookie('BaseUrl');      
       // var token = $.cookie('token'); 
       var token	=	$('#token').val(); 
      //alert(token); 
      //return false;
         $.ajax({
                    dataType:'json',
                    url:site_url+'/tunnel/menu/profileDriver',
                    type:'POST',
                    data:{token:token},
                    success:successProfile,
                    error:errorProfile

                });

}

var global_url='<?php echo $this->basePath();?>';

function successProfile(data){
  // alert("qwe"); 
  var name = data.data.name+" "+data.data.lastname;
  $("#email_driver").html(data.data.email);
  $("#driver_firstName").html(name);
  $("#welcome").html("Welcome "+name);
  $("#driver_phone").html(data.data.phone);
  $("#userType").html("Driver");
  $("#d_address").html(data.data.address);
  $("#d_city").html(data.data.cn);
  $("#d_state").html(", "+data.data.sn);
  $("#d_pin").html(", "+data.data.pin);
  $("#d_country").html(data.data.countryName);
  $("#d_mob").html(data.data.phone);
  $("#res_mob").html(data.data.phone);
  $("#d_id").html(data.data.ID_tbluser);
  $("#acc_bal").html(data.data.amount);
  
  if(data.data.prof_img != ''){
       $("#d_image").attr("src",global_url+'/'+data.data.prof_img);
   }else{
       $("#d_image").attr("src",global_url+'/public/image/default_user.png');
   }
  
  if(data.data.veh_img != ''){
       $("#d_veh_image").attr("src",global_url+'/'+data.data.veh_img);
   }else{
       $("#d_veh_image").attr("src",global_url+'/public/image/vehicle.jpg');
   }
  
  $("#v_name").html(data.data.v_name);
  $("#v_email").html(data.data.v_email);
  $("#v_id").html(data.data.v_id);
  $("#v_mob").html(data.data.v_mob);
  $("#v_address").html(data.data.ofcadds);
  $("#v_city").html(data.data.v_city);
  $("#v_state").html(", "+data.data.v_state);
  $("#v_pin").html(", "+data.data.v_pin);
  $("#v_country").html(data.data.v_country);
  $("#v_mob2").html(data.data.v_mob);
  
  console.log(data.data);
}
function errorProfile(error){
    console.log(error);
}
 
 
function book_count()
{
    var site_url = jQuery.cookie('BaseUrl');      
    var token = $.cookie('token');
     $.ajax({
                dataType:'json',
                url:site_url+'/tunnel/menu/log_count',
                type:'POST',
                data:{token:token},
                success:successCount,
                error:errorProfile

            });
}
 
function successCount(data)
{
  $("#total_book").html(data.data[0].total);
  $("#completed_book").html(data.data[0].complete);
  $("#pending_book").html(data.data[0].pending);
  $("#canceled_book").html(data.data[0].cancel);
  $("#month_log").html(data.data[0].month_log);
  $("#week_log").html(data.data[0].week_log);
  $("#daily_log").html(data.data[0].day_log);
  $("#month_logout").html(data.data[0].month_logout);
  $("#week_logout").html(data.data[0].week_logout);
  $("#daily_logout").html(data.data[0].day_logout);
}

    
        
</script> 
