



<?php 
$path=$this->basePath();
if (defined('RUNNING_FROM_ROOT')) {
  $this->plugin('basePath')->setBasePath($this->basePath().'/public');
} ?>
<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(''. $this->translate('Hello42'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
		 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                      
			->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min1.css')
                        ->prependStylesheet($this->basePath() . '/css/custom.css')
                        ->prependStylesheet($this->basePath() . '/font-awesome-4.2.0/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/font-awesome-4.2.0/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/carousel.css') 
                        ->prependStylesheet($this->basePath() . '/css/jsCarousel.css') 
						?>

        <!-- Scripts -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
                <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    
        <?php echo $this->headScript()
			 ->prependFile($this->basePath() . '/js/jquery.bpopup.js')
                        ->prependFile($this->basePath() . '/js/jquery.bpopup.min.js')
                         ->prependFile($this->basePath() . '/js/userhomemap.js')
			 ->prependFile($this->basePath() . '/lib/site.js')
                         ->prependFile($this->basePath() . '/js/login.js')
			 ->prependFile($this->basePath() . '/js/jquery.cookie.js')	
                         ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
			->prependFile($this->basePath() . '/js/userhome.js')
			->prependFile($this->basePath() . '/js/jsCarousel.js')		
			//->prependFile($this->basePath() . '/js/jquery.colorbox.js')
			
			
			
			->prependFile($this->basePath() . '/js/jquery-1.11.0.min.js')
            ->prependFile($this->basePath() . '/js/jquery-migrate-1.2.1.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.11.0.min.js')
            ->prependFile($this->basePath() . '/js/jquery-migrate-1.2.1.min.js')
            
             ->prependFile($this->basePath() . '/js/regioncheck.js')
                ->prependFile($this->basePath() . '/js/global_text.js')
                ->prependFile($this->basePath() . '/js/booking_data.js')
           // ->prependFile($this->basePath() . '/ie-emulation-modes-warning.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
               ->prependFile($this->basePath() . '/js/predefine.js',   'text/javascript')  
        ; 
		
		
		?>

    </head>
    <body>

<script>
	var baseurl = "<?php echo $this->basePath(); ?>";	
   jQuery.cookie('BaseUrl', baseurl, { expires: 3 }); 
</script>
 
   <div class="container-fluid navbar-inverse height25"> 
   <div class="container navbar-inverse height25">
	<div class="navbar navbar-inverse minhight30 marginbtom0 clearfix height25" role="navigation" style="border-radius:0; border:none;">
      
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
             <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         </div>
        <div class="navbar-collapse collapse  navbar-right" style="padding:0;">
          <ul class="nav navbar-nav">
              <li class="active "><a href="#" class="font12px"><i class="fa fa-home fa-fw fa-1x"></i><span id="menu_home"></span></a></li>
              <li><a href="#about" class="font12px "><i class="fa fa-user fa-fw fa-1x"></i><span id="menu_aboutus"></span></a></li>
              <li><a href="#contact" class="font12px "><i class="fa fa-paper-plane fa-fw fa-1x"></i><span id="home_services"></span></a></li>
              <li><a href="#contact" class="font12px"><i class="fa fa-phone fa-fw fa-1x"></i><span id="home_contact"></span></a></li>
           </ul>
        </div><!--/.nav-collapse -->
       
    </div>
    </div>
	</div>
	
    <div class="container-fluid">
    	<div class="container container_header">
        	<div class="col-sm-3 col-md-3 col-lg-3 marginbottom20">
	   	        <a href="#" style="margin-left: 10px;"><img src="public/image/logo.png" width="127" height="65"></a>
          </div><?php print_r($this->id); ?>
           

          
            <?php echo $this->content; ?>
         
			</div>
			</div>
			
			
            
   
   
   
   
   
   
   
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
		<!--footer-->
		<div class="container-fluid webfooter">
    	<div class="container">
             <div class="col-lg-12">
              <div style="padding: 10px 20px;">
               <p>
               <a href="#">About Us</a>
               <a href="#">Services</a>
               <a href="#">Partners</a>
               <a href="#">Careers</a>
               <a href="#">Testimonials</a>
               <a href="#">Terms & Conditions</a>
               <a href="#">Contact US</a>
               </p>
               <p class="padding_margin0">
                 <a class="btn btn-social-icon padding_margin0"><i class="fa fa-facebook fa-1x socialneticons"></i>Facebook</a>
                 <a class="btn btn-social-icon padding_margin0"><i class="fa fa-tumblr fa-1x socialneticons"></i>twitter</a>
                 <a class="btn btn-social-icon padding_margin0"><i class="fa fa-linkedin fa-1x socialneticons"></i>linkedin</a>
                 <a class="btn btn-social-icon padding_margin0"><i class="fa fa-google-plus fa-1x socialneticons"></i>google-plus</a>
               
               </p>
               <p>Copyright 2013 &copy; Hello42 Pvt. Ltd. All Rights Reserved.</p>
              
              </div>
                
            </div>
        </div>
    </div>
		<!--footer-->
		
    </body>
	
</html>
<!--<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>-->
