<?php //echo $id=$_REQUEST['id']; ?>



<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/about-us.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>
    

<section id="" >
        <div class="container">
          <div class="center wow fadeInDown col-lg-12">
            <h2 align="left">About Us</h2>
               <p align="left">Hello 42 cabs is a one-stop-shop for all personal ground transportation services be it point to point, local hire, outstation or package tours. It is the brainchild of Neeraj Rustagi, CEO, Regency Tours Pvt Ltd,  who has very vast experience in travel industry very much pioneer in B2B and B2C trade since 1994.</p>
                
                <p align="left">Hello 42 cabs is based in Delhi and was  launched in 2015 with a long term vision of fast, reliable and transparent car rental solutions. Customers can access Hello42 through multiple ways : through our user-friendly website, mobile app and 24x7 multi-lingual call centre.  We offer our user various travelling services along with real time tracking, messaging and refer-win features.</p>
               
   <br />

<div class="row">
                <div class="features">
                    <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="feature-wrap" align="left">
                            <i class="fa fa-bullhorn"></i>
                            <h3 ><strong>Our Services</strong></h3>
                            <ul>
                            	<li>24 x 7 support</li>
                                <li>Real Time Cab Tracking</li>
                                <li>Details share feature in App</li>
                                <li>Car Rental for Local and Outstation Usage
Transfer service for Airport / Railway station</li>
<li>Car Hire for any package tour</li>
                            </ul>
                        </div>
                    </div><!--/.col-md-4-->

                    <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="feature-wrap" align="left">
                        
                            <i class="fa fa-comments"></i>
                           
                            <h3><strong>Our Fleet</strong> </h3>
                           
                            <ul>
                            	<li>
                            We are offering a large variety of well maintained and young fleet.
</li>
<li>
Our vehicle are loaded with Amenities for  a comfortable ride.
</li>
<li>
All cars have GPS systems for additional safety.
</li>
<li>
No compromise on cab quality
</li>
</ul>

                        </div>
                    </div><!--/.col-md-4-->

                    <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="feature-wrap" align="left">
                            <i class="fa fa-cloud-download"></i>
                            <h3><strong>Our Chauffeurs</strong> </h3>
                            <p> 
                            <ul>
                            	<li>
                            Ours Chauffeurs are fully trained and police verified.
                            </li>
                            <li>
They are mannered and well groomed.
</li>
<li>
Our chauffeur training is collectively known as HSE i.e. Health, 

Security and Environment training. 
</li>
<li>
All Chauffeurs  work according to the fatigue management.
</li>
    </ul>
</p>
                        </div>
                    </div><!--/.col-md-4-->
                
                </div><!--/.services-->
            </div>

            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>
<!--/.container
<section id="feature">
        <div class="container">
            <div class="clients-area center wow col-lg-12 fadeInDown">
                <h2>Our Team</h2>
                <p class="lead">Ours Chauffeurs are fully trained and police verified. 
They are mannered and well groomed.<br />
Our chauffeur training is collectively known as HSE i.e. Health, Security and Environment training. <br />
All Chauffeurs  work according to the fatigue management.
</p>
            </div>

 

            <div class="row">
                <div class="col-md-4 wow fadeInUp">
                    <div class="clients-comments text-center">
                        <img src="<?php echo $this->basePath();  ?>/public/images/client1.png" class="img-circle" alt="">
                        <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</h3>
                        <h4><span>-John Doe /</span>  Director</h4>
                    </div>
                </div>
                <div class="col-md-4 wow fadeInDown">
                    <div class="clients-comments text-center">
                        <img src="<?php echo $this->basePath();  ?>/public/images/client2.png" class="img-circle" alt="">
                        <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</h3>
                        <h4><span>-John Doe /</span>  Director</h4>
                    </div>
                </div>
                <div class="col-md-4 wow fadeInDown">
                    <div class="clients-comments text-center">
                        <img src="<?php echo $this->basePath();  ?>/public/images/client3.png" class="img-circle" alt="">
                        <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt</h3>
                        <h4><span>-John Doe /</span>  Director</h4>
                    </div>
                </div>
           </div>
           
           
             </div>
</section>
-->
