<?php //echo $id=$_REQUEST['id']; ?><body dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Accountant</strong></h2><br>

                <strong>Position : - Sr. Accountant </strong><br>

                 <strong>Exp:-  1 to 5  Years</strong><br />
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->
<p>
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
  <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->
</p>
<p><strong>Job  Description</strong></p>
<ul>
  <li>
    <p> Experience of accounting data entry.&nbsp;</p>
  <li>
    <p> Purchase and various cash &amp; bank activities and bank  	reconciliation.&nbsp;</p>
  <li>
    <p> Knowledge of software Yatra, tally, MS Excel.</p>
  <li>
    <p> Vendors payment.</p>
  <li>
    <p> Monthly expense information report.</p>
  <li>
    <p> Maintaining records of journal voucher &amp; bank voucher</p>
  <li>
    <p> Create the bank payment voucher &amp; journal voucher.</p>
  <li>
    <p> Reconciliation of Bank Account, T.D.S Return, Service Tax  	Knowledge.</p>  
</ul>
                
      <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
      <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->
      <p>
        <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
        <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	--><strong>Skills  and personal qualities</strong></p>
      <ul>
        <li>
          <p> Candidate should be a Graduate in Commerce Stream.</p>
        <li>
          <p> Person should have 1+ Year work experience of taking care of  	accounts and audit.</p>
        <li>
        <p> Candidates from Travel industry would be preferred.<br>
          <br>
        </p>
        </ul>
      <p>
        <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">1)Prepare, examine, and analyze accounting records, financial  statements, and other financial reports to assess accuracy,  completeness, and conformance to reporting and procedural standards. </p>
<p> 2) Compute taxes owed and prepare tax returns, ensuring compliance  with payment, reporting and other tax requirements.      </p>
      <p> 3) Analyze business operations, trends, costs, revenues, financial  commitments, and obligations, to project future revenues and expenses  or to provide advice.      </p>
      <p> 4) Report to management regarding the finances of establishment.      </p>
      <p> 5) Establish tables of accounts, and assign entries to proper  accounts.      </p>
      <p> 6) Develop, maintain, and analyze budgets, preparing periodic  reports that compare budgeted costs to actual costs.</p>
      <p> Develop, implement, modify, Document record keeping and accounting  systems, making use of current computer technology.      </p>
      <p> 8) Prepare forms and manuals for accounting and book keeping  personnel, and direct their work activities.      </p>
      <p> 9) Survey operations to ascertain accounting needs and to  recommend, develop, and maintain solutions to business and financial  problems.</p>
      <p> 10) Work as Internal Revenue Audit &amp; Service agents.      </p>
      <p> 11) Advise management about issues such as resource utilization,  tax strategies, and the assumptions underlying budget forecasts.      </p>
      <p> 12) Provide internal and external auditing services for businesses  and individuals.      </p>
      <p> 13) Investigate bankruptcies and other complex financial  transactions and prepare reports summarizing the findings.      </p>
      <p> 14) Represent clients before taxing authorities and provide  support during litigation involving financial issues.      </p>
      <p> 15) Appraise, evaluate, and inventory real property and equipment,  recording information such as the property's description, value, and  location.      </p>
      <p> 16) Maintain and examine the records of government agencies.</p>
<p>
<p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>