<?php //echo $id=$_REQUEST['id']; ?><body dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Admin &amp; HR</strong></h2>
                <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
                <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->
                <p><strong>Position: - </strong><strong>HR  &amp; Admin</strong>    <br>
            
               <strong>Exp: - 3+  Years</strong><br>
                  
                  
                  <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br />
                </p>
<p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->
<p><strong>Job  Description</strong></p>
<ul>
  <li>
    <p>Good  	Knowledge in T &amp; D (Training &amp; Development)</p>
  <li>
    <p>Making  	the Training Module &amp; giving the training to the Team &amp;  	Drivers.</p>
  <li>
    <p>Helping  	the employ to achieve KRA by providing training &amp; upgrading  	them.</p>
  <li>
    <p>Training  	module.</p>
  <li>
    <p>Talent  	Acquisition &amp; Manpower Planning.</p>
  <li>
    <p>Responsible  	for recruitment &amp; selection at all levels of technical &amp;  	commercial to set up the entire Projects Manpower.</p>
  <li>
    <p>Background  	verification for selected candidate professional and as well as  	educational for key position.</p>
  <li>
    <p>Constant  	Interaction with senior members of functional departments to  	understand and interpret efficiently job &amp; competency  	requirements in order to ensure apt profile matching.</p>
  <li>
    <p>To  	Prepare and maintain the recruitment MIS report to present in  	Management Review Meeting.</p>
  <li>
    <p>Preparing  	Minutes of the Meetings &amp; follow up with concerned departments.</p>
  <li>
    <p>Preparing  	the offer letter and issuance of the same to the candidate.</p>
  <li>
    <p>Resource  	allocation i.e. arranging workstation other facilities to new  	recruits.</p>
  <li>
    <p>To  	collect and recheck the Documents for Personal file &amp; Open the  	Salary Account. </p>
  <li>
    <p>Employee  	grievance handling &amp; explaining the policies &amp; process.</p>
  <li>
    <p>To  	complete perfectly HR related assignment given by senior in HR  	Department/management.</p>
  <li>
    <p>To take  	the Exit interview &amp; clearance of the resigned Employee. </p>
  <li>
    <p>To  	Maintain and give salary details of the newly joined Employees &amp;  	revised salary to process the salary.</p>
  <li>
    <p>Maintaining  	Leave Records and Compensatory off of all Employees Month Wise.</p>  
</ul>
<p> <strong>Skills</strong></p>
<ul>
  <li>
    <p>Initiative  	and Commitment to Achieve.</p>
  <li>
    <p>Adaptability  	and innovation.</p>
  <li>
    <p>Have  	excellent leadership and managerial skills.</p>
  <li>
    <p>Must be  	computer literate, familiarity with Microsoft excel, word, and  	outlook. </p>
  <li>
    <p>Ability  	to speak English reasonably well.</p>
  <li>
    <p>Be  	professional, and positive.</p>
  <li>
    <p>Prior  	managerial experience.</p>
  </ul>
<p>
<p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>