<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Android Developer</strong></h2>
                <strong>Position : - Android Developer </strong><br />
                <strong>Exp:-  1+  Years</strong><br />
                <strong>Job Location: Delhi (Karol Bagh)</strong><br />
               <strong>Date Posted: 23-03-2016</strong><br /><br />

               <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />

    
    <strong>Job Brief</strong><br />


        We are looking for an Android Developer who possesses a passion for pushing
mobile technologies to the limits and will work with our team of talented
engineers to design and build the next generation of our mobile applications.
<br />
<br />
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  		a:link { color: #0000ff; so-language: zxx }  	-->
<p><strong>Job  Description</strong></p>
<ul>
  <li>
    <p align="left"> Android Developer  	(Have done any work on Map, GPS, Tracking, Web services).</p>
  </li>
  <li>
    <p align="left"> Having knowledge  	of Notification Services.</p>
  </li>
  <li>
    <p align="left"> Good understanding  	of Java &amp; Oops Concept.</p>
  </li>
  <li>
    <p align="left"> Strong analytical  	skills</p>
  </li>
</ul>
<p style=" float:right;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
            </div> 
          
        </div>
    </section>