<?php //echo $id=$_REQUEST['id']; 

// echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-danger'));
?>




<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container">
            <div class="center col-lg-12">        
                <h2><strong>Apply Now</strong></h2>
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:
     <br />
<br />
           
                

( Please note: If you talent matches one or more openings in the current openings section above, we recommend applying directly to those openings to increase your chances of a speedy review )

                
                </p>
                <p>
                
                
                </p>
            </div> 
            <div class="row contact-wrap col-lg-12"> 
                <div class="status alert alert-success" style="display: none" id="mailsendmsg"></div>
                <form id="main-contact-form" class="contact-form" name="contact-form" method="post" action="<?=$this->url().'page/carriermail';?>" autocomplete="off" enctype="multipart/form-data" >
                    <div class="col-sm-5 col-sm-offset-1">
                        <div class="form-group">
                            <label>Name *</label><br />
                            <div class="col-sm-6 applypagesm_6">
                            <input type="text" name="Fname" class="form-control"  placeholder="First Name">
                            <span class="showerror"></span>
                        </div>
                            
                            <div class="col-sm-6 applypagesm_6">
                            <input type="text" name="Lname" class="form-control"  placeholder="Last Name">
                            <span class="showerror"></span>
                        </div>
                        </div>
                        <div class="form-group">
                            <label>Email *</label>
                            <input type="email" name="email" id="contactemail" class="form-control" >
                            <span class="showerror"></span>
                        </div>
                        <div class="form-group">
                            <label>Phone</label>
                            <input type="number" class="form-control" id="contactnumber" name="ph_no">
                            <span class="showerror"></span>
                        </div>
                                                
                    </div>
                    <div class="col-sm-5">
                    <div class="form-group">
                            <label>Post</label>
                            <select class="form-control" name="applied_post">
                          <option value="">Which Department are you applying to</option>
				<option value="Research & Development">Research & Development</option>
		<option value="Quality Control & Assurance">Quality Control & Assurance</option>
		<option value="Manufacturing & Plant Operations">
			Manufacturing & Plant Operations</option>
		<option value="Marketing & Advertising">Marketing & Advertising</option>
		<option value="Branding & Creative">Branding & Creative</option>
		<option value="Administration">Administration</option>
		<option value="Finance">Finance</option>
		<option value="Human Resource">Human Resource</option>
		<option value="Information Technology">Information Technology</option>
		<option value="Management">Management</option>
                            </select>
                            <span class="showerror"></span>
                          
                        </div>
                    
                        <div class="form-group">
                            <label>Corvering Letter *</label>
                            <input type="text" name="subject" class="form-control" >
                            <span class="showerror"></span>
                        </div>
                        <div class="form-group">
                            <label>Upload Resume *</label>
                            <input name="Upload Resume" type="file" id="filesUp" size="500kb" class="form-control" />
                            <span class="showerror"></span>
                            <spam class="small">Only .doc, .docx & .pdf files of 2mb or less are allowed</samp>
                        </div>                        
                        <div class="form-group">

                            <button type="submit" name="submit" class="btn btn-primary btn-lg" >Submit</button>
                        </div>
                    </div>
                </form> 
            </div><!--/.row-->
        </div><!--/.container-->
    </section>