<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Area Sales Manager</strong></h2><br>

                <strong>Position : - Area Sales Manager </strong><br>

                 <strong>Exp:-  2+ Years</strong><br />
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a><br />
                </p>
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
             
              <p>
               
              <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; line-height: 120% }  		a:link { so-language: zxx }  	--><u><strong>Desired  Skills</strong></u> </p>
<p align="left">•   Analytical  skill set, strong presentation skills, ability to interact with any  level within an organization              </p>
              <p align="left">•   Ability  to self-motivate and multi-task and </p>
              <p align="left"> work  independently or within a team              </p>
              <p align="left">•  Outstanding  Written and Verbal Communication Skills              </p>
              <p align="left">•   Well-Developed  Interpersonal Skills and Professional Demeanor              </p>
              <p align="left"><strong>Job  Responsibility:</strong></p>
              <ul>
                <li>
                  <p align="left">Maintaining  	and increasing sales of your company's products </p>
                <li>
                  <p align="left"> Reaching  	the targets and goals set for your area </p>
                <li>
                  <p align="left"> Establishing,  	maintaining and expanding your customer base </p>
                <li>
                  <p align="left"> Servicing  	the needs of your existing customers </p>
                <li>
                  <p align="left"> Increasing  	business opportunities through various routes to market </p>
                <li>
                  <p align="left"> Developing  	sales strategies and setting targets </p>
                <li>
                  <p align="left"> Monitoring  	your team's performance and motivating them to reach targets </p>
                <li>
                  <p align="left"> Compiling  	and analysing sales figures </p>
                <li>
                <p align="left"> Possibly  	dealing with some major customer accounts yourself </p>                
              </ul>
              <p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>