<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Business Development</strong></h2><br>

                <strong>Position : - Business Development </strong><br>

                 <strong>Exp:-  2+ Years</strong><br />
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->                
              <p>
              
              <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; line-height: 120% }  		a:link { so-language: zxx }  	--> <strong>Skills   &amp; Responsibilities:              </strong></p>
              <ul>
                <li>
                  <p align="left"> Promoting  	and marketing the business, sometimes to new or niche markets</p>
                <li>
                  <p align="left"> Identifying  	new sales leads </p>
                <li>
                  <p align="left"> Pitching  	products and/or services </p>
                <li>
                  <p align="left"> Maintaining  	fruitful relationships with existing customers </p>
                <li>
                  <p align="left"> Contacting  	potential clients via email or phone to establish rapport and set up  	meetings </p>
                <li>
                  <p align="left">Planning  	and overseeing new marketing initiatives</p>
                <li>
                  <p align="left">Call,  	meet and present proposals about our services</p>
                <li>
                  <p align="left"> Achieve  	annual sales targets with travel support staf</p>
                <li>
                  <p align="left"> Achieve  	efficient cost of sale through optimising sales channel mix and  	spend</p>
                <li>
                  <p align="left"> Continually  	review and act to improve on the customer journey through sale  	partners and agents</p>
              </ul>
              <p align="left"> Communicate  sales channel position vs plan, highlighting areas of risk and  opportunity against sales and cost of sales budgets to drive trading  focus at channel and sales account level</p>
<p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>