<?php //echo $id=$_REQUEST['id']; ?>

<style>
.scrollbar{
width:100%;
height:80px;
background-color:;
overflow-y:scroll;
float:left;
}

#ex3::-webkit-scrollbar{
width:16px;
background-color:#cccccc;
} 

#ex3::-webkit-scrollbar-thumb{
background-color:#333;
border-radius:10px;
}
#ex3::-webkit-scrollbar-thumb:hover{
background-color:#BF4649;
border:1px solid #333333;
}
#ex3::-webkit-scrollbar-thumb:active{
background-color:#A6393D;
border:1px solid #333333;
} 


#ex3::-webkit-scrollbar-track{
border:1px gray solid;
border-radius:10px;
-webkit-box-shadow:0 0 6px gray inset;
} 

</style>

<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>
    
    <section id="recent-works">
        <div class="container">
            <div class="center wow fadeInDown">
                <h2>Career
                <span class="small"><br />
				all open positions 
</span>
                </h2>
                
            </div>


            <div class="row fadeInDown rowbranding" align="center">
                <div class="col-xs-12 col-sm-4 col-md-4 homefrature fadeInDown">
                    <div class="recent-work-wrap" style="border:1px solid #ccc;">
                        <img class="img-responsive" src="<?php echo $this->basePath();  ?>/public/careers/administration.png" alt="" style="height:147px !important">
                        <div class="overlay">
                            <div class="recent-work-inner" align="">
                                <h3><a href="#">Administration</a> </h3>
                                <div class="scrollbar" id="ex3">
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/admin">HR & Admin</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/admin">Delhi</a></span>
                                
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/reception">Receptionist</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/reception">Delhi</a></span>
                               
                               
                                
                           </div>
                               
                            </div> 
                        </div>
                    </div>
                    <div class="recent-work-wrap">
                   <h3><strong> Administration </strong></h3>
                    </div>
                    
                </div>   

                <div class="col-xs-12 col-sm-4 col-md-4 homefrature">
                    <div class="recent-work-wrap" style="border:1px solid #ccc;">
                        <img class="img-responsive" src="<?php echo $this->basePath();  ?>/public/careers/finance.png" alt=""  style="height:147px !important">
                        <div class="overlay">
                            <div class="recent-work-inner" align="">
                                <h3><a href="#">Finance</a></h3>
                                
                                <div class="scrollbar" id="ex3">
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/accountant1">Accountant</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/accountant">Delhi</a></span>
                                
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/accountant">Sr Accountant</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/accountant">Delhi</a></span>
                               
                               
                                
                           </div>
                                
                            </div> 
                        </div>
                    </div>
                    
                     <div class="recent-work-wrap">
                   <h3><strong> Finance</strong> </h3>
                    </div>
                </div> 

                <div class="col-xs-12 col-sm-4 col-md-4 homefrature">
                    <div class="recent-work-wrap" style="border:1px solid #ccc;">
                        <img class="img-responsive" src="<?php echo $this->basePath();  ?>/public/careers/research-development.png" alt=""  style="height:147px !important">
                        <div class="overlay" style="border:1px solid #ccc;">
                            <div class="recent-work-inner" align="">
                                <h3><a href="#">IT </a></h3>
                               <div class="scrollbar" id="ex3">
                                <!--<span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/job">UI Designer</a></span> <span class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></span>-->
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/webdesigner">Web Designer</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/webdesigner">Delhi</a></span>
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/android">Android Developer</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/android">Delhi</a></span>
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/ios">IOS Developer</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/ios">Delhi</a></span>
                              
                                <!--<span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/job">PHP Developer</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/job">Delhi</a></span>-->
                                 <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/srphpdev">Sr. PHP Developer</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/srphpdev">Delhi</a></span>
                                 <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/phpdev">PHP Developer</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/phpdev">Delhi</a></span>
                            
                                
                           </div>
                                
                            </div> 
                        </div>
                    </div>
                     <div class="recent-work-wrap">
                   <h3><strong>IT</strong> </h3>
                    </div>
                </div>   

                <div class="col-xs-12 col-sm-4 col-md-4 homefrature">
                    <div class="recent-work-wrap" style="border:1px solid #ccc;">
                        <img class="img-responsive" src="<?php echo $this->basePath();  ?>/public/careers/branding-and-creative.png" alt=""  style="height:147px !important">
                        <div class="overlay">
                            <div class="recent-work-inner" align="">
                                <h3><a href="#">Marketing </a></h3>
                               <div class="scrollbar" id="ex3">
                                <dev class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/businessdevelopment">Business Development</a></dev> <dev class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></dev>
                                <dev class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/salesexqutive">Sales Exqutive</a></dev> <dev class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/salesexqutive">Delhi</a></dev>
                                <dev class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/manager">Area Sales Manager</a></dev> <dev class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></dev>
                                <dev class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/digitalmarketing">Digital Marketing</a></dev> <dev class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></dev>
                                <dev class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/manager">Marketing Manager</a></dev> <dev class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></dev>
                                <dev class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/regionalsalesmanager">Reginol Marketing Manager</a></dev> <dev class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></dev>
                                 
                            
                                
                           </div>
                            </div> 
                        </div>
                    </div>
                     <div class="recent-work-wrap">
                   <h3><strong>Marketing</strong> </h3>
                    </div>
                </div>   
                
                <div class="col-xs-12 col-sm-4 col-md-4 homefrature">
                    <div class="recent-work-wrap" style="border:1px solid #ccc;">
                        <img class="img-responsive" src="<?php echo $this->basePath();  ?>/public/careers/marketing-advertising.png" alt=""  style="height:147px !important">
                        <div class="overlay">
                            <div class="recent-work-inner" align="">
                                <h3><a href="#">Operation Department </a></h3>
                              <div class="scrollbar" id="ex3">
                                 <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="#">Callers</a></span> <span class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></span>
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="#">Dispatcher</a></span> <span class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></span>
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/teamleader">Team Leader</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/teamleader">Delhi</a></span>
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/vendor">Vender Manager</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/vendor">Delhi</a></span>
                               
                                 
                            
                                
                           </div>
                               
                            </div> 
                        </div>
                    </div>
                    
                     <div class="recent-work-wrap">
                   <h3><strong> Operation Department  </strong></h3>
                    </div>
                </div>   

                <div class="col-xs-12 col-sm-4 col-md-4 homefrature">
                    <div class="recent-work-wrap" style="border:1px solid #ccc;">
                        <img class="img-responsive" src="<?php echo $this->basePath();  ?>/public/careers/quality-control.png" alt=""  style="height:147px !important">
                        <div class="overlay">
                            <div class="recent-work-inner" align="center" style="margin-top:20px;">
                                <h3><a href="#">Quality Control</a></h3>
                                <div class="scrollbar" id="ex3">
                                  <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="<?php echo $this->basePath(); ?>/index/page/quailtyanalyst">Quailty Analyst</a></span> <span class="col-sm-4 col-sm-4career"><a href="<?php echo $this->basePath(); ?>/index/page/quailtyanalyst">Delhi</a></span>
                                <!--<span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="#">Callers</a></span> <span class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></span>
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="#">Dispatcher</a></span> <span class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></span>
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="#">Teaqm Leader</a></span> <span class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></span>
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="#">Vender Manager</a></span> <span class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></span>
                                <span class="col-sm-8 col-sm-8career" style="text-align:left;"><a href="#">Digital Marketing</a></span> <span class="col-sm-4 col-sm-4career"><a href="#">Delhi</a></span>-->
                            
                                
                           </div>
                            </div> 
                        </div>
                    </div>
                    
                     <div class="recent-work-wrap">
                   <h3><strong> Quality Control</strong> </h3>
                    </div>
                </div> 
  
            </div>
        </div>
    </section>
    
    