<?php //echo $id=$_REQUEST['id']; ?>


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Android Developer</strong></h2>
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:
     <br />
    
Job Description<br />

 
Send me Jobs like this<br />


    Walk In On 23 Feb 2016 & 24 Feb 2016 for Android Developer and Java Developer also.<br />


    Walk In Time : 10:00 am To 1:00 pm<br />


    If you think you are suitable candidate then please come for interview on mentioned date and time.<br />


    Senior Android Developer: 3 to 4 years<br />

    Junior Android Developer: 1 to 2 years<br />


    Job Description:<br />


    - Developing serious Android apps / solutions<br />

    - Writing high quality and optimized code<br />

    - Contribute in Architecture / Designing solutions<br />

    - Keep on upgrading on new technologies / frameworks in Android<br />


    Desired Skills<br /><br />


        Should have working knowledge and experience in Android Mobile Application Development. Expected skill sets.<br />

        Should have experience on J2EE as Android is built on Standard Java 2 Standard Edition with a new API and structure for the applications<br />

        Should be familiar with Android framework - activities, services, related life cycles, intents, content providers, broadcast receivers, etc.<br />
ss
        Should know about multi-threading and thread synchronization<br />
<br />

        Exposure to necessary optimization techniques for mobile devices with limited battery life (reduce number of instruction cycles, minimize memory access, don't leak any resources, etc)<br />
<br />

        Should have knowledge of XML and JSON a requirement<br />
<br />

        Should have Knowledge of Sql Lite and a working experience in SQL databases<br />
<br />

        Should be self disciplined to follow coding standards, organizational programming skills and good commenting practices

    We have another requirement also: Java Developer<br />

    Experience :- 2 to 3 Years<br />
<br />


        Understanding and experience in J2EE 1.5 and 1.6 overall concepts.<br />

        Candidate should have minimum 1.5 to 2 years of experience in Java development and Coding.<br />

        Hands on experience in Tomcat, Resin and Open Source Platforms.<br />

        Hands on experience in any web application servers, preferably tomcat / resin.<br />

        Strong in db and validating the queries and performance issues. <br />

        Hands on experience in javascript with JSON and Jquery or backbone with underscore. <br />

        MVC framework such as Mustache experience is an advantage. <br />

        Working knowledge on MySQL Database Server, including triggers, functions and procedures. <br />

        Capability to consume web services and troubleshoot the xml request responses.<br />

        Good understanding of performance testing of web services.<br /><br />


        Candidate will need to have experience in Core Java ( Java certification would be a definite plus.) OOPS, Multi- threading, Collections, J2EE, Spring, hibernate.
        Very good in communication and client interacting capabilities.<br />


Salary: Not Disclosed by Recruiter<br />


Industry: IT-Software / Software Services<br />


Functional Area: IT Software - Application Programming , Maintenance<br />


Role Category:Programming & Design<br />


Role:Software Developer<br />
<ul>
	<li>

Keyskills
</li>
 <li>
Java
</li>

<li>
J2Ee
</li>

Android
<li>
XML
</li>

<li>
Mobile Application Development
</li>
<li>
SQL
</li>
<li>
JSON
</li>
<li>
Multithreading
</li>
<li>
Architectural Design
</li>
<li>
android developer android application developer gps and geo coding gis and geo coding sqlite database
</li>
<li>
Web Services
</li>
<li>
Java Developer
</li>
Desired Candidate Profile

Education-

UG: Any Graduate, B.Tech/B.E., Diploma, B.Sc, BCA

PG:Post Graduation Not Required, MCA, M.Sc

Doctorate:Doctorate Not Required

    Please refer to the Job description above 

Company Profile:
     
<br />
           
                

( Please note: If you talent matches one or more openings in the current openings section above, we recommend applying directly to those openings to increase your chances of a speedy review )
                
                </p>
            </div> 
          
        </div><!--/.container-->
    </section>