<?php //echo $id=$_REQUEST['id']; ?>



<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/contact-us.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="contact-info">
        <div class="center">                
            <h2><strong>How to Reach Us?</strong></h2>
           <!-- <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>-->
        </div>
        <div class="gmap-area">
            <div class="container">
                <div class="row">
                    <div class="col-sm-5 text-center">
                        <div class="gmap">
                           <iframe width="100%" height="350" frameborder="0" src="https://maps.google.com/maps/ms?msa=0&msid=211001950410036316718.0004df15470c207210920&ie=UTF8&ll=28.651993,77.194748&spn=0,0&t=m&output=embed" marginwidth="0" marginheight="0" scrolling="no"></iframe>
                        </div>
                    </div>

                    <div class="col-sm-7 map-content">
                        <ul class="row">
                            <li class="col-sm-6">
                                <address>
                                    <h5>Head Office</h5>
                                    <p> 	29 -30, D.B Gupta Market, <br>
                                    Karol Bagh New Delhi - 110005 (INDIA)
                                    </p>
                                    <p>Phone: +91-11-424 242 42<br>
                                    Email Address: feedback@hello42cab.com</p>
                                 
                                </address>

                                
                            </li>


                            <li class="col-sm-6">
                               

                                
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <section id="contact-page">
        <div class="container">
            <div class="center col-lg-12">        
                <h2><strong>Drop Your Message</strong></h2>
                <p class="lead">Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div> 
            <div class="row contact-wrap col-lg-12"> 
                <div class="status alert alert-success" style="display: none" id="mailsendmsg"></div>
                <form id="main-contact-form" class="contact-form" name="contact-form" method="post" action="<?=$this->url().'page/sendmail';?>" >
                    <div class="col-sm-5 col-sm-offset-1">
                        <div class="form-group">
                            <label>Name *</label>
                            <input type="text" name="name" class="form-control" >
                            <span class="showerror"></span>
                        </div>
                        <div class="form-group">
                            <label>Email *</label>
                            <input type="email" name="email" class="form-control" id="contactemail">
                            <span class="showerror"></span>

                        </div>
                        <div class="form-group">
                            <label>Phone</label>
                            <input type="number" name="ph_no" id="contactnumber" class="form-control">
                            <span class="showerror"></span>

                        </div>
                        <div class="form-group">
                            <label>Company Name</label>
                            <input type="text" name="Company_name" class="form-control">
                            <span class="showerror"></span>

                        </div>                        
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group">
                            <label>Subject *</label>
                            <input type="text" name="subject" class="form-control" >
                            <span class="showerror"></span>

                        </div>
                        <div class="form-group">
                            <label>Message *</label>
                            <textarea name="message" id="message"  class="form-control" rows="15" style="height:129px !important;"></textarea>
                            <span class="showerror"></span>

                        </div>                        
                        <div class="form-group">
                            <button type="submit" name="submit" class="btn btn-primary btn-lg">Submit Message</button>
                        </div>
                    </div>
                </form> 
            </div><!--/.row-->
        </div><!--/.container-->
    </section>
    
    
    