<?php //echo $id=$_REQUEST['id']; ?>



<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/copyright.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container">
            <div class="center col-lg-12">        
                <h2 align="left"><strong>Copyright</strong></h2>
                <p class="" align="justify">All content, logo, domain on this web site is the copyright of Hello42 except the third party content and link to third party web site on our website. Any other website shall not be initial to copy the content from the Hello42 website. 
<br />
<br />
<strong>CONSENT TO ELECTRONIC COMMUNICATIONS AND TRANSACTIONS</strong><br />

By clicking the 'I Agree' button, user agreed for any information, communication, and notice, from us electronically, whether sent by e-mail or other electronic means. All the electronic communication between the user and company will be mutually agreed by both.
<br />
<br />
<strong>Disclaimer</strong><br />
 
Hello42cab.com disclaims all warranties of merchantability, relating to the information and description of the cab/taxi, car rental or any other product or service displayed on this website (including, without limitation, the pricing, photographs, list of amenities, general product descriptions, etc.), much of which information is provided by the respective suppliers/operators. Car or any other ratings displayed on this website are intended as only general guidelines, and hello42cab.com, bookingcabs.com and other domain of Hello42 Affiliates and their respective suppliers do not guarantee the accuracy of the ratings. Hello42cab.com, its Affiliates and their respective suppliers make no guarantees about the availability of specific products and services
<br />
<br />
The customer agrees and acknowledges that the use of the Mobile App/Website/CC is at the sole risk of the customer and that Company disclaims all representations and warranties of any kind, whether express or implied as to condition, suitability, quality and fitness for any purposes are excluded to the fullest extent permitted by law. 
<br />
<br />
The information contained in this Website / Application is for general information purposes only. The information is provided by Hello42 and while we endeavor to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk. 
<br />
<br />
In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arise out of, or in connection with, the use of this website. 
<br />
<br />
Through this website you are able to link to other websites which are not under the control of Hello42. We have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them. 
<br />
<br />
Every effort is made to keep the Website / Application/CC up and running smoothly. However, Hello42 takes no responsibility for, and will not be liable for, the Website / Application/CC being temporarily unavailable due to technical issues beyond our control. 
                
                </p>
            </div> 
          
        </div><!--/.container-->
    </section>
    