<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Digital Marketing</strong></h2><br>

                <strong>Position : - Digital Marketing </strong><br>

                 <strong>Exp:-  2+ Years</strong><br />
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->                
              <p>
                <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
              <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; line-height: 120% }  		a:link { so-language: zxx }  	-->
              <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
              <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; line-height: 120% }  		a:link { so-language: zxx }  	-->
              <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
              <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; line-height: 120% }  		a:link { so-language: zxx }  	-->
              <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"> <strong>Job   Description:-</strong></p>
<p align="left"> ·	Plan  and execute all web, SEO/SEM, marketing database, email, social media  and display advertising campaigns</p>
              <p align="left"> ·	Design,  build and maintain our social media presence</p>
              <p align="left"> ·	Measure  and report performance of all digital marketing campaigns, and assess  against goals (ROI and KPIs)</p>
              <p align="left"> ·	Identify  trends and insights, and optimize spend and performance based on the  insights</p>
              <p align="left"> ·	Brainstorm  new and creative growth strategies</p>
              <p align="left"> ·	Plan,  execute, and measure experiments and conversion tests</p>
              <p align="left"> ·	Collaborate  with internal teams to create landing pages and optimize user  experience</p>
              <p align="left"> ·	Utilize  strong analytical ability to evaluate end-to-end customer experience  across multiple channels and customer touch points</p>
              <p align="left"> ·	Instrument  conversion points and optimize user funnels</p>
              <p align="left"> ·	Collaborate  with agencies and other vendor partners</p>
              <p align="left"> ·	Evaluate  emerging technologies. Provide thought leadership and perspective for  adoption where appropriate</p>
              <p align="left"> <strong>Skills:-</strong>              </p>
              <p align="left"> ·	Proven  working experience in digital marketing</p>
              <p align="left"> ·	Demonstrable  experience leading and managing SEO/SEM, marketing database, email,  social media and/or display advertising campaigns</p>
              <p align="left"> ·	Highly  creative with experience in identifying target audiences and devising  digital campaigns that engage, inform and motivate</p>
              <p align="left"> ·	Experience  in optimizing landing pages and user funnels</p>
              <p align="left"> ·	Experience  with A/B and multivariate experiments</p>
              <p align="left"> ·	Solid  knowledge of website analytics tools (e.g., Google Analytics,  NetInsight, Omniture, Web Trends)</p>
              <p align="left"> ·	Working  knowledge of ad serving tools (e.g., DART, Atlas)</p>
              <p align="left"> ·	Experience  in setting up and optimizing Google Ad words campaigns</p>
              <p align="left"> ·	Working  knowledge of HTML, CSS, and JavaScript development and constraints</p>
              <p align="left"> ·	Strong  analytical skills and data-driven thinking</p>
              <p align="left"> ·	Up-to-date  with the latest trends and best practices in online marketing and  measurement              </p>
              <p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>