<?php //echo $id=$_REQUEST['id']; ?>



<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/blog.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container">
            <div class="col-lg-12" align="left">        
                <h2><strong>Documentation</strong></h2>
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:
     <br />
<br />
           
                

( Please note: If you talent matches one or more openings in the current openings section above, we recommend applying directly to those openings to increase your chances of a speedy review )
                
                </p>
            </div> 
          
        </div><!--/.container-->
    </section>