<?php //echo $id=$_REQUEST['id']; ?>


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/faq.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container">
            <div class="col-lg-12" align="left">        
                <h2><strong>FAQ</strong></h2>
                <p class="" align="justify"><strong>Cancellations Related</strong> <br />

Q: Can I change my booking?<br />

A: Yes. You can change the date of booking till 1 day before the booked date free of charge in case of Cab ( P to P Booking) or other services check the cancelation respectively. After that, there will be a cancellation charge as detailed in the next question. 
<br />
<br />

Q: How do I cancel my booking? What are the charges?
<br />
A: You can cancel your booking anytime through Call center, Mobile Application and Website. The cancellation charges are as follows:
<br />
48 hours before booked time: No Charge
<br />
24  hours before booked time: Min 15% of the booking charges
<br />
0 - 24 hours before booked time: Min 25% of the booking charges. May Vary on Cancelation as per services provided by other Vendors & TSP.
<br />
<br />
<strong>About Our Services</strong><br />

Q. What are the services offered by Hello42?
<br />
Hello42 offers a reliable metered taxi service in Delhi through a fleet of modern, air conditioned cars equipped with state-of-the-art GPS based communication technology. The service is backed by a 24x7 Customer Contact Center.
<br />
<br />
Q. What are the timings for the Hello42 Service?
<br />
Hello42 Services are available round the clock with best services.
<br />
<br />
Q. How do I book a Hello42 Cab?
<br />
You can book a Hello42 either through Phone or hello42 Mobile Application or Website. • To book through phone please call 011-42424242 Delhi NCR. To book Hello42 instantly on Hello42 Mobile Application by download it on Android & iPhone • To book a Hello42 through the website, visit our home page: www.hello42cab.com/www.bookingcabs.com.
<br />
<br />
Q. Can I hail a Hello42 cab on the road?
<br />
Hello42 Cab can only be booked in advance thru CC or website or Mobile App You can`t book if the Cab is  travelling to another assigned pick up.
<br />
<br />
Q. Is there a charge for booking on the phone / web?
<br />
No, there is no 'Convenience Charge' for booking a Hello42 either you book through our mobile application and website. The charges may Applicable if Booking thru Call Centre.  
<br />
<br />
Q. Will I be charged for waiting time also?
<br />
Yes, there are waiting charges while meter is flagged on of the respective cities. User will get some relaxation while waiting for certain time after that it will be chargeable for users. 
<br />
<br />
Q. Do I have to pay toll charge when I travel through Hello42?
<br />
Yes, you will be paying 'Toll charge', state charges, service tax- at the actual, when you are crossing the toll post while travelling through Hello42.
<br />
However, in case you have booked a Hello42 & the cab is crossing the toll post while coming to pick you up, then you need not pay the toll charges.
<br />
<br />
Q. How do I pay after the completion of my trip?
<br />
You can pay the chauffeur in cash or in Advance on Mobile App / Website by debit/credit card (VISA/Master Card/ AMEX) or thru wallet as per the fare on the meter with extras if any (for waiting, pre-waiting night surcharge, service tax) and a printed receipt / e-receipt for the same will be given to you. If you have any complaint & feedback, please fill up our client feedback form - this will help us to resolve your problem quickly.
<br />
<br />
Q. Will I get a printed receipt for the amount paid?
<br />
Always, please insist on it. Our chauffeurs are trained to give the receipt for every fare they collect. If by oversight this is missed, please ask for a receipt. All the receipt will be send on your registered e-mail ID.
<br />
<br />
Q. Can I pay using a debit or a credit card?
<br />
Yes, you can pay the fare charges by your debit or credit card as well. We accept all VISA, Master Card for payment. This facility is available on our mobile application and website.
<br />
<br />
Q. Can I use the cab without flagging down the meter?
<br />
We track every fare that the Hello42 cab is taking at our Technology Center and actively dissuade our chauffeurs from taking an un-metered fare. An un-metered fare is in violation of the Department of Transport rules and exposes the chauffeur to penal action. 
<br />
Moreover, if you have a complaint against the chauffeur, you would not have a valid printed receipt / e-receipt at the end of your journey to make a valid complaint.
<br />
<br />
Q. What do I do if I have left something behind in a Hello42?
<br />
Please call our Customer Service Center at 011 42424242 for Delhi and give us the details of the cab number, date and time of travel (all this information is there on your printed fare receipt / e-receipt) and we will help you track down your missing item. Hello42 chauffeurs are trained to report items left behind in a cab. So if you tell us the details of your commute, it makes it easy for us to link you with your missing item!
<br />
<br />
Q. Can I cancel a booking made?
<br />
Our system of handling bookings is automated and once your booking is confirmed by our Customer Service Center, a cab is assigned to report to you. We do understand that sometimes, plans change and you may need to cancel a booking. Please tell us as soon as you reasonably can - that you would like to cancel a booking so that we can avoid a Hello42 reporting to you, when you don't need it.
<br />
<br />
Q. In which cities is the Heloo42 Service currently available?
<br />
The Hello42 cab service is now available in Delhi. We expect to start operations in other major cities soon.
<br />
<br />
<strong>About Convenience Charge</strong>
<br />
Q. Are there any additional booking charges? 
<br />
No, if you book a Hello42 by through our call centre, mobile application and website in the cities of Delhi, then a Convenience Charge will not be applicable over & above your fare charge. 

<br />
<br />
Q. What are the charges that I have to pay if I book a Hello42 cab by calling Hello42 Call Center?
<br />
Apart from fare charges, No additional charges are applicable for Hello42 whether user book the cab through call center, mobile application and website. 
<br />
<br />
<strong>About Our Website</strong>
<br />
<br />
Q. Do I need to register at your website to avail the Hello42 service? 
<br />
No, it's not compulsory to registered with the Hello42 to avail the cab services, user can book the cab as a Guest user or Registered User but if user are registered with the hello42 will get the extra benefit while booking the cab.  
<br />
<br />
Q. I am a registered user and have forgotten my password!
<br />
If you are a registered user, please enter your correct login id i.e. your registered "Mobile Number/Email Id" and "Password". If you have forgotten your password, please click on "Forget password" link next to log in window on home page. Enter your user id (i.e. your email id) then click on "Submit" button. We will send your password via email.
<br />
<br />
Q. I am not able to login!
<br />
Please call us at 42424242 for Delhi. Please use the city specific STD code and we will try to connect you with our website Hello42 so that you can avail best services.
<br />
<br />
<strong>Rental Structure</strong>
<br />
Q. Airport / Railway station transfer: 
<br />
Here you need to be picked from airport/railway station and dropped somewhere within the pickup city or picked somewhere within the pickup city and dropped to the airport/railway station. We offer flat rates within city limits.
<br />
<br />
<strong>Local Trip / Within City use:</strong> 
<br />
Here you need the car to visit places within the city limits of the pickup city. The car service is provided for different packages like 4hrs/40 km, 8hrs/80km, and 12hrs/120 km. Any extra hour and extra km is charged at the rate applicable for that car in that particular city. If the car is used beyond 10:00pm, then there is a driver allowance charged for that day.
<br />
<br />
<strong>Outstation Trip / Out of City use:</strong><br />

Here you need the car to visit the places outside the picked city. There is a driver allowance charged for each day when the car is used for outstation travel. For every city from where the trip started there is a fixed km per day after that customer need to pay for extra km as per the rate applicable. One big difference between Local and Outstation trips is that in Outstation trips, the car is available for the entire calendar day and the costing is based only on kms usage.
<br />
<br />
<strong>General</strong><br />

What are the advantages you would get renting a car from us? 
<br />
We provide quality car rental services at competitive rates. We have friendly and efficient staff to help. All our cars are well maintained and are driven by chauffeurs who are highly experienced and courteous.
<br />
Currently, we provide services in Delhi/NCR city, soon we are covering all the cities in INDIA
<br />
How do we ensure privacy and security of your credit card? 
<br />
For on-road safety, we provide cars which are less than 2 years, clean, well maintained cars and hire only courteous and experienced chauffeurs well versed with regional routes. Our Chauffeurs are reliable, and trained to drive safely; so, you can feel relaxed and comfortable about your safety while riding one of our rental cars.
<br />
How is the itinerary confirmation provided? 
<br />
The moment user enters the payment details and makes the payment; the confirmation page shows the Reference ID which can be used for any future references. Also, a confirmation mail is sent for your record to the email address provided immediately with the details of the itinerary.
<br />
What if the plan changes and the car is needed for extra days or the trip needs to be cancelled or shortened? 
<br />
We understand that the trip plan can change and in the event that the car is needed for more time/days than what the car was booked for or the trip is to be cancelled or shortened, you can contact our 24x7 customer support through email or phone as mentioned in the confirmation voucher.

<br />
<br />
<strong>When is the driver and car detail provided?</strong><br />

The driver and car detail is provided at least 45 Min  before the scheduled pickup in email and through SMS. The email and SMS are provided by you at the time of making the booking. We always try to give the details of Driver in Advance subject to available .
                
                </p>
            </div> 
          
        </div><!--/.container-->
    </section>