<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>IOS Developers</strong></h2><br>

                <strong>Position : - IOS Developers </strong><br />
                <strong>Exp:-  2+  Years</strong><br />
                <strong>Job Location: Delhi (Karol Bagh)</strong><br />
               <strong>Date Posted: 23-03-2016</strong><br /><br />

               <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />

    
    <strong>Job Brief</strong><br />


        We are looking for an IOS Developer who possesses a passion for pushing
mobile technologies to the limits and will work with our team of talented
engineers to design and build the next generation of our mobile applications.
<br />
<br />
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  		a:link { color: #0000ff; so-language: zxx }  	-->
<p> <strong>Responsibilities  :</strong><br>
  <br>
  Design and build advanced app features for the iOS  platform<br>
  Collaborate with cross-functional teams to define,  design, and ship new features.<br>
  Unit-test code for robustness,  including edge cases, usability, and general reliability.<br>
  Work on  bug fixing and improving application performance.<br>
  Continuously  discover, evaluate, and implement new technologies to maximize  development efficiency.<br>
  <br>
  <strong>Ideal candidate profile:</strong><br>
  <br>
  BS/MS  degree in Computer Science, Engineering or a related subject<br>
  3+  years of software development experience<br>
  1+ years of iOS  development<br>
  Have published one or more iOS apps in the app store<br>
  A  deep familiarity with Objective-C, Swift and Cocoa Touch<br>
  Experience  working with iOS frameworks such as Core Data, Core Animation, Core  Graphics and Core Text<br>
  UI development with Interface Builder and  Code, including AutoLayout<br>
  Experience with third-party libraries  and APIs<br>
  Working knowledge of the general mobile landscape,  architectures, trends, and emerging technologies<br>
  Solid  understanding of the full mobile development life cycle<br>
  <br>
  <br>
  <u>Objective  C</u></p>
<p align="left"><u>Cocoa  Touch</u></p>
<p align="left"><u>IOS</u></p>
<p align="left"><u>Mobile  Development</u></p>
<p align="left"><u>Core  Data</u></p>
<p align="left"><u> Core Animation</u></p>
<p align="left"><u>Core  Graphics</u></p>
<p align="left"><u>Core  Text</u></p>
<p align="left"><u>IOS  Developer</u></p>

<p style=" float:right;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
            </div> 
          
        </div>
    </section>