<?php //echo $id=$_REQUEST['id']; ?>


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Android Developer</strong></h2><br />

                <strong>Job Location: Delhi</strong><br />
                 <strong>Date Posted: 19-02-2016</strong><br /><br />

               <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />

    
    <strong>Job Brief</strong><br />


        We are looking for an Android Developer who possesses a passion for pushing
mobile technologies to the limits and will work with our team of talented
engineers to design and build the next generation of our mobile applications.
<br />
<br />



    <strong>Resposbility</strong>

    <ul>
	<li>
    Design and build advanced applications for the Android platform
    </li>
    <li>
    Collaborate with cross-functional teams to define, design, and ship new features.
    </li>
    <li>
    Work with outside data sources and API's
    </li>
    <li>
    Unit-test code for robustness, including edge cases, usability, and general reliability.
    </li>
    <li>
    Work on bug fixing and improving application performance.
    </li>
    <li>
    Continuously discover, evaluate, and implement new technologies to maximize development efficiency.
</li>
</ul>
<br />


     <strong>  Requirements</strong><br />


       <ul>
       		<li>
    BS/MS degree in Computer Science, Engineering or a related subject
    </li>
    <li>
    Proven software development experience
    </li>
    <li>
    Proven working experience in Android development
    </li>
    <li>
    Have published at least one original Android app
    </li>
    <li>
    Experience with Android SDK
    </li>
    <li>
    Experience working with remote data via REST and JSON
    </li>
    <li>
    Experience with third-party libraries and APIs
    </li>
    <li>
    Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies
    Solid understanding of the full mobile development life cycle.

     </li>
       </ul>       
                

( Please note: If you talent matches one or more openings in the current openings section above, we recommend applying directly to those openings to increase your chances of a speedy review )
                
                </p>
                
                 <p style=" float:right;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
            </div> 
          
        </div>
    </section>