<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Manager</strong></h2><br>

                <strong>Position : - 
</strong><strong>Asst. Manager/  Manager/ Operation Manager (Cab)</strong>
       <strong> </strong><br>

                 <strong>Exp:- 2 to 9 Years+
                 </strong><br />
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->                
              <p><strong>Job  Description</strong></p>
              <ul>
                <li>
                  <p>He will be  	the in charge of all the working of HELLO42 Cabs.</p>
                <li>
                  <p>He will  	assist in the coordinating and motivating all the employ of the  	company.</p>
                <li>
                  <p>He will  	motivate members so that they meet deadlines, work productively, and  	resolve any issues effectually.</p>
                <li>
                  <p>He will be  	making the Daily report, Shift wise report, Duty Dispatched, Duty  	refused with reason,  Call Records, List of drivers, any complain  	during the working hours &amp; Daily work MIS with the help of all  	the team member.</p>
                <li>
                  <p>He will  	update in the MIS regarding Imposing of penalty on drivers for or  	against any complain.</p>
                <li>
                  <p>He will look  	after daily Log in &amp; Log out report of Drivers.</p>
                <li>
                  <p>He will  	follow up with the Drivers area wise.</p>
                <li>
                  <p>He will see  	the vehicle break down.</p>
                <li>
                  <p>He will be  	the in charge for checking &amp; updating the daily duty sheet.</p>
                <li>
                  <p>Checking the  	call records.</p>
                <li>
                  <p>Checking &amp;  	maintain the records of all the booked &amp; canceled cab.</p>
                <li>
                  <p>Making the  	credit duty bill month wise.</p>
                <li>
                  <p>Dividing the  	duty driver wise.</p>
                <li>
                  <p>Updating the  	director regarding daily income &amp; expenditure.</p>
                <li>
                  <p>Crosschecking  	the feedback call data.</p>
                <li>
                  <p>He will look  	for the reason for customer not picking the call after giving duty.</p>
                <li>
                  <p>He will  	check &amp; maintain the caller quality &amp; dispatcher quality.</p>
                <li>
                  <p>He will  	check the willingness &amp; motivation of work of drivers.</p>
                <li>
                  <p>Making shift  	wise roster.</p>
                <li>
                  <p>Handling  	Customer &amp; Drivers complains.</p>
                <li>
                  <p>Maintain the  	office decorum.</p>
              </ul>
              <p> <strong>Skills</strong></p>
              <ul>
                <li>
                  <p>Have  	excellent leadership and managerial skills.</p>
                <li>
                  <p>Must be  	computer literate, familiarity with Microsoft excel, word, and  	outlook. </p>
                <li>
                  <p>Ability to  	speak English reasonably well.</p>
                <li>
                  <p>Be able to  	make solid business decisions.</p>
                <li>
                  <p>Be  	professional, and positive.</p>
                <li>
                  <p>Have  	integrity, initiative and focus.</p>
                <li>
                  <p>Prior  	managerial experience.</p>
                <li>
                  <p>Be able to  	think, communicate and present information effectively.</p>
                <li>
                  <p>Have good  	coping skills.</p>
                <li>
                  <p>Be able to  	motivate self, team or staff.</p>
                <li>
                  <p>Be able to  	use computer or IT equipment proficiently.</p>
              </ul>
<p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>