<?php //echo $id=$_REQUEST['id']; ?>


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/partners.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>
    
    <section id="feature" >
        <div class="container">
          <div class="center wow col-lg-12 fadeInDown">
            <h2 align="left">Partners</h2>
               <p class="" align="justify">
               
               Hello42cab.com is a cab booking portal which enables consumers to book cabs online. It gives you a wide range of choices between chauffeur driven car rentals across India to suit your specific need whether it be an airport transfer, late night car hire, meeting, a road trip, outstation, intercity or just a special car on a special occasion such as an anniversary, birthday or even your marriage.
<br />
<br />
<strong>Why Partners joining us:-<br /></strong>

1. Hello 42 cabs services are cheaper than other radio taxi and car rental services.<br />

2. Quality is assured with each delivery.
<br />
3. Promise of on time execution.
<br /><br />

To partner with us: Drop a mail to contact@hello42cab.com


                </p>
               
   <br />

<!--<div class="row">
                <div class="partners">
                <ul>
                    <li> 
                    <div class="feature-wrap feature-wrapnew" align="center">
                            <i class="fa fa-check"></i><BR />
                            <h3>Traveler's Convenience</h3>
                           
                        </div>
                    
                    </li>
                    <li><div class="feature-wrap feature-wrapnew" align="center">
                            <i class="fa fa-lock"></i><BR />
                            <h3>Passenger's Safety</h3>
                           
                        </div></li>
                    <li><div class="feature-wrap feature-wrapnew" align="center">
                            <i class="fa fa-chevron-down"></i><BR />
                            <h3>Quality Ride</h3>
                           
                        </div></li>
                    <li> <div class="feature-wrap feature-wrapnew" align="center">
                            <i class="fa fa-inr"></i><BR />
                            <h3>Pricing Control</h3>
                           
                        </div></li>
                   
                </ul>
            </div>
            </div>-->

            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>