<?php //echo $id=$_REQUEST['id']; ?>



<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/privacy-policy.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container">
            <div class="center col-lg-12">        
                <h2 align="left"><strong>Privacy Policy</strong></h2>
                <p class="" align="justify">This privacy policy assures that the user information give to Hello42 will be protected while using Hello42 website.

<br />
<br />
Hello42 is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, and then you can be assured that it will only be used in accordance with this privacy statement.

<br />
<br />
Hello42 may change this policy from time to time by updating this page. You should check this page from time to time to ensure that you are happy with any changes. This policy is effective from 24th February 2016
<br />
<br />
<strong>What Hello42 collect:</strong><br />

We may collect the following information- 
<br />
Name and Details of your Tours.
<br />
Contact information including email address, Mobile No.
<br />
Demographic information such as postcode, preferences and interests.
<br />
Other information relevant to customer surveys and/or offers.
<br />
What Hello42 do with the information we gather:
<br />
We require this information to understand your needs and provide you with a better service, and in particular for the following reasons: 
Internal record keeping.
<br />
We may use the information to improve our products and services and retain the good relationship with our users.
<br />
We may periodically send promotional emails about new products, special offers, discounts  or other information which we think you may find interesting using the email address which you have provided.
<br />
Some time we may also use your information to contact you for market research purposes. We may contact you via email, phone calls and other mobile Notifications 
<br />
<br />
<strong>Security:</strong><br />

We are committed to ensuring that your information is secure. In order to prevent unauthorized access or disclosure we have put in place suitable physical, electronic and managerial procedures to safeguard and secure the information we collect online..
<br />
<br />
 If you have questions about this Privacy and Cookie Policy, please contact us    at support@hello42cabs.com
<br />
<br />
<strong>How we use cookies:</strong>
<br />
A cookie is a small file which asks permission to be placed on your computer's hard drive. Once you agree, the file is added and the cookie helps analyze web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.

<br />
<br />
We use traffic log cookies to identify which pages are being used. This helps us analyze data about webpage traffic and improve our website in order to tailor it to customer needs. We only use this information for statistical analysis purposes and then the data is removed from the system.

<br />
<br />
Overall, cookies help us provide you with a better website, by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us.

<br />
<br />
You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website.
<br />
<br />
<strong>Contacting Us:</strong><br />

If there are any questions regarding this privacy policy you may contact us using the information below: 
<br />
<br />

Company Name: Hello42 cab India Pvt. Ltd
<br />
Address:    29 -30, D.B Gupta Market, Karol Bagh, New Delhi-
<br />
Telephone No. : +91-011-42424242
<br />
E-Mail ID: support@hello42cab.com
<br />
<br />
<strong>Referral Scheme T&C:-</strong><br />

1. The free ride coupons are applicable on economy, Sedan and Prime rides only. <br />

2. The coupon is applicable on one ride only. 
<br />
3. Any user who signs-up a referral code will get a coupon worth the value of the referral program at the time of sign-up. These values may change if our referral program changes during the sign-up. 
<br />
a. You too will receive free ride coupons depending on the referral program that is running when your friend signs-up once he/she completes the first ride. 
<br />
4. When you sign-up with a referral code, you earn a first ride coupon. The coupon will expire if not applied on the first ride. 
<br />
5. When your friend signs up with your code and takes the first ride, you earn a free ride coupon, which can be applied on any ride before the coupon expires. 
<br />
6. If your bill amount is less than your coupon amount, your free ride coupon will be fully used. 
<br />
7. Hello42 reserves the right to revoke the free ride coupons or suspend your account at any time if we feel that the account is being misused or that our referral program is being violated. 
<br />
8. No refund, either in the form of coupons or Hello42 Money, will be issued for free ride coupons. 
<br />
9. Hello42 reserves the right to change the referral scheme at any time. 
<br />
10. Multiple accounts with your email address, fake email IDs, manipulated devices, usage of fake locations , jail broken devices or an equivalent of that is a violation of our policy and can render your account invalid for any referral, promotional scheme or usage of our service. 
                
                </p>
            </div> 
          
        </div><!--/.container-->
    </section>