<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Quailty  Analyst</strong></h2><br>

             <strong>Position : - <span class="lead">Quailty  Analyst</span></strong><br>

                 <strong>Exp:-  2+ Years</strong><br />
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">
                  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
                  <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  		a:link { color: #0000ff; so-language: zxx }  	-->
                QA  Analyst will be responsible for testing both manually and with  automated tools. Looking for QA Analyst, Able to understand software,  debug problems, and write automated test scripts and user-level  automated tools.<br>
                  <br>
                  As  an engineering resource, you will work on new challenges on daily  basis, you will focus on problem solving, and you will interact with  our technology team on a regular basis. We will operate in  world-class and very fast-paced engineering environment and you will  be learning new things and making huge impact at the same time.<br>
                  <br>
                  <strong>An  Ideal Candidate Will Possess Following</strong><strong><br>
                
              <ul>
                  <li>
                    <p align="left">B.E/B.Tech/M.C.A  	in Computer Science or equivalent combination of technical education  	and work experience.</p>
                <li>
                    <p align="left">Couple  	of years of QA experience Strong knowledge of QA methodology and  	tools.</p>
                <li>
                    <p align="left">Experience  	of working on automation tools.</p>
                <li>
                    <p align="left">Web  	based and mobile application-testing experience, </p>
                <li>
                    <p align="left">Knowledge  	of Web and Mobile Technologies preferable. </p>
                <li>
                    <p align="left">Knowledge  	of Databases and Knowledge of Networking Concepts is preferable.</p>
                <li>
                    <p align="left">Knowledge  	of at least one language is preferable.</p>
                <li>
                    <p align="left">Knowledge  	of Linux Based User Command preferable.</p>
                <li>
                    <p align="left">Create/modify  	test cases based on design document.</p>
                <li>
                    <p align="left">Write/modify  	test scripts using automation Tools.</p>
                <li>
                    <p align="left">Extremely  	good interpersonal skills.</p>
              </ul>
<p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>