<?php //echo $id=$_REQUEST['id']; ?><body dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Reception</strong></h2><br>

                
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                 <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->
<p><strong>Job  Description</strong></p>
<ul>
                  <li>
                    <p>Answers  	incoming telephone calls, determines purpose of calls, and forward  	calls to appropriate personnel or department.</p>
                  </li>
                  <li>
                    <p>Takes  	and delivers messages when appropriate personnel are unavailable.</p>
                  </li>
                  <li>
                    <p>Answers  	questions about organization and provides callers with address,  	directions, and other information.</p>
                  </li>
                  <li>
                    <p>Welcomes  	on site visitors, determines nature of business, and announces  	visitors to appropriate personnel.</p>
                  </li>
                  <li>
                    <p>Operates  	multi-line telephone system to answer incoming calls; directs  	callers to appropriate personnel by performing the following duties;  	completes a variety of administrative duties.</p>
                  </li>
                  <li>
                    <p>He  	will maintain all call records.</p>
                  </li>
                  <li>
                    <p>Updating  	the register for letters &amp; couriers.</p>
                  </li>
                  <li>
                    <p> Maintain  	the attendance register.</p>
                  </li>
                </ul>
                
      <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
      <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->
      <p> <strong>Skills</strong></p>
      <ul>
        <li>
          <p>Have  	excellent managerial skills.</p>
        </li>
        <li>
          <p>Be  	professional, and positive.</p>
        </li>
        <li>
          <p>Have  	integrity, initiative and focus.</p>
        </li>
        <li>
          <p>Be able to  	think, communicate and present information effectively.</p>
        </li>
        <li>
          <p>Be able to  	use computer or IT equipment proficiently.</p>
        </li>
        <li>
          <p>Must be  	computer literate, familiarity with Microsoft excel, word, and  	outlook </p>
        </li>
        <li>
          <p>Strong  	interpersonal and communication skills.</p>
        </li>
        <li>
          <p>Can-do attitude  	and ability to think outside the box.</p>
        </li>
        <li>
          <p>Excellent  	telephone etiquettes.</p>
        </li>
        <li>
          <p>In depth  	knowledge of administrative and clerical protocols.</p>
        </li>
        <li>
          <p>Knowledge of  	customer services practices</p>
        </li>
      </ul>
      <p>
       <p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>