<?php //echo $id=$_REQUEST['id']; ?>



<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/refund-policy.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container">
            <div class="col-lg-12" align="left">        
                <h2><strong>Refund Policy</strong></h2>
                <p class="">Hello42 believes in helping its customers as far as possible, and has therefore a liberal cancellation policy. :<br />

<br />
1. The customer agrees and acknowledges that 25% of booking amount refund shall be provided if the cancellation information is received after 24 hour of scheduled pickup, If cancellation request is received before 24 hour of the scheduled pickup, convenience charge 15% would be deducted from the amount which has been booked for travel as preauthorization or advance. The cancellation can be done over the phone or by email. All cancellation to be made against the booking ID provided at the time of booking the cab.
<br />
2. There is no cancellation of orders placed under the same day booking.
<br />
3. No cancellations are entertained for that products/Service that the hello42 marketing team has obtained on special occasions like Dussehra, Pongal, Diwali, New Year etc. These are limited occasion offers and therefore cancellations are not possible. 
<br />
<br />

<strong>Hello42 India general terms:</strong><br />
 
<br />
1) Toll tax and parking will be paid directly to the driver in case not included in the outstation or one way booking 
<br />
2) After reaching the boarding point, waiting charge of Rs 2/- per minute will be charged after the 15 minutes waiting, these charge will be paid directly to the driver
<br />
3) If opting for the one-way driver will not stop the car for more than 30 minutes during the journey
<br />
4) Driver will drop the guest at the destination which will be informed by the guest while starting the journey, driver will not stop the car in between the journey except for tea and lunch break, which will be for 30 minutes max (This will be applicable if opting for one-way).
<br />
<br />
<strong>Refund Policy:</strong><br />

If you are eligible for refunds based on the "Cancellation and Returns" policy above, then the refund will be remitted back to you in 5-7 working days. In case of any issues, writes to us at support@hello42cab.com or call us at 011-42424242.
                
                </p>
            </div> 
          
        </div><!--/.container-->
    </section>