<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Regional Sales Manager</strong></h2><br>

                <strong>Position : - Regional Sales Manager </strong><br>

                 <strong>Exp:-  2+ Years</strong><br />
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->                
              <p>
                <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
              <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; line-height: 120% }  		a:link { so-language: zxx }  	-->
              <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
              <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; line-height: 120% }  		a:link { so-language: zxx }  	-->
              <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
              <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; line-height: 120% }  		a:link { so-language: zxx }  	-->
              <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
              <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
              <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; line-height: 120% }  		a:link { so-language: zxx }  	-->
              <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
              <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; line-height: 120% }  		a:link { so-language: zxx }  	--><strong>Skills   &amp; Responsibilities: </strong></p>
              <ul>
                <li>
                  <p align="left">Exposed  	to Superior sales and management skills with accomplishments all  	through his/her career.</p>
                <li>
                  <p align="left"> Excellent  	written, oral communication and presentation skills.</p>
                <li>
                  <p align="left">Established  	track record in effective leadership talents which includes people  	development.</p>
                <li>
                  <p align="left"> Increasing  	business opportunities through various routes to market </p>
                <li>
                  <p align="left"> Developing  	sales strategies and setting targets </p>
                <li>
                  <p align="left"> Reaching  	the targets and goals set for your area </p>
                <li>
                <p align="left"> Establishing,  	maintaining and expanding customer base </p>                
              </ul>
<p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>