<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Sales & Exqutive</strong></h2><br>

                <strong>Position : - Sales & Marketing </strong><br>

                 <strong>Exp:-  2+ Years</strong><br />
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->                
              <p><strong>Job  Description</strong></p>
<ul>
  <li>
    <p>Advertisements  	in Publications, Counseling Centers, Poster Campaigns.</p>
  <li>
    <p>Must have the  	knowledge of B2B &amp; B2C Marketing in online and offline.</p>
  <li>
    <p>He will be  	looking after complete Delhi NCR.</p>
  <li>
    <p>Promoting and  	marketing the business, to new or niche markets.</p>
  <li>
    <p>Sourcing  	products and destinations to meet consumer demands for bespoke  	travel and sustainable tourism.</p>
  <li>
    <p>Dealing with  	customer enquiries and aiming to meet their expectations.</p>
  <li>
    <p>Overseeing the  	smooth, efficient running of the business.</p>
  <li>
    <p>Monitoring and  	analyzing market trends.</p>  
</ul>
<p><strong>Skills  and personal qualities</strong></p>
<ul>
  <li>
    <p> Have knowledge of a wide range of marketing techniques and concepts.</p>
  <li>
    <p> Be an excellent communicator.</p>
  <li>
    <p> Be able to respond well to pressure.</p>
  <li>
    <p> Think creatively.</p>
  <li>
    <p> Work well in a team and with a wide range of people.</p>
  <li>
    <p> Be organized and methodical.</p>
  <li>
    <p> Be proactive and able to take the initiative.</p>
  <li>
    <p> Be able to motivate and inspire a team.</p>
  <li>
    <p> Be well presented with a professional manner.</p>
  <li>
    <p> Be persuasive and diplomatic.</p>
  <li>
    <p> Have a good business awareness.</p>
  <li>
    <p> Be able to work within a budget.</p>
  </ul>
<p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>