<?php //echo $id=$_REQUEST['id']; ?>



<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow fadeInDown">
           <img src="<?= $this->basePath();?>/public/img_banner/services.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature" >
        <div class="container">
           <div class="center wow col-lg-12 fadeInDown">
                <h2 align="left">Our Services</h2>
                <p class="">Hello 42 Cabs services is the first company in India which is offering point to point services in car rental which is chepaer than Radio Taxi services. Hello 42 Cabs is a venture of pepole who have very vast exprience in Travel industry very much pioner in B2B and B2C trade since 1994. </p>
            </div>

            <div class="row">
                <div class="features">
                    <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="feature-wrap">
                            <i class="icntReliability"></i>
                            <h3>Reliability</h3>
                            <p>
                           	 Never cancel any trip<br />
							Well groomed drivers<br />
							High quality with affordability<br />
                            Promise of on time execution<br />
							24 x 7 support<br />
							
                            </p>
                        </div>
                    </div><!--/.col-md-4-->

                    <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="feature-wrap">
                            <i class="icntconvienence"></i>
                            <h3>Convenience</h3>
                            <p>
                            	Book by  web, phone or app<br />
								Pay by cash or card<br />
								<!--In car news paper, tissue paper and mineral water<br />-->
								Hassle free booking and instant confirmation<br />
                            </p>
                        </div>
                    </div><!--/.col-md-4-->

                    <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="feature-wrap">
                            <i class="icntSefty"></i>
                            <h3>Safety</h3>
                            <p>
                           	 Police Verified Drivers<br />
							Real Time Cab Tracking<br />
							Details share feature in App<br />
							24 x 7 support<br />
							In car GPS systems that makes our <br />
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; vehicle safe<br />
                            </p>
                        </div>
                    </div><!--/.col-md-4-->
                
                    <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="feature-wrap">
                            <i class="icntfleet"></i>
                            <h3>Our Fleet</h3>
                            <p>
                            	Wide range of cars<br />
								Amenities for comfort<br />
								Well maintained and young fleet<br />
								No compromise on cab quality<br />
                            
                            </p>
                        </div>
                    </div><!--/.col-md-4-->

                    <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="feature-wrap">
                            <i class="icntchauffer"></i>
                            <h3>Our Chauffeur</h3>
                            <p>
                            	Double Verified<br />
								Well groomed<br />
								Multi lingual<br />
                                Work with fatigue management<br />
								<!--Highly trained :--> Health, Security and Environment<br />
								
                                
                                </p>
                        </div>
                    </div><!--/.col-md-4-->

                    <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="feature-wrap">
                            <i class="icntpricing"></i>
                            <h3>Our Pricing</h3>
                            <p>
                            	Transparent pricing structure<br />
								No luggage charges<span style="color:red;">*</span><br />
                                No night charges.<br />
								No  AC charges.<br />
								No booking charges <!--or call centre charges--><br />
<br />
<span style="color:red;">* </span>Terms and conditions apply
								
                            </p>
                        </div>
                    </div><!--/.col-md-4-->
                </div><!--/.services-->
            </div><!--/.row-->    
        </div><!--/.container-->
    </section>
    
    