<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Sr. PHP Developer</strong></h2><br>

                <strong>Position : - Sr. PHP Developer</strong><br>

                 <strong>Exp:-  3+ Years</strong><br />
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->
<p>
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
  <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
  <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; line-height: 120% }  		a:link { so-language: zxx }  	-->
</p>
<p align="left"><strong>KEY  SKILLS:</strong></p>
<p align="left">1.  HTML </p>
<p align="left">2.  CSS</p>
<p align="left">3.  Javascript</p>
<p align="left">4.  PHP</p>
<p align="left">5.  MySQL</p>
<p align="left">6.  Web Technologies</p>
<p align="left">7.  Zend Framework</p>
<p align="left"><strong>Job  Responsibility:</strong></p>
<ul>
  <li>
    <p align="left">Should  	have expertise with interfaces, HTML5, CSS 3, JavaScript, AJAX,  	caching, sessions, and authentication </p>
  <li>
    <p align="left">Should  	have knowledge of Ajax and APIs integration (Open APIs) highly  	desirable </p>
  <li>
    <p align="left">Should  	have strong knowledge of the Markup languages: CSS 3 &amp; HTML 5 </p>
  <li>
    <p align="left">Should  	have understanding of the Data formats JSON, JSONP </p>
  <li>
    <p align="left">Should  	play key role in Release and deployment planning. </p>
  </ul>
<p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>