<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Vendor Attachment</strong></h2><br>

                <strong>Position : - Vendor Attachment </strong><br>

                 <strong>Exp:-  2 Years</strong><br />
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->                
              <p>
                <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"><strong>Job  Description</strong></p>
              <ul>
                <li>
                  <p>Make 70  	calls per day for Vendor Attachments .</p>
                <li>
                  <p>Target of  	attachment 5 cars Per Day &amp; 100 Cars Per Month on average.</p>
                <li>
                  <p>Make a  	records of all the calls made to driver &amp; send to the reporting  	manager at the end of day.</p>
                <li>
                  <p>Responsible  	for all the Venders related to out station as well as Local Vendor  	Attachments for All categories of vehicle.</p>
                <li>
                  <p>Require to  	audit 30 to 40 cars in a week with the entire document, agreement &amp;  	check list.</p>
                <li>
                  <p>Preparing  	weekly audit sheet &amp; send to the reporting manager at the end of  	the week.</p>
                <li>
                  <p>Updating all  	the Vender agreement form, Quality control sheet, Driver training  	Module time to time.</p>
                <li>
                  <p>He has to  	maintain the cab quality, Car Chauffeur quality &amp; Vender  	Quality.</p>
                <li>
                  <p>He will be  	arranging the required cab on time.</p>
                <li>
                  <p>Checking the  	route test of chauffeur.</p>
                <li>
                  <p>He will be  	training the chauffeur.</p>
                <li>
                  <p>Ability to  	work in flexible timings.<br>
              </p>                
              </ul>
<p> <strong>Skills</strong></p>
              <ul>
                <li>
                  <p>Be a team  	player.</p>
                <li>
                  <p>Have  	excellent managerial skills.</p>
                <li>
                  <p>Be  	professional, and positive.</p>
                <li>
                  <p>Have  	integrity, initiative and focus.</p>
                <li>
                  <p>Be able to  	think, communicate and present information effectively.</p>
                <li>
                  <p>Be able to  	motivate self, team or staff.</p>
                <li>
                  <p>Be able to  	use computer or IT equipment proficiently.</p>
                <li>
                  <p>Must be  	computer literate, familiarity with Microsoft excel, word, and  	outlook </p>
                <li>
                  <p>Must be able to  	sustain a high level of fair play, honesty and consistency.</p>
              </ul>
<p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>