<?php //echo $id=$_REQUEST['id']; ?><body link="#0000ff" dir="ltr" lang="en-US" xml:lang="en-US">


<section id="" style="background:#c0c0c0; padding:0;" >
        <div class="container">
          <div class="center wow">
           <img src="<?= $this->basePath();?>/public/img_banner/careers.jpg" />
               
   <br />



            <!--/.row-->    
        </div><!--/.container-->
        
        </div>
    </section>

<section id="feature">
        <div class="container" style="text-align:left;">
            <div class="col-lg-12" >        
                <h2><strong>Graphic & Web Designer</strong></h2><br>

                <strong>Position : - Graphic & Web Designer </strong><br>

                 <strong>Exp:-  2+ Years</strong><br />
                 <strong>Job Location: Delhi (Karol Bagh)</strong><br />
                  <strong>Date Posted: 23-03-2016</strong><br /><br />
                 
                  <p> <a id="" class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
                <br />
                <p class="lead">We always keep a look-out for top talent to join us. If you feel you talented enough and can contribute to Hello42 then fill out the form below:     <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->
<p>
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
  <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  	-->
</p>
<p>
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
  <!--  		@page { margin: 2cm }  		p { margin-bottom: 0.25cm; direction: ltr; line-height: 120%; text-align: left; widows: 2; orphans: 2 }  		a:link { color: #0000ff; so-language: zxx }  	-->
</p>
<p><strong>Job  Description</strong></p>

  <ol type="a">
    <li>
      <p>Develops  		site&nbsp;graphics, images, icons, banners, etc.</p>
    <li>
      <p>Upgrades  		site by updating content and&nbsp;graphics; monitoring performance  		and results; identifying and evaluating improvement options;  		introducing new technology; maintaining links.</p>
    <li>
      <p>Maintains  		site appearance by developing and enforcing content and display  		standards; editing submissions</p>
    <li>
      <p>Good  		understanding of responsive web design, visualize and develop- info  		graphics, animations and interactivities</p>
    <li>
      <p>Ability  		to develop website in static HTML and Word Press and have good  		knowledge about its customization&nbsp;</p>
    <li>
      <p>Excellent  		knowledge and expertise in W3C compliant HTML5/CSS3, PSD to HTML  		conversion, CSS3 &amp; jQuery animation, 3rd party tools &amp;  		social media integration</p>
    <li>
      <p>Determining  		size and arrangement of illustrative material and copy, and font  		style and size.</p>
    <li>
      <p> Manage design projects / deliverables on  		day to day basis.</p>
    <li>
      <p> Ability to work with interpreting  		concepts/storyboarding for digital campaigns.</p>
    <li>
      <p> Demonstrable experience with Standard and  		Rich Media Banners- interactivity, roll-overs, video integration  		and other formats.</p>
    <li>
      <p> Daily requirement  		of Banner design for Social Media, Website , Mobile App , Email  		Marketing , Print etc</p>    
  </ol>
 	 	
<p><u><strong>Requirement  :</strong></u><u>&nbsp;</u></p>

  <ul>
    <li>
      <p>Bachelor/Master  		degree in creative design or respective field </p>
    <li>
      <p>2+  		years experience in creative&nbsp;G<strong>raphics</strong>&nbsp;and  		Website designing.</p>
    <li>
      <p>Worked  		on e-commerce website.</p>
    <li>
      <p>Good  		understanding &amp; experience in designing innovative wireframes,  		mock ups of entire website, micro site, landing pages, banners,  		brochures, case studies, templates, etc.</p>
    <li>
      <p>Good  		understanding &amp; experience in innovative color palates/themes,  		creative layouts, and typography in different digital mediums.</p>
    <li>
      <p>Ability  		demonstrate illustrative skills with rough sketches&nbsp;</p>
    <li>
      <p>Excellent  		fluency with software like Photoshop, CorelDraw, Illustrator and  		Dreamweaver</p>
    <li>
      <p>Hands  		on experience on HTML and CSS is must</p>    
  </ul>

<p style=" float:left;"> <a  class="btn btn-primaryred btn_fare" href="<?php echo $this->basePath(); ?>/index/page/apply_now">Apply Now</a></p>
      </div> 
          
        </div><!--/.container-->
    </section></p>