<?php $session=new Zend\Session\Container('admin');
if($session->offsetGet('adminuser')==''){
	$bashPath=$this->basePath();
	$location="Location:".$bashPath."/admin";
 	header($location);	
	exit;	
 } ?><div id="page-wrapper" class="" >
  <h4 style="">Add Promotion</h4>
  <div>
    <div class="container">
      <div class="row">
        <form role="form" method="post" action="save">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="PromotionName">Promotion Name</label>
              <div class="input-group">
                <input type="text" class="form-control" name="PromotionName" id="PromotionName" placeholder="Promotion Name" required>
                <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span></div>
            </div>
            <div class="form-group">
              <label for="PromotionName">Promotion Description</label>
              <div class="input-group">
                <textarea name="PromotionDescription" id="PromotionDescription" class="form-control"></textarea>
                <span class="input-group-addon"></span></div>
            </div>
            <div class="form-group">Coupon Type
              <div class="input-group">
                <select name="CouponType" id="CouponType" class="form-control" >
				<option value="1">Select Coupon</option>
				<option value="1">Coupon Only Discount</option>
				<option value="2">Credit Coupon</option>
				<option value="3">General Coupon</option>
				<option value="4">General Restricted Coupon</option>
                </select>
                <span class="input-group-addon"></span></div>
            </div>
            <div class="form-group">
              <label for="ValidDateFrom">Valid Date</label>
              <div class="input-group"> <span class="input-group-addon"> From </span>
                <input type="text" class="form-control" id="ValidDateFrom" name="ValidDateFrom" placeholder="Enter Date From" required>
                <span class="input-group-addon"> To </span>
                <input type="text" class="form-control" id="ValidDateTo" name="ValidDateTo" placeholder="Enter Date To" required>
                <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span> </div>
            </div>
            <div class="form-group">
              <label for="ValidTimeFrom">Valid Time From</label>
              <div class="input-group"> <span class="input-group-addon"> From </span>
                <select name="ValidTimeFrom" id="ValidTimeFrom" class="form-control" required>
                  <?php print $data['TimeList'];?>
                </select>
                <span class="input-group-addon"> To </span>
                <select name="ValidTimeTo" id="ValidTimeTo" class="form-control" required>
                  <?php print $data['TimeList'];?>
                </select>
                <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span> </div>
            </div>
            <div class="form-group">
              <label for="WeekDay">Select Days</label>
              <div class="input-group" id ="frm1">
                <ul style="list-style-type: none;">
                  <li>
                    <input type="checkbox" name="CheckAll" value="1" id="selecctall" />
                  <strong>Check All</strong></li>
                  </li>
                  <li>
                    <input type="checkbox" name="WeekDays[]" value="Sunday" class="checkbox1" />
                    Monday </li>
                  <li>
                    <input type="checkbox" name="WeekDays[]" value="Monday"  class="checkbox1" />
                    Tuesday </li>
                  <li>
                    <input type="checkbox" name="WeekDays[]" value="Tuesday" class="checkbox1" />
                    Wednesday </li>
                  <li>
                    <input type="checkbox" name="WeekDays[]" value="Wednesday" class="checkbox1" />
                    Thursday </li>
                  <li>
                    <input type="checkbox" name="WeekDays[]" value="Thursday" class="checkbox1" />
                    Friday </li>
                  <li>
                    <input type="checkbox" name="WeekDays[]" value="Friday" class="checkbox1" />
                    Saturday </li>
                  <li>
                    <input type="checkbox" name="WeekDays[]" value="Saturday" class="checkbox1" />
                    Sunday </li>
                </ul>
              </div>
            </div>
            
            <div class="form-group">
              <label for="BookingType">Booking Type</label>
              <div class="input-group">
                <select name="BookingTypeId" id="BookingTypeId" class="form-control" required>
                  <?php print $data['BookingTypeList'];?>
                </select>
                <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span></div>
            </div>
            <div class="form-group">
              <label for="MinimumBookingAmount">Minimum Booking Amount</label>
              <div class="input-group">
                <input type="number" maxlength="4" class="form-control" id="MinimumBookingAmount" name="MinimumBookingAmount" placeholder="Minimum Booking Amount" required />
                <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span></div>
            </div>
            <div class="form-group">
              <label for="Discount">Discount In</label>
              <div class="input-group">
                
                RS <input type="radio" onclick="discount_type(this.value)" checked="checked" name="DiscountType" id="RS" value="RS" />
                % <input type="radio" onclick="discount_type(this.value)" name="DiscountType" id="Per" value="%" />
                
                <span class="input-group-addon" id="DiscountType">RS</span><input type="number" class="form-control" id="Discount" name="Discount" placeholder="Discount" required />
              </div>
                
            </div>
            <input type="submit" value="Save Coupon Code" class="btn btn-info pull-right">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script>
	$(document).ready(function(){
		$(function() {
			$("#ValidDateFrom" ).datepicker({
				changeMonth: true,
				changeYear: true,
				yearRange: '2010:2020',
				dateFormat : 'dd-mm-yy',
				defaultDate: new Date(<?=date('Y , m , d')?>)
			});
			$("#ValidDateTo" ).datepicker({
				changeMonth: true,
				changeYear: true,
				yearRange: '2010:2020',
				dateFormat : 'dd-mm-yy',
				defaultDate: new Date(<?=date('Y , m , d')?>)
			});
		});
	});
	
	function discount_type(ds_type){
		$('#DiscountType').html(ds_type);
	}
</script> 
<!--Script by hscripts.com-->
<!-- Free javascripts @ https://www.hscripts.com -->
<script type="text/javascript">
$(document).ready(function() {
    $('#selecctall').click(function(event) {  //on click
        if(this.checked) { // check select status
            $('.checkbox1').each(function() { //loop through each checkbox
                this.checked = true;  //select all checkboxes with class "checkbox1"              
            });
        }else{
            $('.checkbox1').each(function() { //loop through each checkbox
                this.checked = false; //deselect all checkboxes with class "checkbox1"                      
            });        
        }
    });
   
});
</script>
<!-- Script by hscripts.com -->