<div class=" mapcantiner_inner">
    <h2>Select a Car for Outstation</h2>
      
    <div></div>
    <div class=" mapcantiner_inner1">
  
      <table class="table1">
      <tr>
      <td colspan="3" style="background:#f8f8f8;">Itenarary</td>

      </tr>
      <tr>
      <td>From</td>
      <td>To</td>
      <td>Date</td>
      </tr>
      <tr>
      <td><input type="text" placeholder="Delhi/NCR" class="input1" ></td>
      <td><input type="text" class="input1" placeholder="Delhi/NCR" ></td>
      <td><input type="text" class="input1" ></td>
      </tr>
      <tr>
      <td><input type="text" class="input1" placeholder="Delhi/NCR" ></td>
      <td><input type="text" class="input1" placeholder="Delhi/NCR" ></td>
      <td><input type="text" class="input1" ></td>
      </tr>
      <tr>
      <td><input type="text" class="input1" placeholder="Delhi/NCR" ></td>
      <td><input type="text" class="input1" placeholder="Delhi/NCR" ></td>
      <td><input type="text" class="input1" ></td>
      </tr>
      <tr>
      <td><input type="text" class="input1" placeholder="Delhi/NCR" ></td>
      <td><input type="text" class="input1" placeholder="Delhi/NCR" ></td>
      <td><input type="text" class="input1" ></td>
      </tr>
      <tr>
      <td colspan="3" style="background:#f8f8f8;">Details</td>

      </tr>
      <tr>
      <td colspan="2">Pickup Address</td>
      <td>test</td>
      </tr>
      <tr>
      <td colspan="2">Pickup Time</td>
      <td>10:05</td>
      </tr>
      <tr>
      <td colspan="2">Minimum Distance</td>
      <td></td>
      </tr>
      
      <tr>
      <td colspan="2">Roundtrip</td>
      <td>Yes</td>
      </tr>
      </table>
      <div class="clear"></div>

     <table class="table" border="0">
     <tr>
     <Td width="24%" style="background:#f8f8f8;">Car</Td>
     <td width="17%" style="background:#f8f8f8;">Category</td>
     <td width="23%" style="background:#f8f8f8;">Capacity</td>
     <td width="19%" style="background:#f8f8f8;">Price</td>
     <td width="17%" style="background:#f8f8f8;"></td>
     </tr>
     <Tr>
     <td ><img src="/hello42/public/image/compact.png" class="img"></td>
     <td><span class="span3">Compact</span>
<span class="span4">Tata Indica</span></td>
     <td><span class="number">1</span>+ 4 Driver</td>
     <td><span class="span4">Fare Details</span></td>
     <td><img src="/hello42/public/image/book_now.png"></td>
     </Tr>
     <Tr>
     <td><img src="/hello42/public/image/compact.png" class="img"></td>
     <td><span class="span3">Compact</span>
<span class="span4">Tata Indica</span></td>
     <td><span class="number">1</span>+ 4 Driver</td>
     <td><span class="span4">Fare Details</span></td>
     <td><img src="/hello42/public/image/book_now.png"></td>
     </Tr>
     <Tr>
     <td><img src="/hello42/public/image/compact.png" class="img"></td>
     <td><span class="span3">Compact</span>
<span class="span4">Tata Indica</span></td>
     <td><span class="number">1</span>+ 4 Driver</td>
     <td><span class="span4">Fare Details</span></td>
     <td><img src="/hello42/public/image/book_now.png"></td>
     </Tr>
     </table>
      
    </div>
 </div>