<div class=" mapcantiner_inner">
    <h2>CAREER</h2>
    <div class=" mapcantiner_inner1">
    <article><strong>Operations Manager</strong>
</article>
<br>
<article><strong>Roles and Responsibilities:</strong></article>
<div class="clear"></div>
<ul>
<li>  Strategy Responsible for strategizing for the day-to-day operating activities including fleet management, partner management and customer management.
</li>
<li>Operations Ensure all SLAs with Partners are met e.g. ensure timely dispatch of cars and timely reporting to the customers by effective management of all resources available. Responsi    
      ble for supervision of drivers for training, mannerisms, customers focus etc.</li>
    <li>Customer Service Build a top class customer service and call center organization Develop systems and processes to constantly seek customer feedback Identify issues across operations     
     at early stage and devise ways to address the same Enable a high degree of visibility and credibility for the TaxiForSure brand.</li>
     
    <li>Processes & Systems Monitor & set Processes & Systems in order to ensure safety, preventive maintenance, cleanliness in vehicles etc Ensure all safety and hygiene standards are met.</li>
    <li>Best Practices & Innovation Establish Taxiforsure’s operations and customer service standards, guidelines and best practices. Build an environment to constantly challenge the status   
     quo and innovate. Constantly improve, understand and benchmark with respect to global standards and methodologies.</li>
    <li>Communication- Develop effective processes for communication within the team and other functions.</li>
</ul>

<article><strong>UI/UX Designer</strong></article>
<article><strong>Roles and Responsibilities:</strong></article>

<ul>
<li>Design web portal, Mobile WAP site, Mobile App</li>
<li>Strong consumer / user orientation</li>
<li>Come up with a mascot for the company which will be used across all the marketing campaigns of the company</li>
<li>Analyze customer experience on the portal, mobile App, WAP site - take feedback and incorporate</li>
</ul>

<article><strong>Job Requirements:</strong></article>
<ul>
<li>Should have designed e-commerce portals before</li>
<li>Strong consumer / user orientation</li>
<li>Designed mobile apps, WAP sites</li>
<li>Should have designed marketing collateral - Both Offline & Online</li>
<li>Self-Motivated</li>
<li>Experience in building a brand is an advantage</li>
</ul>
    </div>
	</div>