<?php $session=new Zend\Session\Container('admin');
if($session->offsetGet('adminuser')==''){
	$bashPath=$this->basePath();
	$location="Location:".$bashPath."/admin";
 	header($location);	
	exit;	
 } ?>
 
 <style>
 .form-control {
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
    color: #555;
    display: block;
    font-size: 12px;
    height: 30px !important;
    line-height: 1.42857;
    padding: 6px 15px;
    transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
    width: 85%;
 
 </style>
 
<div id="page-wrapper" class="" >
 
  <div >
  
  
  
  
    <div class="container">
	
	
	
	
	
	<div class="row">
    <div class="col-lg-12">
    
    
      <h4 class="page-header">General Information</h4>
    </div>
  </div>
  
  
  
  
  <form id="bookingFilter">
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade active in" id="home">
              <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px; height:700px;">
              
              
              
              
              
             
                    
                    
                    
                      
                    
                    
                    
                    
                    
                    
                    <div class="clearfix"></div>
                    
                    
                    
                    
                    
                    
                
                  <div class="form-group clearfix margintopnew20">
				  

                    <label id="Alogrithm" class="col-sm-2 control-label labelalign ">Name</label>
                    <div class="col-sm-3">
                      <input type="text" placeholder="Alogrithm" class="form-control inputchange" id="Alogrithm">
                    </div>
                    <label id="point_airport" class="col-sm-2 control-label labelalign ">Father Name</label>
                    <div class="col-sm-3">
                      <input type="text" placeholder="Father Name" class="form-control inputchange" id="Father Name">
                    </div>
                  </div>
                
                
                
                
                
                
                   <div class="form-group clearfix margintopnew20">
				  

                    <label id="Alogrithm" class="col-sm-2 control-label labelalign ">Email</label>
                    <div class="col-sm-3">
                      <input type="text" placeholder="Email" class="form-control inputchange" id="Email">
                    </div>
                    <label id="point_airport" class="col-sm-2 control-label labelalign ">Gender</label>
                    <div class="col-sm-1">
					 <label id="Male" class="col-sm-4 control-label labelalign">Male</label>
                      <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios">
                    </div>
					<div class="col-sm-1">
					 <label id="Male" class="col-sm-4 control-label labelalign ">Female</label>
                      <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios" style="margin-left:10px;">
                    </div>
					
					
                  </div>
				  
				  
				  
				  
				  
				  
				  
				  
				  
				   <div class="form-group clearfix margintopnew20">
				  

                    <label id="point_airport" class="col-sm-2 control-label labelalign ">
User type</label>
                    <div class="col-sm-3">
					
                    <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                    </div>
                     <label id="Alogrithm" class="col-sm-2 control-label labelalign ">Category</label>
                    <div class="col-sm-3">
                          <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                    </div>
                  </div>
				  
				  
				  
				  
				  
				  <div class="form-group clearfix margintopnew20">
				  

                     <label id="point_airport" class="col-sm-2 control-label labelalign">User Name</label>
                    <div class="col-sm-3">
                    <input type="text" id="Password" class="form-control inputchange" placeholder="Password">
                    </div>
                     <label id="Alogrithm" class="col-sm-2 control-label labelalign ">Password</label>
                    <div class="col-sm-3">
                         <input type="text" class="form-control" name="username" id="Password" value="<?php print $data['Rec']->username;?>" placeholder="Username" required>
                    </div>
                  </div>
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				   <div class="form-group clearfix margintopnew20">
				  

                    <label id="Alogrithm" class="col-sm-2 control-label labelalign ">Start Date</label>
                    <div class="col-sm-3">
                     <input type="text" data-date-format="dd-mm-yyyy" id="id-date-picker-1" class="form-control date-picker">
					 
					
                    </div>
                    <label id="point_airport" class="col-sm-2 control-label labelalign ">Phone No*</label>
                    <div class="col-sm-3">
                      <input type="text" placeholder="Father Name" class="form-control inputchange" id="Father Name">
                    </div>
                  </div>
				  
				  
				  
				  
				  
				  <div class="form-group clearfix margintopnew20">
				  

                    <label id="Alogrithm" class="col-sm-2 control-label labelalign ">Alternate No</label>
                    <div class="col-sm-3">
                      <input type="text" placeholder="Email" class="form-control inputchange" id="Email">
                    </div>
                    <label id="point_airport" class="col-sm-2 control-label labelalign ">Reference by</label>
                    <div class="col-sm-3">
                      <input type="text" placeholder="Father Name" class="form-control inputchange" id="Father Name">
                    </div>
                  </div>
				  
				  
				  
				  
				  
				    <div class="form-group clearfix margintopnew20">
				  

                    <label id="Alogrithm" class="col-sm-2 control-label labelalign ">Address</label>
                    <div class="col-sm-3">
                         <textarea class="form-control" rows="3" placeholder="Enter ..."></textarea>
                    </div>
                    <label id="point_airport" class="col-sm-2 control-label labelalign ">Country</label>
                    <div class="col-sm-3">
					
					
					  <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
					
					
					
                        
                    </div>
                  </div>
				  
				  
				  
				    <div class="form-group clearfix margintopnew20">
				  

                    <label id="Alogrithm" class="col-sm-2 control-label labelalign ">State</label>
                    <div class="col-sm-3">
                        <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                    </div>
                    <label id="point_airport" class="col-sm-2 control-label labelalign ">City</label>
                    <div class="col-sm-3">
                        <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                    </div>
                  </div>
				  
				  
				  
				  
				  
				 
				  
				  
				
				  
				  
				    <div class="form-group clearfix margintopnew20">
				  

                     <label id="point_airport" class="col-sm-2 control-label labelalign">Pin code</label>
                    <div class="col-sm-3">
                  <input type="text" placeholder="Father Name" class="form-control inputchange" id="Father Name">
                    </div>
                     <label id="Alogrithm" class="col-sm-2 control-label labelalign ">IsActive</label>
                    <div class="col-sm-3">
                         <select name="IsActive" id="IsActive" class="form-control" required>
				<?php print $data['StatusList'];?>
				</select>
                    </div>
                  </div>
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				    
				  
				  
				  
				  
				  
				  
				  
				  
				  

<h4>Previous Office Address</h4>
				  
				  
				  
				  
				  
				  
				  
				  
				  
				   <div class="form-group clearfix margintopnew20">
				  

                    <label id="Alogrithm" class="col-sm-2 control-label labelalign ">Previous Office Address</label>
                    <div class="col-sm-3">
                         <textarea class="form-control" rows="3" placeholder="Enter ..."></textarea>
                    </div>
                    <label id="point_airport" class="col-sm-2 control-label labelalign ">Country</label>
                    <div class="col-sm-3">
					
					
					  <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
					
					
					
                        
                    </div>
                  </div>
				  
				  
				  
				    <div class="form-group clearfix margintopnew20">
				  

                    <label id="Alogrithm" class="col-sm-2 control-label labelalign ">State</label>
                    <div class="col-sm-3">
                        <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                    </div>
                    <label id="point_airport" class="col-sm-2 control-label labelalign ">City</label>
                    <div class="col-sm-3">
                        <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                    </div>
                  </div>
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				  
				   <div class="form-group clearfix margintopnew20">
				  

                    <label id="Alogrithm" class="col-sm-2 control-label labelalign ">Pin code</label>
                    <div class="col-sm-3">
                     <input type="text" id="Email" class="form-control inputchange" placeholder="Email">
                    </div>
                   <label id="Alogrithm" class="col-sm-2 control-label labelalign ">User type</label>
                    <div class="col-sm-3">
                        <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                    </div>
                  </div>
				  
				  
				  
				  
				  
				  
				   <div class="form-group clearfix margintopnew20">
				  

                    <label id="point_airport" class="col-sm-2 control-label labelalign ">Category</label>
                    <div class="col-sm-3">
					
                    <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                    </div>
                     <label id="Alogrithm" class="col-sm-2 control-label labelalign ">User Id</label>
                    <div class="col-sm-3">
                          <input type="text" id="User Id" class="form-control inputchange" placeholder="User Id">
                    </div>
                  </div>
				  
				  
				  
				  
				  
				  <div class="form-group clearfix margintopnew20">
				  

                     <label id="point_airport" class="col-sm-2 control-label labelalign">Password</label>
                    <div class="col-sm-3">
                    <input type="text" id="Password" class="form-control inputchange" placeholder="Password">
                    </div>
                     <label id="Alogrithm" class="col-sm-2 control-label labelalign ">User Name</label>
                    <div class="col-sm-3">
                         <input type="text" class="form-control" name="username" id="username" value="<?php print $data['Rec']->username;?>" placeholder="Username" required>
                    </div>
                  </div>
				  
				  
				  
				   <div class="form-group clearfix margintopnew20">
				  

                   <label id="Alogrithm" class="col-sm-2 control-label labelalign ">IsActive</label>
                    <div class="col-sm-3">
                     <select name="IsActive" id="IsActive" class="form-control" required>
				<?php print $data['StatusList'];?>
				</select>
                    </div>
                     <!-- <label id="Alogrithm" class="col-sm-2 control-label labelalign ">IsActive</label>
                    <div class="col-sm-3">
                        
                    </div>
					-->
                  </div>
				  
				  
				  <!-- <div class="form-group clearfix margintopnew20">
				  

                    <label id="Alogrithm" class="col-sm-2 control-label labelalign ">Password</label>
                    <div class="col-sm-3">
                   <input type="password" class="form-control" name="password" id="password" value="<?php print $data['Rec']->password;?>" placeholder="Password" required>
                    </div>
                     <label id="Alogrithm" class="col-sm-2 control-label labelalign ">IsActive</label>
                    <div class="col-sm-3">
                         <select name="IsActive" id="IsActive" class="form-control" required>
				<?php print $data['StatusList'];?>
				</select>
                    </div>
                  </div>
				  
				  -->
				  
				  
				  
			  
				  
				  <div class="col-md-8 "> 
          <!-- Horizontal Form -->
          <div class="box box-info"> 
            <!-- /.box-header -->
            
			
			
			      <h4 class="page-header">Upload Photo</h4>
			
			
			<div class="col-md-3"> 
            
            <div class="form-group">
                      <label for="exampleInputFile">Browse Image</label>
                      <input type="file" id="exampleInputFile">
                      <p class="help-block">Example block-level help text here.</p>
                    </div>
					
					</div>
         
		 
		 
		 
		 
		 
		 
            
            <div class="col-md-3 "> 
			
			
			<img width="126" height="127" src="/hello42/public/images/agent.jpg" style="padding-left:10px;" class="img-responsive" alt=""></div>
			
			
			
            <div style="margin-top:20px margin-left:10px; col-md-2"></div>
            <div class="form-group">
              <label for="exampleInputFile">Upload File</label>
              <input type="file" id="exampleInputFile">
              <p class="help-block">Example block-level help text here.</p>
            </div>
          </div>
          <!-- /.box --> 
          <!-- general form elements disabled --> 
          <!-- /.box --> 
        </div>
		
		
		
		
		
		<div class="row">
                <div class="form-group clearfix margintopbottom20">
												 
                     <div class="col-sm-4 pull-right">
                       <a class="btn btn-red defaultbtnsearch searchBooking" href="#">SUBMIT</a>
					                      
                                                  </div>
												  
		
		
		
		
		
		
		
		
		
		
				  
		
					
                    
                 
                    
                    
                  </div>
                
              
                
               
              </div>
              
              		
                
              </div>
            </div>
          </form>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
	
      
