<?php $session=new Zend\Session\Container('admin');
if($session->offsetGet('adminuser')==''){
	$bashPath=$this->basePath();
	$location="Location:".$bashPath."/admin";
 	header($location);	
	exit;	
 } ?>
<div id="page-wrapper" class="" >
  <h4 style="">Edit User</h4>
  <div>
    <div class="container">
      <div class="row">	
		 <form role="form" method="post" action="update">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="Full Name">Full Name</label>
              <div class="input-group">
                <input type="text" class="form-control" name="full_name" id="full_name" value="<?php print $data['Rec']->full_name;?>" placeholder="Full Name" required>
                <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span></div>
            </div>
            <div class="form-group">
              <label for="Username">Username</label>
              <div class="input-group">
				<input type="text" class="form-control" name="username" id="username" value="<?php print $data['Rec']->username;?>" placeholder="Username" required>
                <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span></div>
            </div>
			<div class="form-group">
              <label for="Email">Email</label>
              <div class="input-group">
				<input type="text" class="form-control" name="email" id="email" value="<?php print $data['Rec']->email;?>" placeholder="Email" required>
                <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span></div>
            </div>
			
			<div class="form-group">
				<label for="Role">Role</label>
				<div class="input-group">
				<select name="role_id" id="role_id" class="form-control" required>
				<?php print $data['RoleList'];?>
				</select>
				<span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span></div>
			</div>
			
			<div class="form-group">
				<label for="Status">IsActive</label>
				<div class="input-group">
				<select name="IsActive" id="IsActive" class="form-control" required>
				<?php print $data['StatusList'];?>
				</select>
				<span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span></div>
			</div>
           
            <input type="submit" value="Save" class="btn btn-info pull-right">
          </div>
          <input type="hidden" name="id" value="<?php print $data['Rec']->id;?>" />
        </form>
		
      </div>
    </div>
  </div>
</div>
