
<?php 
$path=$this->basePath();
if (defined('RUNNING_FROM_ROOT')) {
  $this->plugin('basePath')->setBasePath($this->basePath().'/public');
} ?>
<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(''. $this->translate('Hello42'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
		 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                      
						->prependStylesheet($this->basePath() . '/css/style.css')
                        
                        ->prependStylesheet($this->basePath() . '/css/custom.css')
                        ->prependStylesheet($this->basePath() . '/font-awesome-4.2.0/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/font-awesome-4.2.0/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/carousel.css') 
                        ->prependStylesheet($this->basePath() . '/css/jsCarousel.css') 
                      //  ->prependStylesheet($this->basePath() . '/css/updatedstyle.css') 
						?>

        <!-- Scripts -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
                <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    
        <?php echo $this->headScript()
			->prependFile($this->basePath() . '/js/jquery.bpopup.js')
                        ->prependFile($this->basePath() . '/js/jquery.bpopup.min.js')
                        ->prependFile($this->basePath() . '/js/userhomemap.js')
		        ->prependFile($this->basePath() . '/js/login.js')
			->prependFile($this->basePath() . '/js/jquery.cookie.js')	
                        ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
			->prependFile($this->basePath() . '/js/userhome.js')
			->prependFile($this->basePath() . '/js/jsCarousel.js')		
			->prependFile($this->basePath() . '/js/userbooking.js')
			->prependFile($this->basePath() . '/js/regioncheck.js')
			->prependFile($this->basePath() . '/js/global_text.js')
			->prependFile($this->basePath() . '/js/booking_data.js')
		//	->prependFile($this->basePath() . '/js/jquery-1.11.0.min.js')
            //->prependFile($this->basePath() . '/js/jquery-migrate-1.2.1.min.js')
            //->prependFile($this->basePath() . '/js/bootstrap.min.js')
            //->prependFile($this->basePath() . '/js/jquery.min.js')
            //->prependFile($this->basePath() . '/js/jquery-1.11.0.min.js')
            //->prependFile($this->basePath() . '/js/jquery-migrate-1.2.1.min.js')
            
             
            //->prependFile($this->basePath() . '/ie-emulation-modes-warning.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/predefine.js',   'text/javascript')    
        ; 
		
		
		?>
<meta name="google-translate-customization" content="ed6222985524da91-e9cf6390d80c95a3-gead06468fc629b8f-15"></meta>



                    <!--===========================FreiChat=======START=========================-->
<!--	For uninstalling ME , first remove/comment all FreiChat related code i.e below code
	 Then remove FreiChat tables frei_session & frei_chat if necessary
         The best/recommended way is using the module for installation                         -->

<?php
$ses=null;

if(!function_exists("freichatx_get_hash")){
function freichatx_get_hash($ses){

       if(is_file("C:/wamp/www/chat/hardcode.php")){

               require "C:/wamp/www/chat/hardcode.php";

               $temp_id =  $ses . $uid;

               return md5($temp_id);

       }
       else
       {
               echo "<script>alert('module freichatx says: hardcode.php file not
found!');</script>";
       }

       return 0;
}
}
?>
<script type="text/javascript" language="javascipt" src="http://localhost/chat/client/main.php?id=<?php echo $ses;?>&xhash=<?php echo freichatx_get_hash($ses); ?>"></script>
	<link rel="stylesheet" href="http://localhost/chat/client/jquery/freichat_themes/freichatcss.php" type="text/css">
<!--===========================FreiChatX=======END=========================-->                


    </head>
    
    <body>
 <div class="loader"><img src="/hello42/public/image/loading.gif" width="150" height="150" /></div>
<script>
	var baseurl = "<?php echo $path ?>";+
	var global_url="<?php echo $path?>";
	jQuery.cookie('BaseUrl', baseurl, { expires: 3 }); 
</script>

<div class="container-fluid"> 

    </div>
	
        
    <div class="container-fluid">
    	<div class="container container_header">
        	<div class="col-sm-3 col-md-3 col-lg-3 marginbottom20">
	   	        <a href="#" style="margin-left:10px; float:left;"><img src="public/image/logo.png" width="127" height="65"></a>
          </div><?php print_r($this->id); ?>
           

          
            <?php echo $this->content; ?>
         
			</div>
			</div>
			
			
            
   
   
   
   
   
   
   
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
		<!--footer-->
		<div class="container-fluid webfooter">
    	<div class="container">
             <div class="col-lg-12">
              <div style="padding: 10px 20px;">
               <p>
               <a href="#" id="home_aboutus" style="text-transform: capitalize"></a>
               <a href="#" id="home_services" style="text-transform: capitalize"></a>
               <a href="#">Partners</a>
               <a href="#">Careers</a>
               <a href="#">Testimonials</a>
               <a href="#">Terms & Conditions</a>
               <a href="#" id="home_contact" style="text-transform: capitalize"></a>
               </p>
               <p class="padding_margin0">
                 <a class="btn btn-social-icon padding_margin0"><i class="fa fa-facebook fa-1x socialneticons btn-danger"></i>Facebook</a>
                 <a class="btn btn-social-icon padding_margin0"><i class="fa fa-tumblr fa-1x socialneticons btn-danger"></i>twitter</a>
                 <a class="btn btn-social-icon padding_margin0"><i class="fa fa-linkedin fa-1x socialneticons btn-danger"></i>linkedin</a>
                 <a class="btn btn-social-icon padding_margin0"><i class="fa fa-google-plus fa-1x socialneticons btn-danger"></i>google-plus</a>
               
               </p>
               <p>Copyright 2013 &copy; Hello42 Pvt. Ltd. All Rights Reserved.</p>
              
              </div>
                
            </div>
        </div>
    </div>
		<!--footer-->
		
    </body>
	
</html>
<!--<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>-->
