<?php $session=new Zend\Session\Container('admin');
if($session->offsetGet('adminuser')==''){
	$bashPath=$this->basePath();
	$location="Location:".$bashPath."/admin";
 	header($location);	
	exit;	
 } ?><div id="page-wrapper" class="" >
  <h4 style="">Add Role</h4>
  <div>
    <div class="container">
      <div class="row">	
		 <form role="form" method="post" action="save">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="Designation">Role Name</label>
              <div class="input-group">
                <input type="text" class="form-control" name="RoleName" id="RoleName" value="<?php print $data['Rec']->RoleName;?>" placeholder="Role Name" required>
                <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span></div>
            </div>
            <div class="form-group">
              <label for="Roll Description">Roll Description</label>
              <div class="input-group">
                <textarea name="RoleDescription" id="RoleDescription" class="form-control"><?php print $data['Rec']->RoleDescription;?></textarea>
                <span class="input-group-addon"></span></div>
            </div>
			
			<div class="form-group">
				<label for="Status">IsActive</label>
				<div class="input-group">
				<select name="IsActive" id="IsActive" class="form-control" required>
				<?php print $data['StatusList'];?>
				</select>
				<span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span></div>
			</div>
           
            <input type="submit" value="Save" class="btn btn-info pull-right">
          </div>
          <input type="hidden" name="id" value="<?php print $this->data['Rec']->Role_ID;?>" />
        </form>
		
      </div>
    </div>
  </div>
</div>
