<?php $session=new Zend\Session\Container('admin');
if($session->offsetGet('adminuser')==''){
	$bashPath=$this->basePath();
	$location="Location:".$bashPath."/admin";
 	header($location);	
	exit;	
 } ?>
<div id="page-wrapper" >
  <h4 style="">Local Package</h4>
  <div>
    <div class="portlet portlet-default">
      <div class="portlet-heading">
        <div class=" "> <i class="fa fa-filter" style="float: left;margin:7px;color:#3D84C1;"></i>
          <h6 style="background: #E2E2E2;padding:7px;margin: 0;">Filter</h6>
          <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
      </div>
	  
	  <div class="portlet-body">
		<ul id="myTab" class="nav nav-tabs">
			<li class="active"><a href="#role" data-toggle="tab"><i class="fa fa-list" style="color:#; margin:5px"></i>Local Package</a></li>
		</ul>
	
<div id="myTabContent" class="tab-content clearfix">
	<div class="tab-pane fade in active" id="role">
	<div class="container col-sm-col-sm-offset-1" style="margin: 20px auto 8px !important;padding: 0 10px;">
		<div class="row">
		<div class="form-group clearfix margintopbottom20">
			<label id="flight_nos" class="col-sm-2 control-label labelalign">Id</label>
			<div class="col-sm-4">
			<input id="groupId" type="text" class=" form-control inputchange" placeholder="Driver group ids">                                    
			</div>

			<label id="point_airport" class="col-sm-2 control-label labelalign">Vehicle</label>
			<div class="col-sm-4">
			<input id="groupVehicle" type="text" class=" form-control inputchange" placeholder="Id or license plate">     
			</div>
		</div>
		</div>
	</div>
	</div>

	<div class="col-sm-4 pull-right" style="margin-bottom:15px; padding-left:0;">
		<a href="#" class="btn btn-red defaultbtnsearch" id="vsearch"><i class="fa fa-search" style="color:#fff; margin:5px"></i>Search</a>
		<a href="#" class="btn btn-red defaultbtnsearch"><i class="fa fa-times" style="color:#fff; margin:5px"></i>Clear</a>                                  
	</div>


</div>

</div>
      <!-- /.portlet-body --> 
    </div>
    <!-- /.portlet --> 
  </div>
  <div class="table-responsive" >
 <!--<a href="<?php print site_url;?>/admin/role/add" class="btn btn-default marginright"><i class="fa fa-user marginright"></i>Add Local Package</a>-->
    <table id="designation" class="table table-striped">
      <thead>
        <tr>
          <th>Sr.No.</th>
          <th>Package</th>
		  <th>Sub-Package</th>
          <th>Hrs</th>
		  <th>Km</th>
		  <th>Price</th>
		  <th>Cab Type</th>
          <th>Status</th>
          <!--<th>Action</th>-->
        </tr>
      </thead>
    </table>
    <div class="col-sm-12 marginbottom20"> </div>
  </div>
</div>
<script>
$('#designation').dataTable(<?php print $this->data;?>);
</script> 
