<?php $session=new Zend\Session\Container('admin');
if($session->offsetGet('adminuser')==''){
	$bashPath=$this->basePath();
	$location="Location:".$bashPath."/admin";
 	header($location);	
	exit;	
 } ?><!-- Navigation -->

    
    <div id="page-wrapper" >
	
	<div>

                        <div class="portlet portlet-default">
                            <div class="portlet-heading">
                                <div class=" ">
                                 
                                    <i class="fa fa-filter" style="float: left;margin:7px;color:#3D84C1;"></i>
									<h6 style="background: #E2E2E2;padding:7px;margin: 0;">Filter</h6>
                                
                                <div class="clearfix"></div>
                            </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="portlet-body">
                                <ul id="myTab" class="nav nav-tabs">
                                    <li class="active"><a href="#drivergroup" data-toggle="tab"><i class="fa fa-list" style="color:#; margin:5px"></i>Drivers Group</a>
                                    </li>
                                    <li><a href="#driverSearch" data-toggle="tab"><i class="fa fa-user" style="color:#; margin:5px"></i>Drivers</a>
                                    </li>
                                    <li>
                                        <a href="#vehicleSearch" class="dropdown-toggle" data-toggle="tab"><i class="fa fa-user" style="color:#; margin:5px"></i>Vehicles</a>
                                     </li>
                                     
                                     
									
                                </ul>
                                <div id="myTabContent" class="tab-content clearfix">
                                    <div class="tab-pane fade in active" id="drivergroup">
                                        <div class="container col-sm-col-sm-offset-1" style="margin: 20px auto 8px !important;padding: 0 10px;">
										<div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign">Id</label>
                                                  <div class="col-sm-4">
                      <input id="groupId" type="text" class=" form-control inputchange" placeholder="Driver group ids">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Vehicle</label>
                                                   <div class="col-sm-4">
                         <input id="groupVehicle" type="text" class=" form-control inputchange" placeholder="Id or license plate">     
                                                    </div>
                                                 </div>
                                             </div>
											 
											 <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign">Name</label>
                                                  <div class="col-sm-4">
												  
                 <input id="groupName" type="text" class=" form-control inputchange" placeholder="Driver group name">                                    
                                                  </div>
                                                                                                   
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Vehicle external reference</label>
                                                   <div class="col-sm-4">
                                                        <div class="input-group">
 													<input id="groupExt" type="text" class="form-control inputchange" placeholder="Vehicle external reference">
													<span class="input-group-addon"><i class="fa fa-search"></i></span>   
                                                </div> 
                                                    </div>
                                                 </div>
                                             </div>
											  <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign"></label>
                                                  <div class="col-sm-2">
                                                     <input id=" " type="hidden" class=" form-control inputchange" placeholder="Since">                                    
                                                  </div>
												   <div class="col-sm-2">
                                                     <input id=" " type="hidden" class=" form-control inputchange" placeholder="To">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Driver</label>
                                                   <div class="col-sm-4">
						<div class="input-group">
 <input type="text" id="groupDname" class="form-control inputchange" placeholder="Driver">
			<span class="input-group-addon"><i class="fa fa-search"></i></span>   
                                                </div> 
                                                            
                                                    </div>
                                                                                                    
                                                                                                    
                                                                                                    
                                                 </div>
                                                                                              <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign"></label>
                                                  <div class="col-sm-2">
                                                     <input id=" " type="hidden" class=" form-control inputchange" placeholder="Since">                                    
                                                  </div>
												   <div class="col-sm-2">
                                                     <input id=" " type="hidden" class=" form-control inputchange" placeholder="To">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Driver external reference</label>
                                                   <div class="col-sm-4">
						<div class="input-group">
 <input type="text" id="groupDExt" class="form-control inputchange" placeholder="Driver external reference">
			<span class="input-group-addon"><i class="fa fa-search"></i></span>   
                                                </div> 
                                                            
                                                    </div>
                                                                                                    
                                                                                                    
                                                                                                    
                                                 </div>
                                             </div>
											   <div class="row">
<!--                                                <div class="form-group clearfix margintopbottom20">
												 
                                                  <div class="col-sm-4 pull-right">
                                                     <a href="#" class="btn btn-red defaultbtnsearch"><i class="fa fa-search" style="color:#fff; margin:5px"></i>Search</a>
													 <a href="#" class="btn btn-red defaultbtnsearch"><i class="fa fa-times" style="color:#fff; margin:5px"></i>Clear</a>                                  
                                                  </div>
												  
												   
                                                 
 												    
                                                  
                                                 </div>-->
                                             </div>
											 
											 
											 
											 
										</div>
                                    </div>
                                    <div class="tab-pane fade" id="driverSearch">
                                          <div class="tab-pane fade in active" id="home">
                                        <div class="container col-sm-col-sm-offset-1" style="margin: 20px auto 8px !important;padding: 0 10px;">
										<div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign">Id</label>
                                                  <div class="col-sm-4">
                                                     <input id="driverSearchId" type="text" class=" form-control inputchange" placeholder="Driver Id">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Vehicle</label>
                                                   <div class="col-sm-4">
                                                         <input id="driverSearchVehicle" type="text" class=" form-control inputchange" placeholder="Id or license plate">     
                                                    </div>
                                                 </div>
                                             </div>
											 
											 <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign">Name</label>
                                                  <div class="col-sm-4">
												  
                                                     <input id="driverSearchName" type="text" class=" form-control inputchange" placeholder="Driver Name">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Vehicle External Reference</label>
                                                   <div class="col-sm-4">
                                                        <div class="input-group">
 													<input id="driverSearchExt" type="text" class="form-control inputchange" placeholder="Vehicle External Reference">
													<span class="input-group-addon"><i class="fa fa-search"></i></span>   
                                                </div> 
                                                    </div>
                                                 </div>
                                             </div>
											  <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign"></label>
                                                  <div class="col-sm-2">
                                                     <input id=" " type="hidden" class=" form-control inputchange" placeholder="Since">                                    
                                                  </div>
												   <div class="col-sm-2">
                                                     <input id=" " type="hidden" class=" form-control inputchange" placeholder="To">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Driver</label>
                                                   <div class="col-sm-4">
												     <div class="input-group">
 													<input type="text" id="driverSearchDriver" class="form-control inputchange" placeholder="Driver">
													<span class="input-group-addon"><i class="fa fa-search"></i></span>   
                                                </div> 
                                                            
                                                    </div>
                                                 </div>
                                                                                              
                                                                                               <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign"></label>
                                                  <div class="col-sm-2">
                                                     <input id=" " type="hidden" class=" form-control inputchange" placeholder="Since">                                    
                                                  </div>
												   <div class="col-sm-2">
                                                     <input id=" " type="hidden" class=" form-control inputchange" placeholder="To">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Driver External Reference</label>
                                                   <div class="col-sm-4">
												     <div class="input-group">
 													<input type="text" id="driverSearchExternal" class="form-control inputchange" placeholder="Driver External Reference">
													<span class="input-group-addon"><i class="fa fa-search"></i></span>   
                                                </div> 
                                                            
                                                    </div>
                                                 </div>
                                             </div>
											   <div class="row">
<!--                                                <div class="form-group clearfix margintopbottom20">
												 
                                                  <div class="col-sm-4 pull-right">
                                                     <a href="#" class="btn btn-red defaultbtnsearch" id="driversearching"><i class="fa fa-search" style="color:#fff; margin:5px"></i>Search</a>
													 <a href="#" class="btn btn-red defaultbtnsearch"><i class="fa fa-times" style="color:#fff; margin:5px"></i>Clear</a>                                  
                                                  </div>
												  
												   
                                                 
 												    
                                                  
                                                 </div>-->
                                             </div>
											 
											 
											 
											 
										</div>
                                    </div>
                                    </div>
                                    <div class="tab-pane fade" id="vehicleSearch">
                                          <div class="tab-pane fade in active" id="home">
                                        <div class="container col-sm-col-sm-offset-1" style="margin: 20px auto 8px !important;padding: 0 10px;">
										<div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign">License Plate</label>
                                                  <div class="col-sm-4">
                          <input id="vlPlate" type="text" class=" form-control inputchange" placeholder="License Plate">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Make</label>
                                                   <div class="col-sm-4">
                                <input id="vmake" type="text" class=" form-control inputchange" placeholder="Make">     
                                                    </div>
                                                 </div>
                                             </div>
											 
											 <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign">Model</label>
                                                  <div class="col-sm-4">
												  
                                     <input id="vmodel" type="text" class=" form-control inputchange" placeholder="Model">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">External Refrence</label>
                                                   <div class="col-sm-4">
                                                        <div class="input-group">
 	<input id="vEref" type="text" class="form-control inputchange" placeholder="External Refrence">
													<span class="input-group-addon"><i class="fa fa-search"></i></span>   
                                                </div> 
                                                    </div>
                                                 </div>
                                             </div>
											  
											   
											 
											 
											 
											 
										</div>
                                    </div>
                                    </div>
                                    <div class="col-sm-4 pull-right" style="margin-bottom:15px; padding-left:0;">
  <a href="#" class="btn btn-red defaultbtnsearch" id="vsearch"><i class="fa fa-search" style="color:#fff; margin:5px"></i>Search</a>
  <a href="#" class="btn btn-red defaultbtnsearch"><i class="fa fa-times" style="color:#fff; margin:5px"></i>Clear</a>                                  
                                                  </div>
                                    <div class="tab-pane fade" id="dropdown2">
                                        <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.</p>
                                        <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.</p>
                                    </div>
                                    
                                </div>
                            </div>
                            <!-- /.portlet-body -->
                        </div>
                        <!-- /.portlet -->

                    </div>
	
<!--        <div class="row" style="display:none">
                    <div class="col-lg-12">

                        <div class="portlet portlet-default">
                            <div class="portlet-heading">
                                <div class="portlet-title">
                                    <h4>Basic Tabs Example</h4>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="portlet-body">
                                <ul id="myTab" class="nav nav-tabs">
                                    <li class="active"><a href="#home" data-toggle="tab"><i class="fa fa-list" style="color:#; margin:5px"></i>General</a>
                                    </li>
                                    <li><a href="#profile" data-toggle="tab"><i class="fa fa-user" style="color:#; margin:5px"></i>Client</a>
                                    </li>
                                    <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" style="color:#; margin:5px"></i>Driver</a>
                                     </li>
									 <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-road" style="color:#; margin:5px"></i>Vehicle</a>
                                     </li>
									  <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-globe" style="color:#; margin:5px"></i>Location</a>
                                     </li>
									  <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-gear (alias)" style="color:#; margin:5px"></i>State</a>
                                     </li>
									 <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-eur" style="color:#; margin:5px"></i>Payment</a>
                                     </li>
                                </ul>
                                <div id="myTabContent" class="tab-content">
                                    <div class="tab-pane fade in active" id="home">
                                        <div class="container col-sm-col-sm-offset-1" style="margin-top:30px !important;">
										<div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign">Id</label>
                                                  <div class="col-sm-4">
                                                     <input id=" " type="text" class=" form-control" placeholder="Booking Process Id">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Vehicle Owner</label>
                                                   <div class="col-sm-4">
                                                         <input id=" " type="text" class=" form-control" placeholder="Vehicle Owner">     
                                                    </div>
                                                 </div>
                                             </div>
											 
											 <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign">Internal Id</label>
                                                  <div class="col-sm-4">
												  
                                                     <input id=" " type="text" class=" form-control" placeholder="Internal Id">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Driver</label>
                                                   <div class="col-sm-4">
                                                        <div class="input-group">
 													<input type="text" class="form-control" placeholder="Driver">
													<span class="input-group-addon"><i class="fa fa-search"></i></span>   
                                                </div> 
                                                    </div>
                                                 </div>
                                             </div>
											  <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												   <label id="flight_nos" class="col-sm-2 control-label labelalign">Initial request data</label>
                                                  <div class="col-sm-2">
                                                     <input id=" " type="text" class=" form-control" placeholder="Since">                                    
                                                  </div>
												   <div class="col-sm-2">
                                                     <input id=" " type="text" class=" form-control" placeholder="To">                                    
                                                  </div>
                                                 
 												    <label id="point_airport" class="col-sm-2 control-label labelalign">Partner</label>
                                                   <div class="col-sm-4">
												     <div class="input-group">
 													<input type="text" class="form-control" placeholder="Partner">
													<span class="input-group-addon"><i class="fa fa-search"></i></span>   
                                                </div> 
                                                            
                                                    </div>
                                                 </div>
                                             </div>
											   <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
												 
                                                  <div class="col-sm-4 pull-right">
                                                     <a href="#" class="btn btn-red"><i class="fa fa-search" style="color:#fff; margin:5px"></i>Search</a>
													 <a href="#" class="btn btn-red"><i class="fa fa-times" style="color:#fff; margin:5px"></i>Clear</a>                                  
                                                  </div>
												  
												   
                                                 
 												    
                                                  
                                                 </div>
                                             </div>
											 
											 
											 
											 
										</div>
                                    </div>
                                    <div class="tab-pane fade" id="profile">
                                        <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>
                                        <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>
                                    </div>
                                    <div class="tab-pane fade" id="dropdown1">
                                        <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>
                                        <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>
                                    </div>
                                    <div class="tab-pane fade" id="dropdown2">
                                        <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.</p>
                                        <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.</p>
                                    </div>
                                </div>
                            </div>
                             /.portlet-body 
                        </div>
                         /.portlet 

                    </div>
                     /.col-lg-12 
                </div>				-->
					
					
        <div class="table-responsive">
            
            <table id="devicemanagement" class="table table-striped table-responsive" style="width:100% !important;">
                <thead>
                    <tr>
                        <th></th>
                        <th>SNo</th>
                        <th>Unit No</th>
                        <th>Purchase Date</th>
                        <th>Activation Date</th>
                         <th>Sim No</th>
                          <th>Port</th>
                          <th>Taxi No.</th>
                          <th>Edit</th>
                       
                     
                    </tr>
                </thead>
				
				  <tbody>

                </tbody>

                <tfoot>
                    <tr>
                       <th></th>
                        <th>SNo</th>
                        <th>Unit No</th>
                        <th>Purchase Date</th>
                        <th>Activation Date</th>
                         <th>Sim No</th>
                          <th>Port</th>
                          <th>Taxi No.</th>
                          <th>Edit</th>
                    </tr>
                </tfoot>

              
                
            </table>
            <div class="col-sm-12 marginbottom20">
                
				<a href="#" class="btn btn-primary marginright" onclick="addDevice();"><i class="fa fa-envelope-o marginright"></i>Add Unit</a>
<!--				<a href="#" class="btn btn-default marginright"><i class="fa fa-download marginright"></i>Download CSV</a>
				<a href="#" class="btn btn-default marginright" onclick="signupDriver();"><i class="fa fa-user marginright"></i>SignUp a Driver</a>-->
				<a href="#" class="btn marginright defaultbtnsearch" id="delete_device"><i class="fa fa-trash-o marginright"></i>Delete</a>
            </div>
        </div>
            
    </div>

</div>

<!--<div id="driverprofile">-->

  
<div class="col-lg-12" style="display: none" id="driverprofile">
    <i class="fa fa-reply fa-1_5x backbtn" id="backbutton" onclick="backbutton();"></i>

                        <div class="portlet portlet-default">
                            <div class="portlet-heading">
                                <div class="portlet-title">
                                    <h4>Basic Tabs Example</h4>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="portlet-body">
                                <ul id="myTab" class="nav nav-tabs">
                                    <li class="active"><a href="#client" data-toggle="tab">Entity</a>
                                    </li>
                                    <li class=""><a href="#drivergroups" data-toggle="tab">Driver groups</a>
                                    </li>
                                    <li class="">
                                        <a href="#bookingfeatures" id="myTabDrop1" class="dropdown-toggle" data-toggle="tab">Booking features</a>
                                     </li>
									 <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">Bank account</a>
                                     </li>
									  <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">Certificates</a>
                                     </li>
									  <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">State</a>
                                     </li>
									 <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">SMSes</a>
                                     </li>
									 <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">Emails</a>
                                     </li>
									 <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">Status history</a>
                                     </li>
									 <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">Allocation history</a>
                                     </li>
									 <li>
                                        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">Booking history</a>
                                     </li>
                                </ul>
                                <div id="myTabContent" class="tab-content">
                                    
                  <div class="tab-pane fade active in" id="client">
                                         
					<div class="container margintop">
<!--users-->

						<div id="userRoleDriver" style="margin:20px;">
  <!--
    <form  id='frm_details' name='frm_details' method="multipart/form-data" >
    <!--<input type="file" name="UploadPhoto" id="UploadPhoto" />
		
		<img src="public/images/photo_not_available.png" id="PhotoPrev" alt="Photo Preview" />-->
    <!--left_panel_form START-->
     <!--right_panel_form START-->
    
         <div class=" col-sm-4 col-md-4 col-lg-4 clearfix userprofileimg pull-right">
         	<div id="crop-avatar">

    <!-- Current avatar -->
   
    <div class="avatar-view userimg_byratio" style="width:140px; margin:auto;" title="Profile Picture">
      <img src="public/image/default_user.png" alt="Avatar">
    </div>
 
    <!-- Cropping modal -->
    <div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <form class="avatar-form" id="0" method="post" action="public/crop-avatar.php" enctype="multipart/form-data">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">×</button>
              <h4 class="modal-title" id="avatar-modal-label">Profile Picture</h4>
            </div>
            <div class="modal-body">
              <div class="avatar-body">

                <!-- Upload image and data -->
                <div class="avatar-upload">
                  <input class="avatar-src" name="avatar_src" type="hidden">
                  <input class="avatar-data" name="avatar_data" type="hidden">
                  <label for="avatarInput">Local upload</label>
               
                  <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
                </div>

                <!-- Crop and preview -->
                <div class="row">
                  <div class="col-md-9">
                      <div class="loading" tabindex="-1" role="img" aria-label="Loading"></div>
                    <div class="avatar-wrapper"></div>
                  </div>
                  <div class="col-md-3">
                    <div class="avatar-preview preview-lg"><img src="public/image/default_user.png"></div>
                    <div class="avatar-preview preview-md"><img src="public/image/default_user.png"></div>
                    <div class="avatar-preview preview-sm"><img src="public/image/default_user.png"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
              <button class="btn btn-primary avatar-save" type="submit">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div><!-- /.modal -->

    <!-- Loading state -->
   
  </div>
             <div id="crop-vehicle center" style="width:140px; margin:auto;">

    <!-- Current avatar -->
   
    <div class="avatar-view userimg_byratio" title="Profile Picture">
        <img src="public/image/vehicle.png" alt="Avatar" style="height:140px">
    </div>
 
    <!-- Cropping modal -->
    <div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <form class="avatar-form" id="0" method="post" action="public/crop-avatar.php" enctype="multipart/form-data">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">×</button>
              <h4 class="modal-title" id="avatar-modal-label">Vehicle Picture</h4>
            </div>
            <div class="modal-body">
              <div class="avatar-body">

                <!-- Upload image and data -->
                <div class="avatar-upload">
                  <input class="avatar-src" name="avatar_src" type="hidden">
                  <input class="avatar-data" name="avatar_data" type="hidden">
                  <label for="avatarInput">Local upload</label>
                  <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
                </div>

                <!-- Crop and preview -->
                <div class="row">
                  <div class="col-md-9">
                       <div class="loading" tabindex="-1" role="img" aria-label="Loading"></div>
                    <div class="avatar-wrapper"></div>
                  </div>
                  <div class="col-md-3">
                    <div class="avatar-preview preview-lg"><img src="public/image/vehicle.png"></div>
                    <div class="avatar-preview preview-md"><img src="public/image/vehicle.png"></div>
                    <div class="avatar-preview preview-sm"><img src="public/image/vehicle.png"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
              <button class="btn btn-primary avatar-save" type="submit">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div><!-- /.modal -->

    <!-- Loading state -->
   
  </div>
		
		<h3><center>Management</center></h3>
<center><div class="btn defaultbtnsearch ">Send SMS</div></center>
<h3><center>Current Status</center></h3>
<input type="text" id="driverStatus" name="dName" aria-controls="driver" class="form-control input-sm" disabled>
<!--<center>
    <select name="driver_length" aria-controls="driver" class="form-control input-sm" disabled>
        <option value="10">Online</option>
        <option value="10">Offline</option></select>
</center>-->
<h3><center>Management</center></h3>
<center>
    <select name="driver_length" aria-controls="driver" class="form-control input-sm">
        <option value="10">Register</option>
        <option value="10">Register</option>
    </select>
</center>

        </div>
     <form id="driver_form_details" name="frm_details" method="multipart/form-data">
         <div class="col-sm-8 col-md-8 col-lg-8 clearfix">
             <input type="hidden" id="image_path0" name="image_path" value="">  	
           <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Id<span class="mandat_star">*</span></label>
            <input type="text" id="" name="" class="driver_name col-mg-7 col-lg-7 inputfild name idsdriver" disabled>
            <input type="hidden" id="driverIds" name="driverIds" class="driver_name col-mg-7 col-lg-7 inputfild name idsdriver" >
           </div>
           <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Unique Id<span class="mandat_star">*</span></label>
            <input type="text" id="driver_email" name="unique_id" class="col-mg-7 col-lg-7 inputfild name">
			 
           </div>
           <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">External Reference<span class="mandat_star">*</span></label>
            <input type="text" id="autocomplete" name="city" class="col-mg-7 col-lg-7 inputfild name"  placeholder="External Reference" autocomplete="off">
           </div>
           <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Created on</label>
            <label class=" col-mg-7 col-lg-7 phno"><span id="createdDate"></span></label>
            
           </div>
           <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Boss of driver group<span class="mandat_star">*</span></label>
             <label class=" col-mg-7 col-lg-7 phno" id="vName">-</label>
           </div>
           <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">First name<span class="mandat_star">*</span></label>
            <input type="text" id="driver_firstName" name ="driver_firstName" class="col-mg-7 col-lg-7 inputfild name">
           </div>
           <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Last name<span class="mandat_star">*</span></label>
            <input type="text" id="driver_lastName" name="driver_lastName" class="col-mg-7 col-lg-7 inputfild name">
           </div>
            <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Email<span class="mandat_star">*</span></label>
             <input type="text" id="email_driver" name="email_driver" class="col-mg-7 col-lg-7 inputfild name">
           </div>
             
           <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Email verified <span class="mandat_star">*</span></label>
       		<input type="checkbox" value="" id="emailVerify" name="emailVerify" class="form-control inputsize hello42">
           </div>
		      
           <div class="form-group clearfix spance">
            <label class="control-label col-lg-5"><span class="mandat_star">username</span></label>
  <input type="text" class="col-lg-7 inputfild name vechile_name ui-autocomplete-input" id="driver_username" name="driver_username" autocomplete="off" onblur="usernameCheck();">
 
           </div>
<!--           <div class="form-group clearfix spance">
               <label class="control-label col-lg-5">Password<span class="mandat_star">*</span></label>
            <input type="text" class="col-lg-7 inputfild name" id="driverMakeVec" name="driverMakeVec">
           </div>-->
           <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Default language<span class="mandat_star">*</span></label>
            <input type="text" class="col-lg-7 inputfild name" id="driverModel" >
           </div>
           
           <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Gender<span class="mandat_star">*</span></label>
            <input type="text" class="col-lg-7 inputfild name" id="driverBadge" >
           </div>
             <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Date of birth<span class="mandat_star">*</span></label>
            <input type="text" class="col-lg-7 inputfild name" id="driverBadge" >
           </div>
           <div class="form-group clearfix spance" style="margin-bottom: 4px;">
            <label class="control-label col-lg-5">Terms acceted on<span class="mandat_star">*</span></label>
           <label class=" col-mg-7 col-lg-7 phno">-</label>
            </div>
            
            <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Has account<span class="mandat_star">*</span></label>
            <label class=" col-mg-7 col-lg-7 phno">-</label>
           </div>
           <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Address<span class="mandat_star">*</span></label>
            <input type="text" id="driver_add" name="driver_adds" class="col-lg-7 inputfild name">
           </div>
             <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Office Address<span class="mandat_star">*</span></label>
            <input type="text" id="driver_addofc" name="driver_addofc" class="col-lg-7 inputfild name" >
           </div>
		    <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Phone number<span class="mandat_star">*</span></label>
            <input type="text" id="driver_phone" name="driver_phone" class="col-lg-7 inputfild name">
           </div>
		    <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Phone number verified<span class="mandat_star">*</span></label>
            <input type="checkbox" value="" name="verify" id="phoneverify" class="form-control inputsize hello42">
           </div>
		   <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Vat Number<span class="mandat_star">*</span></label>
            <input type="text" id="driverAmount"  class="col-lg-7 inputfild name" placeholder="Vat Number">
           </div>
             
             
              <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Pan Card Details<span class="mandat_star">*</span></label>
            <input type="text" id="driver_panNos" name="driver_panNos" class="col-lg-7 inputfild name" >
           </div>
              <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Badge / License No.<span class="mandat_star">*</span></label>
            <input type="text" id="driver_licence" name="driver_licence" class="col-lg-7 inputfild name" >
           </div>
             <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Vehicle No.<span class="mandat_star">*</span></label>
            <input type="text" id="driver_vehicleNo" name="driver_vehicleNo" class="col-lg-7 inputfild name" >
           </div>
             <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Security Amount<span class="mandat_star">*</span></label>
<!--            <input type="text" id="" name="" class="col-lg-7 inputfild name samount" disabled>-->
            <input type="text" id="" name="driver_amount" class="col-lg-7 inputfild name samount" >
           </div>
		   <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Current vehicle<span class="mandat_star">*</span></label>
            <label class=" col-mg-7 col-lg-7 phno" id="vehicleid">-</label>
           </div>
<!--		   <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Is active<span class="mandat_star">*</span></label>
            <input type="checkbox" style="float: left;margin-right: 60px;" id="isActive" value="" name="driver_isActive" class="form-control inputsize activedriver">
             <input type="checkbox" style="float: left;margin-right: 60px;" id="isActive" value="" name="driver_isActive" class="form-control inputsize activedriver">
              <input type="checkbox" style="float: left;margin-right: 60px;" id="isActive" value="" name="driver_isActive" class="form-control inputsize activedriver">
            
            
           </div>
                <div class="form-group clearfix spance">
            <label class="control-label col-lg-5"></label>
            <label class=" col-mg-7 col-lg-7 phno"  id="vehicleid">Active</label>
            <label class=" col-mg-7 col-lg-7 phno"   id="vehicleid">Block</label>
            <label class=" col-mg-7 col-lg-7 phno"  id="vehicleid">Barred</label>
           </div>-->
        <div class="form-group clearfix spance" style="margin-bottom: 4px;">
            <label class="control-label col-lg-5">Driver Status<span class="mandat_star">*</span></label>
            <div class="">
            <label class="radio-inline specs">
                <input type="radio" id="isActive" name="driver_isActive" value="1" checked="" required="" class="activedriver">Active
           </label>
           <label class="radio-inline specs" style="padding-left:47px !important;">
           <input type="radio" id="isBlock" name="driver_isActive" value="2" required="" class="blockdriver">Block
           </label>
                <label class="radio-inline specs" style="padding-left:47px !important;">
           <input type="radio" id="isBarred" name="driver_isActive" value="3" required="" class="barreddriver">Barred
           </label>
           </div>
            </div>
<div class="form-group clearfix spance">
            <label class="control-label col-lg-5"></label>
            
           </div>
<div class="form-group clearfix spance">
            <label class="control-label col-lg-5"></label>
            
           </div>
		    <div class="form-group clearfix spance">
            <h3 class="control-label col-lg-5" style="margin:0;">Comments</h3>
            </div>
			 <hr>
			 <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Signup comment<span class="mandat_star">*</span></label>
            <textarea rows="3" id="driver_signup_comts" name="driver_signup_comts" cols="5" class="col-lg-7 inputfild name"></textarea>
           </div>
		   <div class="form-group clearfix spance">
            <label class="control-label col-lg-5">Internal comment<span class="mandat_star">*</span></label>
           <textarea rows="3" id="driver_internal_comts" name="driver_internal_comts" cols="5" class="col-lg-7 inputfild name"></textarea>
           </div>
		   
		    <div class="form-group clearfix spance">
              
                  <button type="button" class="btn defaultbtnsearch pull-right" onclick="backbutton();">Back</button> 
	<button type="button" class="btn defaultbtnsearch pull-right" style="margin-right:10px;" onclick="update_driver();">Update</button> 
           </div>
		   
          </div>
		    
		    
        
  
           
            <!--bottom part checkbox of form End-->
           
         </form>
    </div>																													
                
                
         <div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Confirmation</h4>
            </div>
            <div class="modal-body">
                <p>An Confirmation Email has been sent on your account</p>
                <p class="text-warning"><small></small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                
            </div>
        </div>
    </div>
 
</div>
       
              
<div class="clearfix"></div>
<!-- End Signup for users-->





<!-- End Signup for users-->

      
          
        </div>
										 
                                    </div>

						<!--Driver Group START-->
                                    <div class="tab-pane fade" id="drivergroups">
                                       
									  <div class="col-sm-6 clearfix" style="margin: 30px auto 20px;padding: 0;">
									   	<label class="col-sm-2">Driver group</label>
										<div class="col-sm-7">
										<input type="text" class="form-control">
										</div>
										<a href="#" class="btn btn-success col-sm-3">Add</a>
									   </div>
									   
									 <table class="table">
 										 <thead>
										 <tr>
										 	<th>Group name</th>
											<th>Action</th>
 										</tr>
										</thead>
										<tbody>
											<tr>
												<td><a href="#">Driver Copenhagen Default</a></td>
												<td><a href="#" class="btn defaultbtnsearch  col-sm-4">Remove</a></td>
											</tr>
										</tbody>
									 </table>
										 
                                    </div>
 						<!--Driver Group END-->	
						
						<!--Booking features Start-->
							 <div class="tab-pane fade clearfix" id="bookingfeatures">
                                       
									  <div class="col-sm-6  clearfix" style="margin: 30px auto 20px;padding: 0;">
									   	<label class="col-sm-2">Add Booking</label>
										<div class="col-sm-9">
										 <select name="driver_length" aria-controls="driver" class="form-control input-sm">
										 <option value="10">select</option>
										 <option value="10">Shopping</option>
										  <option value="10">English Language</option>
										   <option value="10">Transportation atient</option>
										    <option value="10">Assist General</option>
											 <option value="10">Assist Shopping Pharmacy</option>
											  <option value="10">Assist Shopping With Expenses</option>
										 </select>
										</div>
										 
									   </div>
									   <div class="col-sm-6  " style="margin: 30px auto 20px;padding: 0;">
									   	<label class="col-sm-2">Add Booking</label>
										<div class="col-sm-9">
										 <select name="driver_length" aria-controls="driver" class="form-control input-sm">
										 <option value="10">select</option>
										 <option value="10">Shopping</option>
										  <option value="10">English Language</option>
										   <option value="10">Transportation atient</option>
										    <option value="10">Assist General</option>
											 <option value="10">Assist Shopping Pharmacy</option>
											  <option value="10">Assist Shopping With Expenses</option>
										 </select>
										</div>
										 
									   </div>
									   </div>
						<!--Booking features End-->
						
						
									
									
                                </div>
                            </div>
                            <!-- /.portlet-body -->
                        </div>
                        <!-- /.portlet -->

                    </div>


<!--//////////////////////bpop up//////////////////-->



<!--//////////////////////end bpop up//////////////////-->

<!-- ///////////////////////device signup form ////////////////////////-->

<div class="col-sm-6 col-sm-offset-3" id="device_signup_form" style="display:none;background-color: white; padding: 0; border-radius:10px; margin:auto;">
<!--users-->
<h1 class="fa fa-times closbtn b-close"></h1>

<div id="userRoleDriver" style="margin:20px;" >
 
    
         <div class=" col-sm-3 col-md-3 col-lg-3 clearfix userprofileimg pull-right">
         	<div id="crop-avatar">

    <!-- Current avatar -->
   
    <div class="avatar-view userimg_byratio" title="Profile Picture">
      <img src="public/image/default_user.png" alt="Avatar">
    </div>
 
    <!-- Cropping modal -->
    <div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <form class="avatar-form" id="0" method="post" action="public/crop-avatar.php" enctype="multipart/form-data">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">×</button>
              <h4 class="modal-title" id="avatar-modal-label">Profile Picture</h4>
            </div>
            <div class="modal-body">
              <div class="avatar-body">

                <!-- Upload image and data -->
                <div class="avatar-upload">
                  <input class="avatar-src" name="avatar_src" type="hidden">
                  <input class="avatar-data" name="avatar_data" type="hidden">
                  <label for="avatarInput">Local upload</label>
               
                  <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
                </div>

                <!-- Crop and preview -->
                <div class="row">
                  <div class="col-md-9">
                      <div class="loading" tabindex="-1" role="img" aria-label="Loading"></div>
                    <div class="avatar-wrapper"></div>
                  </div>
                  <div class="col-md-3">
                    <div class="avatar-preview preview-lg"><img src="public/image/default_user.png"></div>
                    <div class="avatar-preview preview-md"><img src="public/image/default_user.png"></div>
                    <div class="avatar-preview preview-sm"><img src="public/image/default_user.png"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
              <button class="btn btn-primary avatar-save" type="submit">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div><!-- /.modal -->

    <!-- Loading state -->
   
  </div>
             <div id="crop-vehicle">

    <!-- Current avatar -->
   
    <div class="avatar-view userimg_byratio" title="Profile Picture">
        <img src="public/image/vehicle.png" alt="Avatar" style="height:140px">
    </div>
 
    <!-- Cropping modal -->
    <div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <form class="avatar-form" id="0" method="post" action="public/crop-avatar.php" enctype="multipart/form-data">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">×</button>
              <h4 class="modal-title" id="avatar-modal-label">Vehicle Picture</h4>
            </div>
            <div class="modal-body">
              <div class="avatar-body">

                <!-- Upload image and data -->
                <div class="avatar-upload">
                  <input class="avatar-src" name="avatar_src" type="hidden">
                  <input class="avatar-data" name="avatar_data" type="hidden">
                  <label for="avatarInput">Local upload</label>
                  <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
                </div>

                <!-- Crop and preview -->
                <div class="row">
                  <div class="col-md-9">
                       <div class="loading" tabindex="-1" role="img" aria-label="Loading"></div>
                    <div class="avatar-wrapper"></div>
                  </div>
                  <div class="col-md-3">
                    <div class="avatar-preview preview-lg"><img src="public/image/vehicle.png"></div>
                    <div class="avatar-preview preview-md"><img src="public/image/vehicle.png"></div>
                    <div class="avatar-preview preview-sm"><img src="public/image/vehicle.png"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
              <button class="btn btn-primary avatar-save" type="submit">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div><!-- /.modal -->

    <!-- Loading state -->
   
  </div>
        </div>
    <form id="frm_details_device" name="frm_details" method="multipart/form-data">
         <div class="col-sm-8 col-md-8 col-lg-8 clearfix spacepadding0">
             <input type="hidden" id="image_path0" name="image_path" value="">  	
             <div class="form-group clearfix spance" id="signup_unit" >
            <label class="control-label col-mg-5 col-lg-5">Unit No<span class="mandat_star">*</span></label>
            <input type="text" id="driver_name" name="device_unitno" class="driver_name col-mg-7 col-lg-7 inputfild name">
           </div>
             
             <!--device unit-->
             
             <!-- end device unit-->
             
           <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Purchase Date<span class="mandat_star">*</span></label>
            <input type="text" name="device_pdate" id="device_pdateR" class="col-mg-7 col-lg-7 inputfild name">
<!--			<input type="hidden" id="driver_email2" name="driver_email" class="col-mg-7 col-lg-7 inputfild" value="">-->
           </div>
             <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Activation Date<span class="mandat_star">*</span></label>
            <input type="text" name="device_adate" id="device_adateR" class="col-mg-7 col-lg-7 inputfild name">
<!--			<input type="hidden" id="driver_email2" name="driver_pass" class="col-mg-7 col-lg-7 inputfild" value="">-->
           </div>
           <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Sim No.<span class="mandat_star">*</span></label>
            <input type="text" id="" name="device_sim" class="col-mg-7 col-lg-7 inputfild name"  placeholder="" autocomplete="off">
           </div>
           <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Port No.<span class="mandat_star">*</span></label>
          <input type="text" id="" name="device_portno" class=" col-mg-7 col-lg-7 inputfild phno">

           </div>
             <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Taxi No.<span class="mandat_star">*</span></label>
          <input type="text" id="taxi_nos" name="term" class=" col-mg-7 col-lg-7 inputfild phno">
          <input type="hidden" id="taxi_nos_id" name="device_taxi" class=" col-mg-7 col-lg-7 inputfild phno">

           </div>

            
            
          </div>
     <!--left_panel_form END-->
    
    
      
      <!--bottom part checkbox of form-->
        
           <!--New user form-->
               
               	            
           <div id="append">  </div>
          <div class="row"> 
           <div class="portlet-heading add_new">
                                        <div class="portlet-title pull-right">
                                            <h4></h4>
                                        </div>
                                        <div class="portlet-widgets pull-left">
                                            <a data-toggle="collapse" data-parent="#accordion" href="" class="newclick">
                                            <i class="fa fa-plus fa_2x" style="
    font-size: 1.5em;
    color: #fff;
"></i></a>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
          </div>
           
           <!--New user form End-->
           
           
           
           
           
           
           
           
            <!--bottom part checkbox of form End-->
            <div class="row">
                
                <div class="col-lg-12"  >
                      <a href="#" class="btn marginright btn-primary pull-right col-sm-3" onclick="deviceRegAdmin();">Register</a>
                   </div>
                  
                
            </div>
            

         </form>
    </div>     
                
                
         
       
              
<div class="clearfix"></div>
<!-- End Signup for users-->





<!-- End Signup for users-->





      
            
        </div>

<!-- //////////////////////////////////////end of driver signup form.......................-->
<form id="device_form212" style="display:none ">
        <!--Login START-->
		<div class="container leftbox"  >
   <div class="col-sm-4 col-sm-offset-4" style="background: #fff;border-radius:10px;">
  <h1 class="fa fa-times closbtn b-close"></h1>
				<div class="row text-center">
					<div class="col-md-12">
						<div class="exit_iconbox">
							 
                                     <i class="fa fa-thumbs-up fa-fw fa-5x" style="line-height: 120px;color: #4298D7;"></i>
                               

						</div>
					</div><div class="clearfix"></div>
				</div>
 			<div class="row text-center">
             
				<div class="col-sm-12" style="padding:0 10px;">
 					<div class="col-sm-12 ">
                    
						 
                            <div class="spance">
							 	<h4 style="padding:0; margin:0 auto 30px; text-transform: capitalize;">Are you want to delete drivers.</h4>
							</div>
							<div style="padding-bottom:20px;" class="clearfix">
                            <div class="col-sm-6">
 									 <a href="#" class="btn btn-default col-sm-12 b-close" id="conformation">OK</a>
							</div>
							<div class="col-sm-6">
									 <a href="#" class="btn btn-danger col-sm-12 b-close">NO</a>

  						</div>
						</div>
				</div>
			</div>
  </div>
  </div>

</div>
        <!--Login END--> 
        </form> 






<!--/////////////device update///////////////-->
<div class="col-sm-6 col-sm-offset-3" id="device_update_form" style="display:none;background-color: white; padding: 0; border-radius:10px; margin:auto;">
<!--users-->
<h1 class="fa fa-times closbtn b-close"></h1>

<div id="userRoleDriver" style="margin:20px;" >
 
    
         <div class=" col-sm-3 col-md-3 col-lg-3 clearfix userprofileimg pull-right">
         	<div id="crop-avatar">

    <!-- Current avatar -->
   
    <div class="avatar-view userimg_byratio" title="Profile Picture">
      <img src="public/image/default_user.png" alt="Avatar">
    </div>
 
    <!-- Cropping modal -->
    <div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <form class="avatar-form" id="0" method="post" action="public/crop-avatar.php" enctype="multipart/form-data">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">×</button>
              <h4 class="modal-title" id="avatar-modal-label">Profile Picture</h4>
            </div>
            <div class="modal-body">
              <div class="avatar-body">

                <!-- Upload image and data -->
                <div class="avatar-upload">
                  <input class="avatar-src" name="avatar_src" type="hidden">
                  <input class="avatar-data" name="avatar_data" type="hidden">
                  <label for="avatarInput">Local upload</label>
               
                  <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
                </div>

                <!-- Crop and preview -->
                <div class="row">
                  <div class="col-md-9">
                      <div class="loading" tabindex="-1" role="img" aria-label="Loading"></div>
                    <div class="avatar-wrapper"></div>
                  </div>
                  <div class="col-md-3">
                    <div class="avatar-preview preview-lg"><img src="public/image/default_user.png"></div>
                    <div class="avatar-preview preview-md"><img src="public/image/default_user.png"></div>
                    <div class="avatar-preview preview-sm"><img src="public/image/default_user.png"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
              <button class="btn btn-primary avatar-save" type="submit">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div><!-- /.modal -->

    <!-- Loading state -->
   
  </div>
             <div id="crop-vehicle">

    <!-- Current avatar -->
   
    <div class="avatar-view userimg_byratio" title="Profile Picture">
        <img src="public/image/vehicle.png" alt="Avatar" style="height:140px">
    </div>
 
    <!-- Cropping modal -->
    <div class="modal fade" id="avatar-modal" tabindex="-1" role="dialog" aria-labelledby="avatar-modal-label" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <form class="avatar-form" id="0" method="post" action="public/crop-avatar.php" enctype="multipart/form-data">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">×</button>
              <h4 class="modal-title" id="avatar-modal-label">Vehicle Picture</h4>
            </div>
            <div class="modal-body">
              <div class="avatar-body">

                <!-- Upload image and data -->
                <div class="avatar-upload">
                  <input class="avatar-src" name="avatar_src" type="hidden">
                  <input class="avatar-data" name="avatar_data" type="hidden">
                  <label for="avatarInput">Local upload</label>
                  <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
                </div>

                <!-- Crop and preview -->
                <div class="row">
                  <div class="col-md-9">
                       <div class="loading" tabindex="-1" role="img" aria-label="Loading"></div>
                    <div class="avatar-wrapper"></div>
                  </div>
                  <div class="col-md-3">
                    <div class="avatar-preview preview-lg"><img src="public/image/vehicle.png"></div>
                    <div class="avatar-preview preview-md"><img src="public/image/vehicle.png"></div>
                    <div class="avatar-preview preview-sm"><img src="public/image/vehicle.png"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
              <button class="btn btn-primary avatar-save" type="submit">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div><!-- /.modal -->

    <!-- Loading state -->
   
  </div>
        </div>
    <form id="frm_update_device" name="frm_details" method="multipart/form-data">
         <div class="col-sm-8 col-md-8 col-lg-8 clearfix spacepadding0">
             <input type="hidden" id="image_path0" name="image_path" value="">  	
             <div class="form-group clearfix spance" id="signup_unit" style="display:none">
            <label class="control-label col-mg-5 col-lg-5">Unit No<span class="mandat_star">*</span></label>
            <input type="text" id="driver_name" name="device_unitno" class="driver_name col-mg-7 col-lg-7 inputfild name">
           </div>
             
             <!--device unit-->
             <div class="form-group clearfix spance" id="update_unit" style="display:none">
            <label class="control-label col-mg-5 col-lg-5">Unit No<span class="mandat_star">*</span></label>
            <input type="text" id="driver_name" name="" class="driver_name col-mg-7 col-lg-7 inputfild name unitnos" disabled>
            <input type="hidden" id="driver_name" name="device_unitno_update" class="driver_name col-mg-7 col-lg-7 inputfild name unitnos">
           </div>
             <!-- end device unit-->
             
           <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Purchase Date<span class="mandat_star">*</span></label>
            <input type="text" name="device_pdate" id="device_pdate" class="col-mg-7 col-lg-7 inputfild name">
<!--			<input type="hidden" id="driver_email2" name="driver_email" class="col-mg-7 col-lg-7 inputfild" value="">-->
           </div>
             <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Activation Date<span class="mandat_star">*</span></label>
            <input type="text" name="device_adate" id="device_adate" class="col-mg-7 col-lg-7 inputfild name">
<!--			<input type="hidden" id="driver_email2" name="driver_pass" class="col-mg-7 col-lg-7 inputfild" value="">-->
           </div>
           <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Sim No.<span class="mandat_star">*</span></label>
            <input type="text" id="device_sim" name="device_sim" class="col-mg-7 col-lg-7 inputfild name"  placeholder="" autocomplete="off">
           </div>
           <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Port No.<span class="mandat_star">*</span></label>
          <input type="text" id="device_portno" name="device_portno" class=" col-mg-7 col-lg-7 inputfild phno">
<!--            <input type="hidden" pattern="[0-9]{10,10}" title="Enter valid Mobile No" id="driver_no2" name="dNo" class=" col-mg-7 col-lg-7 inputfild" value="4587963210">-->
           </div>
             <div class="form-group clearfix spance">
            <label class="control-label col-mg-5 col-lg-5">Taxi No.<span class="mandat_star">*</span></label>
          <input type="text" id="taxi_nosUpdate" name="term" class=" col-mg-7 col-lg-7 inputfild phno">
          <input type="hidden" id="taxi_nos_idUpdate" name="device_taxiUpdate" class=" col-mg-7 col-lg-7 inputfild phno">

           </div>

            
          </div>
     <!--left_panel_form END-->
    
    
      
      <!--bottom part checkbox of form-->
      
          
           <!--New user form-->
               
               	            
           <div id="append">  </div>
          <div class="row"> 
           <div class="portlet-heading add_new">
                                        <div class="portlet-title pull-right">
                                            <h4></h4>
                                        </div>
                                        <div class="portlet-widgets pull-left">
                                            <a data-toggle="collapse" data-parent="#accordion" href="" class="newclick">
                                            <i class="fa fa-plus fa_2x" style="
    font-size: 1.5em;
    color: #fff;
"></i></a>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
          </div>
           
           <!--New user form End-->
           
           
           
           
           
           
           
           
            <!--bottom part checkbox of form End-->
            <div class="row">
                
                <div class="col-lg-12" id="edit_device" style="display: none">
                      <a href="#" class="btn marginright btn-primary pull-right col-sm-3" onclick="deviceRegAdmin();">Register</a>
                   </div>
                  
                <div class="col-lg-12" id="update_device" style="display: none">
                     
                 <a href="#" class="btn marginright btn-primary pull-right col-sm-3" onclick="deviceupdateAdmin();">Update</a>
                </div>
            </div>
            

         </form>
    </div>     
                
                
         
       
              
<div class="clearfix"></div>
<!-- End Signup for users-->





<!-- End Signup for users-->





      
            
        </div>
<!-- device update form end/////////////-->
<!--</div>-->
<script src="../public/js/device_admin.js"></script>

<script>
    $(document).ready(function(){
 
});
     var table;
     var data;
     var myVar;
     var data2;
     var myVar2;
     var image_no=0;
    $(document).ready(function () {
       

       

    
  ///////table creation///////////////  
        table=$('#devicemanagement').dataTable( {
        "ajax": '<?php echo $this->basePath();?>'+"/tunnel/admin/device_mang",
        "deferRender": true
    } );
	
$("#devicemanagement_wrapper").attr("style","border:1px solid #d1d1d1; margin:10px 0;");
$("#devicemanagement_wrapper").addClass("clearfix");
$("#devicemanagement_wrapper div:first").removeClass("row");
 $("#devicemanagement_info").parent().parent().removeClass("row");
 $("#devicemanagement_wrapper div:first").attr("class","tbsearchrow clearfix");
    
 ///////end table creation///////////////  
//  $('#driver').on('click','.mydrivers',function(){
//      
//      
//      $("#page-wrapper").hide();
//     $("#driverprofile").show();
//     
//      var id = $(this).attr("data");
//     
//        driverProfile(id); 
//     
//  });
//$("#driver_wrapper").attr("style","border:1px solid #d1d1d1; margin:10px 0;");
//$("#driver_wrapper").addClass("clearfix");
// $("#driver_wrapper div:first").removeClass("row");
// $("#driver_info").parent().parent().removeClass("row");
// $("#driver_wrapper div:first").attr("class","tbsearchrow clearfix");
//
// });
    
$("#device_pdate").datepicker();   
 $("#device_adate").datepicker(); 
 $("#device_pdateR").datepicker();
 $("#device_adateR").datepicker();
});

</script>

<script>
 


</script>
                
