<?php $session=new Zend\Session\Container('admin');
if($session->offsetGet('adminuser')==''){?>
<script>
$(".adminlayout").css("display", "none");
</script>
 <?php	
}

if(isset($_GET['msglgOt'])){
    echo "<script>alert(".$_GET['msglgOt'].")</script>";
    // print_r($_GET['msglgOt']);die;
}

?>
<!DOCTYPE html>

<html lang="en">
<style>
.loader2{position:fixed;
top:250;
background:none;
z-index:1000000;
margin:auto;
margin-left:40%;}

</style>

<img src="/hello42/public/image/loading.gif" class="loader2" width="150" height="150">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
   
    <!-- MetisMenu CSS -->
    <link href="public/css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="public/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="public/font-awesome-4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<style>
.radio label, .checkbox label{margin-left:25px;}
</style>
</head>

<body>

    <div class="container">
        <div class="row" style="margin-top:10%;">
		
            <div class="col-md-4 col-md-offset-4" style="margin-top: -117px;">
			 
			
			<div class="row">
				<div class="col-col-lg-6" style=" float:right;padding: 0 16px;display:none;"><img src="<?php echo $this->basePath(); ?>/public/image/logo.png" alt="" /></div>
				<div class="col-col-lg-6" style="float: left;padding: 25px; float:left;"><h1>Admin</h1></div>
			</div>
                <div class="login-panel panel panel-default">
				
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <fieldset>
                                <p id="invalid" style="display:none;color:red;">Invalid Login and Password</p>
                                <div class="form-group">
                                    <input class="form-control" id="admin" placeholder="User Name" name="email" type="email" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" id="password" placeholder="Password" name="password" type="password" value="">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <a class="btn btn-lg btn-success btn-block" id="login">Login</a>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--<?php echo $this->basePath(); ?>-->
    <!-- jQuery Version 1.11.0 -->
    

    <!-- Metis Menu Plugin JavaScript -->
    <script src="public/js/plugins/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="public/js/sb-admin-2.js"></script>
    <script>
        var url='<?php echo $this->basePath();?>';
        $(document).ready(function(){
		$(".adminlayout").css("display", "none");
       $("#login").click(function(){
            $('#invalid').hide();
         $.ajax({
            
				        type: 'POST',
						//contentType: 'application/json',
				        url:url+'/tunnel/admin/login',
				        dataType: "json",
						data : {username:$('#admin').val(),password:$('#password').val()},		 
				        success: function(data){
				        		if(data.status=='true')
							{
                                                             window.open(url+'/admin/dashboard',"_self"); 
                                                            
                                                        }else{
                                              $('#invalid').show();              
                                                        }		
									
								
									},
				        error: function(error){
						
								console.log(error);	
						}
			});
       });    
            
            
            
    });
        </script>

</body>

</html>
